### ISSUE TITLE
Founder

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#1]
Docs: none
Team: @bisq-network/founders

**Comment by cbeams** [comment]
I've assigned myself here, reflecting my role as co-founder. Further details at https://github.com/bisq-network/roles/issues/2#issuecomment-343157142.

**Comment by cbeams** [comment]
## 2017.12 report

It's not obvious what should be written here in monthly reports for the co-founders, because ideally, founders have no role to play under the Bisq DAO, i.e., all responsibilities _should_ be captured under some other, specific role. The fact of the matter at present, though, is that the co-founders do still play an important role right now, which is playing all the roles that have not yet been delegated to other contributors. At present, I'm playing about 18 roles, and @ManfredKarrer is playing about 12, and this is far too many both from a bandwidth perspective and (most importantly) from a decentralization perspective. Rectifying this problem is, of course, the whole purpose of [Phase Zero](https://bisq.network/phase-zero), and I think we're beginning to build momentum on that front. We tried over the months of November and December to decentralize the operation of key infrastructure, e.g. seed nodes, price nodes and bitcoin nodes with mixed results, but also with lessons learned. The most important efforts right now with regard to realizing the Phase Zero goals, I believe, are to continue sorting out role specifications and bonding, and to continue our outreach efforts to grow the community of contributors. I'll keep pushing these things forward over the month to come, while trying to balance out against other pressing / urgent issues like infrastructure stability and cleaning up the messes created by timeouts last month.

Details aside, I'm excited about the momentum we're creating. Onward!


/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
## 2018.01 report

Nothing major to report this month, other than observing that the number of serious @bisq-network/contributors has been growing and that this a great and necessary thing for our decentralization goals. Welcome, all!

In general, my spirits are high and I'm feeling optimistic about Bisq's future. These last couple months have been intense, and at some points intensely frustrating as we had to deal with all the support issues and reimbursements, but in the end, I'm actually very glad we went through that exercise now; we're stronger for it. I'm also pleased to see how much attention we continue to get on Twitter and with podcast / interview requests. As I've mentioned elsewhere in this month's reports, we have a couple new interviews coming out shortly. All good stuff.

I'll leave it there for now. Cheers!

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

It's been an exciting month!

 - many contributions coming in from new contributors
 - word about Bisq is getting out there esp. via Twitter and YouTube
 - the USD liquidity week is going well
 - trading volumes are continuing to grow
 - I even made time to code this month!

Our focus needs to continue to be recruiting contributors. I think what we're doing on Twitter and YouTube may be the best way to do that. We're going to start doing regular "Tech Session" live streams similar to the couple "Q&A" sessions we did this last month. Hopefully these tech sessions can become a powerful recruiting tool as other developers get a sense of what we're doing, where they can add value and why it's worth their time to do so.

If anyone has other ideas about how to attract and bring up high-quality contributors, let's talk.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

I focused in a big way on coding this month, specifically around breaking up the bisq-* repositories, porting our builds from Maven to Gradle and getting some semi-ambitious refactoring done with @blabno around the new `bisq.asset` package. I also began work prototyping a new, core-level gRPC API and `bisq` command line client, but have not published any of that work just yet.

The reason for this focus on my part is because I believe setting these changes in motion is vital to the success of our efforts to scale up Bisq development. I'd much rather make these changes now, when relatively few are involved, than try to change them when there are many. And furthermore I believe that many of these changes—especially their effect in aggregate—can help in attract skilled developers, precisely because they see the kind of structure, organization, practices and coding standards that they find themselves at home with.

So we're doing things on a number of fronts now to grow the team of developers:

 - Improving the structure and organization of the codebase itself, as described above
 - Our Bisq 'tech session' series on YouTube (we've done two so far, and are aiming to do new ones weekly)
 - Building out ways to programmatically interact with Bisq, e.g. `mrosseel/bisq-api` and the gRPC API prototype mentioned above

Ultimately, I think we won't attract a lot of developers by "going out and recruiting them" per se. Rather, I think we must systematically transform Bisq into a hugely attractive ecosystem for developers to work on, around and within. I think we're doing that, step by step now, and while it's slow going in the beginning, I think we are creating the kind of solid foundation that can support a much larger Bisq developer community in the future.

With all that said, we shouldn't lose sight of the fact that our developer community has in fact been growing. Of particular note is @blabno's participation in the incubating mrosseel/bisq-api effort and his own incubating Ionic-based Bisq mobile app, which, as far as I can tell, already has several people working on it. It will be interesting to see how this effort plays out. It's been utterly permissionless, and without any planning or engagement on my or @ManfredKarrer's part as founders. I think that in any case we'll learn a lot from these kinds of efforts, and I look forward to seeing how it goes.

And in the meantime, volumes and trade counts continue to grow, and overall, Bisq is taking on that growth well. I'm able to keep up with my arbitration requests, and support issues haven't been too time consuming either (though I'd love to start handing this work off, as I've discussed elsewhere).

Add to that that @ManfredKarrer and @sqrrm are making serious progress on implementing the various functions of the Bisq DAO, and things are starting to look pretty good!

Altogether, I think it's a great time to be working on Bisq. Things are relatively quiet, and that means we can get a lot of important stuff done. @jlopp captured this well the other day in [this tweet](https://twitter.com/lopp/status/978621579885195264) (emphasis mine):

> These relatively quiet periods are the best, in my opinion. Haters are happy because they think Bitcoin is dead / dying. **Builders are happy because there are fewer distractions.** Traders are bored to tears. Trolls are grasping at straws trying to retain attention.

/cc bisq-network/compensation#57

**Comment by ManfredKarrer** [comment]
## 2018.04 report
I try to stay focused on the DAO development and get good progress there. We conducted a few tech sessions to spread better the technical base of Bisq. I also did a dev session specially for those who might do a code review on the DAO. 
I tried to help the API developers by refactoring the startup process and made some PRs for giving examples of the strategy I have in mind for doing such refactoring (small steps with mostly pure technical refactoring). 
Beside development efforts I joined discussions about payment methods, visual redesign and doing code review and merging PRs. 
We also started to hand over the release process and testing to @ripcurlx who will do the upcoming release.
Thanks to @cbeams I managed to stay out of most non-dev work and can focus on the DAO. Still try to keep a good high level overview of all whats going on in Bisq and verify if our priorities are set right.

**Comment by ManfredKarrer** [comment]
## 2018.05 report
Again I tried to focus mostly on DAO development but was also busy with the 0.7.0 release.

**Comment by cbeams** [comment]
## 2018.05 report

I missed posting my report here last month in part because I had a serious health issue come up and was short on time. I've since documented what's going on at https://chris.beams.io/posts/hello-aml/, and it's very likely that this issue will continue to affect my availability over the months to come.

This is actually a life-threatening problem, and while everything may turn out just fine in the end, it's appropriate for me to focus as much energy as I can now on turning over many of my roles and responsibilities to other contributors. It's been my express goal to do this in any case under the Phase Zero plan, but I now want to accelerate that process even more.

I believe the best way I can facilitate this transfer of knowledge and duties is to focus relentlessly on building out https://docs.bisq.network. This has already been a major focus for me over the last couple months, but I now plan to make it my main priority and to put my head down on it as much as possible. This effort will affect everyone, and you'll probably see and hear lots from me about it over the weeks to come. Keep in mind that the docs we're talking about here are not only the _user-facing_ docs that cover Bisq features; they are also the _contributor-facing_ docs that cover every aspect of Bisq DAO infrastructure and operations, roles and responsibilities, principles and processes. The goal for docs.bisq.network is that it become a comprehensive operators' manual for all things Bisq, one useful page at a time. This is why, as you can see in https://github.com/bisq-network/bisq-docs/pull/60, I'm currently working on a comprehensive table of contents for the site, even before all the pages are written. The purpose of that effort is to lay out a scalable structure for these docs into which everything we need to write can fit. As I continue to build out that table of contents, it should get clearer and clearer for everyone involved how important these docs can be for Bisq's future, as well as how you can personally contribute to them. 

So I have a couple things to ask of everyone:

1. Please pay attention to what's going on with docs, and understand that it is deeply strategic for us to build them out now. Good documentation can create a lot of leverage and can make a big difference as to whether Bisq and the Bisq DAO continue to scale up smoothly or not. If we continue growing like we have, we will soon be dealing with truly large numbers of users and contributors. We absolutely must have scalable ways to transfer knowledge and culture to them. Great docs are key to making that happen, and I'm hell-bent on putting them together now. This has to be a team effort to succeed though. Please ask yourself how and where you can contribute, and consider writing docs yourself, especially for anything you're already responsible for. @m52go has already contributed a lot, @blabno is working on some docs related to the new HTTP API right now, @alfsbs has started putting together docs for various payment methods, and everybody else is welcome to do the same for their own stuff too. Read the description and comments of https://github.com/bisq-network/bisq-docs/pull/60 for deeper context on all this, and come talk with us in the #docs Slack channel. We'll figure out what might make sense for you to work on, and even if you don't write anything, simply paying attention to what's going on, including reading and reviewing the docs that others write is itself an important contribution. If you haven't done so already, put a watch on the https://github.com/bisq-network/bisq-docs repository, and you'll be plugged into everything as it happens. Thanks!

2. Please start thinking about roles I currently play that you could take over. I've taken a conservative approach to handing off roles so far, and I need to relax and start giving stuff away to others, both so that I can focus on docs, and so that I don't burn myself out or try to do too much while I'm dealing with this health issue. Take a look at my recent compensation requests (including this month's at bisq-network/compensation#74) and ask yourself which roles you might be well-suited to take on. Even if it's a stretch for you, and you're not certain whether you're "qualified" or fully up to the requirements for some reason, that may not be a problem. What matters most is that you take on a role and manage it with pristine integrity, i.e. respond to all requests relating to that role in a timely fashion, monitor whatever resources you're responsible for, write monthly reports about your role on time every time, etc. It's all pretty simple really, and in most cases it's not the end of the world if you make a mistake. The most important things are that you're proactive and in communication at all times; that you take 100% responsibility for the roles you own and that you never let your role become someone else's problem. In any case, please look at the roles I'm playing and if you see one that makes you think "I would really like to do that work", then come talk to me about it the Slack channel associated with that role. Even if you think it won't work for some reason, I'd still like to have the conversation and see what might be possible. Thanks, all.

/cc bisq-network/compensation#74

**Comment by cbeams** [comment]
## 2018.06 report

I'm continuing to deal with my health issue, and this month most of the work I did was around docs as planned. Other contributors have stepped up during the month to take on some of my roles (thank you all very much), and many of these still require actual handoffs to occur, e.g. granting access rights and so on. This is all a good opportunity to write things down and formalize processes, and I'm prioritizing doing that in my current writing efforts. I'll likely continue to be operating at lower capacity this coming month, focusing on writing when I can work, but on the bright side, everything is going well with my treatments.

/cc bisq-network/compensation#89

**Comment by ManfredKarrer** [comment]
## 2018.07 report

I have been at the "Building on Bitcoin" conference in Lisbon and tried there to find developers. Had some interesting conversations but nothing concrete. Finding more developers is still my main priority beside getting the BSQ/DAO completed. Rough plan is to launch on testnet with end of August if we can achieve that. Chi is helping with testing and code review. Most features are already implemented and UI is getting to a better state as well. Beside DAO work I helped Joachim with the Mobile notification app. Desktop integration and server is mostly complete. Iphone version is also in a pretty good state. Android app needs a bit more dev effort and will be probably completed when Joachim is back from holiday.
Also added a PR for Face to Face trade as well as added some new proposals.

/cc bisq-network/compensation#93

**Comment by cbeams** [comment]
## 2018.07 report

Health issues continue to dominate for me, and likely will for the months to come, but I've still been able to get a few things done, as can be seen in my compensation request linked below.

As Manfred mentions in his update above, our major limiting factor remains that we have so few dedicated developers. It's a hard problem. We're competing with well-funded companies and still a great many would-be Bisq devs don't even know Bisq exists. We're a Java project in a native-dominated ecosystem, and I believe many of the best Java/JVM developers haven't even considered working in the Bitcoin space. Manfred and I have been brainstorming about ways to change that situation, but in the coming month, I'm going to turn my attention to some lower-level concerns and focus on development. I've spent a lot of time writing docs and working on administrative infrastructure for the Bisq DAO recently and need a change of pace; I'm eager to get some coding done, and it's something that I can do effectively given my current constraints. I've written a bit more about the specifics of what I'll be doing in the "Contributions in progress" section of my compensation request below.

In any case, I think slow and steady can win the race. We have real users, we're shipping useful features, and we'll soon see F2F trading, Bisq Remote and BSQ come online. While it may be fundamentally hard to "find developers", what we can do is to make sure we're building something that great developers will want to work on when they find it. Let's keep doing the best we can with what we've got.

/cc bisq-network/compensation#101

**Comment by ManfredKarrer** [comment]
## 2018.08 report

That month was quite busy on several fronts:
- DAO dev work, review, discussions
- 0.8.0 release
- Mobile notifications app
- Help out with Http API

Beside that a bit of strategic planning for the next releases (0.9.0 - rebranding, DAO testnet, maybe API) and trying to get communications around the DAO organized. We need to start early enough to explain a rather complex topic to our core users group. So that when we launch the DAO that people have a solid understanding.

It seems the latest releases have fixed quite a few bugs and we have less arbitration cases as it was earlier the case.

/cc bisq-network/compensation#112

**Comment by cbeams** [comment]
## 2018.08 report

My health situation took a turn for the worse early this month, leaving me partially (and hopefully only temporarily) paralyzed. As a result I've contributed very little to Bisq, and am focused primarily on my recovery, physical therapy, and other personal issues.

/cc bisq-network/compensation#114

**Comment by ManfredKarrer** [comment]
## 2018.09 report

I was traveling and took a bit of holiday break that month. Beside dev work I had 2 interviews (Cuen Leigh for Coindesk and Max Hillebrand for WCN (https://www.youtube.com/watch?v=j2_Oe7mlLDk).
I am preparing the testnet version of the DAO so that we can hopefully ship it with 0.9.0 mid/end of October.

/cc bisq-network/compensation#125

**Comment by cbeams** [comment]
## 2018.09 report

I continued to focus on my health issues this month. The paralysis mentioned in last month's report is slowly improving with physical therapy, and I'm now in a more dedicated rehabilitation facility where I can focus fully on the recovery process. I'm no longer bedridden and spend most of my time each day in a wheelchair.

I'm keeping up with my arbitration and Twitter duties and generally monitoring internal communications, but I'm taking a hands-off approach to anything that doesn't clearly need my input or specifically request my participation by @mention.

/cc bisq-network/compensation#139

**Comment by ManfredKarrer** [comment]
## 2018.10 report

Was a busy month. Main focus was to get the DAO ready for testnet release as well as to handle the overall management for the relase. Also lots of communication work with growth calls, interviews and communication with developers and contributors.

More dedicated efforts to find new developers and there are few good devs in our pipeline but some still have not fully commited.

Also worked on a few proposals. Most important the proposal for a new trade protocol without arbitration. Will try to get a dedicated team with Neiman to work on the implementation in parallel to the DAO mainnet launch.

Volume is growing a lot and brings Bisq more close to profitability. But also reminds us that we need to fix the open isses where Bisq is still not fully decentralized and censoship resistant.

/cc bisq-network/compensation#155

**Comment by cbeams** [comment]
## 2018.10 report

I'm thrilled to see all the progress happening around Bisq: the client and website redesign, the forthcoming DAO launch, the growing body of contributors, and of course this month's explosion in trading volume.

I can scarcely keep up with all that's going on, actually. My main focus remains on my health issues, and what time I do have to dedicate to Bisq is occupied mainly by arbitration duties and keeping up with Twitter. It pains me to be on the sidelines like this, but in some ways, I think it's a good thing. When I'm at full capacity, I have a tendency to get involved in everything, and working that way doesn't scale. Worse, it works against our decentralization goals. So I'm actually glad in a way that my circumstances are forcing me to play a smaller and more focused role now.

As for an update on my condition, I'm still doing intensive physical therapy to improve my mobility, but that may change soon as I also need to complete my cancer therapy. I'll know more about what's next in the coming week. If I go directly to the final step doing a bone marrow transplant, I may be out of commission entirely for some time. I'll keep Manfred posted in any case.

/cc bisq-network/compensation#160

**Comment by ManfredKarrer** [comment]
## 2018.11 report

Being very busy with getting the 0.9 release ready. Being in touch with several developers and coordinate work with them. 

/cc bisq-network/compensation#180

**Comment by cbeams** [comment]
## 2018.11 report

I'm home from the hospital now for the first time in four months, and am focusing on spending time with my family. I'm keeping up on arbitration duties and made some time this month to submit PRs that improve Bisq's command line user experience, as well as reviewed a number of build system and docs-related PRs. I'll be back to the hospital for a bone marrow transplant in late December or early January, and I'll keep doing what I can to contribute in the meantime.
 
/cc bisq-network/compensation#179

**Comment by cbeams** [comment]
UPDATE: I'll be taking a ~2 month hiatus from my work with Bisq, effective immediately. I'm scheduled to undergo a bone marrow transplant a little less than two weeks from now, and have many things to get in order beforehand. The transplant process itself will likely take at least 6 weeks, and I probably won't be fit to work during much of that time. I'm in the process of handing off most of my roles now. I may contribute a PR here and there as I have spare time and energy, and I'll do my best to respond to any @mentions, but otherwise, I'll be out completely for the next couple months. I look forward to returning!

**Comment by ghost** [comment]
Best luck @cbeams .
Return in better health. (I'm confident).

**Comment by ManfredKarrer** [comment]
## 2019.01 report

Main focus that month was to get DAO testnet version stable (issues with seed nodes and explorers) and onboarding and coordinating with new developers. 

/cc bisq-network/compensation#205

**Comment by ManfredKarrer** [comment]
## 2019.02 report

We had issues with using the Bitcoin testnet for DAO testing as one day 20 000 block got created which turned the block based timing for the phases un-usable. It showed again that testnet is not suitbale for application testing ;-(. We decided to move to a server based regtest mode as that was the fastest solution with least effort. Starting a private testnet would have caused more effort (seed node, fauce, miner, how to protect against asic causing the same issue...).
This delayed the 0.9.4 release but it was good that it happened earlier rather then later when more users are testing the DAO. 

/cc bisq-network/compensation#227

**Comment by ManfredKarrer** [comment]
A quick update regarding @cbeams health state:
Chris had his bone marrow transplant a few weeks ago and luckily all went very well and he is already released from hospital (earlier as expected) and back home! I am very happy to see he is recovering well! It still will take some time for full recovery so will take some time until we have him back at Bisq ;-).

**Comment by mrosseel** [comment]
Great news, was wondering how it was going.

**Comment by ManfredKarrer** [comment]
This was a very intense month with getting the DAO prepared for mainnet launch. We had some important fixes and changes which will require to start over with a new testnet. Mainly focussed to test the DAO for finding any possible attack or weakness.
Also started to re-distribute some nodes to other contributors and make sure we are good decentralized on the contributor base as well once we launch on mainnet.

Had some conversations with @cbeams as well. We agreed that we will dissolve the founder role with the mainnet launch as the project is then fully in the hand of the BSQ stakeholders.

**Comment by cbeams** [comment]
@ManfredKarrer wrote

> Had some conversations with @cbeams as well. We agreed that we will dissolve the founder role with the mainnet launch as the project is then fully in the hand of the BSQ stakeholders.

Confirming this from my side. Any work I do for Bisq in the future will be as a regular contributor.

I also wanted to note that recovery process after the stem cell transplant has turned out to be much more difficult and lengthy than I thought it would. I'll be going back to the hospital soon for dedicated physical therapy, and at this point I think it'll be another 6–12 months before I'll be ready to work again.

**Comment by sqrrm** [comment]
@cbeams All the best for your recovery. Think of Bisq as your distributed support network, always there and in need of more contributions whenever you're ready.

**Comment by ManfredKarrer** [comment]
@cbeams Thanks Chris for the update! Looking forward to see you back in Bisq but take all the time you need for your recovery. All the best!

**Comment by ripcurlx** [comment]
@cbeams Thanks for your message Chris! Take your time to fully recover and Bisq will welcome you better than ever, whenever you're ready!

**Comment by ghost** [comment]
@cbeams Thanks for the news, even if not so good. Take best care of yourself. Bisq will still be there in 6-12 months to welcome you back.

**Comment by ManfredKarrer** [comment]
As announced we will close that role now as the Bisq DAO is in place with the v1.0.0 release.
