### ISSUE TITLE
BSQ Explorer Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#103]
This role is responsible for maintaining the https://github.com/bisq-network/bisq-explorer repository. See also the BSQ Explorer Operator role at #11.

Docs: TBD
Team: @bisq-network/bsq-explorer-operators

**Comment by sqrrm** [comment]
## Cycle 12 report

There isn't much going on with the explorer code at the moment. The explorers are running well after wiz's efforts on the ops side.

https://github.com/bisq-network/compensation/issues/536

**Comment by sqrrm** [comment]
## Cycle 13 report

Nothing new with explorer repo.

bisq-network/compensation#564

**Comment by sqrrm** [comment]
## Cycle 14 report

Haven't touched this repo during this cycle

bisq-network/compensation#597

**Comment by sqrrm** [comment]
## Cycle 15 report

Wiz has worked on a BSQ explorer for mempool that looks really nice. Hope I can soon retire from this role.

https://github.com/bisq-network/compensation/issues/623

**Comment by wiz** [comment]
Yeah @sqrrm I think we can retire this role and archive the https://github.com/bisq-network/bisq-explorer repo now that we have https://github.com/bisq-network/mempool fork of it

**Comment by sqrrm** [comment]
## Cycle 16 report

I should retire.

bisq-network/compensation#646

**Comment by wiz** [comment]
# 🚨 This role is retired 🚨

At the end of Cycle 16, the Bisq Explorer repo has been obsoleted by the Mempool Explorer repo, so this role is obsoleted.

**Comment by cbeams** [comment]
Closing this role issue as no longer needed per @wiz's request, and I have also deleted the @bisq-network/bsq-explorer-maintainers team.
