### ISSUE TITLE
@leo816 to assume Support Team Lead role

### ISSUE THREAD

**Issue by leo816** [bisq-network/roles#105]
I would like to formally apply for this role,

My current roles include: 
-  Mediator: bisq-network/roles#83
-  Fee Reimbursement Agent: bisq-network/roles#76
-  Support Agent: bisq-network/roles#64

I have been involved with bisq for over 2 years now. I started making bisq's first ever tutorial video (https://www.youtube.com/watch?v=-o9CKiivyIc&t=1s) and then having a series of critical roles inside the support team that have made me very aware of how each one works. 
I am very passionate about this project and think I have gained enough knowledge through these years that make me an adequate candidate. 

I have added two more duties on the https://bisq.wiki/Support_Team_Lead that I think are inherent to the role, and that I happen to have done to some extent already:

- Review Team's Compensation requests as per Process.

- Manage new internship proposals and evaluate their performance once the period is over.

- Review and supervise the "on duty" schedule.

I'd like to hear if anyone, specially the @bisq-network/support have any suggestions or comments about which direction should the role develop into going forward.

**Comment by wiz** [comment]
My understanding is that you should make this issue in the proposals repo, the roles repo is for active roles
