### ISSUE TITLE
Bisq litigation

### ISSUE THREAD

**Issue by AureusNummusGold** [bisq-network/roles#106]
Dear Chris Beams,

This letter is addressed to you, the owner of Bisq.  

We approached Bisq with a listing request, as the Bisq technical set up had been of interest to us.
However, the process has been a thorough disappointment. First, per the instructions on your website the interested listing candidate is invited to write a pull request (which we did), only to find out that nobody deals with the pull requests, with no information offered as to why.

Then you were kind enough to respond to our message on keybase, which is much appreciated as I am sure you are a busy guy.

Yesterday, however, and very much to our disappointment, we discovered a comment by a Bisq member called “whiz”, who calls us a scam without offering any evidence or reason whatsoever. Neither this “whiz” individual nor anybody else from Bisq ever contacted us or asked us questions, nor did they perform any due diligence whatsoever. In a court of law this is referred to as “due process denied” and by itself represents a felony if intent can be proven. 

The standard of evidence is not zero. Alleging fraud without any evidence whatsoever necessarily will have consequences. Either put up or shut up and bear the consequences for falsehoods and hate comments in a court of law.

We are a FINTRAC and FINCEN registered company based in onshore jurisdictions with verifiable public corporate books and we do take our business very seriously. 

We offered to Bisq 1 BTC to cover the listing costs and 150,000 USD for market making as we do understand of course that trading volume is a key aspect for us and for the exchange. 
We were under the impression that Bisq would like to grow its business, but instead it appears that it has a serious troll issue within its rank and file. 

If you want to allege something please do so with the authorities and show your evidence. 
Allowing and enabling members of the Bisq organization to arbitrarily insult the general audience or listing candidates, and accuse them publicly and falsely of scam, while not offering the slightest piece of evidence is neither worthy of a CMC included exchange nor will it do any good to your business objectives and, more importantly, it will have legal consequences. 

Trolling, slandering, hate and vitriol are the internet’s pandemic, committed by individuals hidden behind anonymous. As a CMC included exchange your standards should be higher than the usual internet trolls.

The Bisq member “whiz” hides behind anonymous, while spraying vitriol and falsehoods. “whiz” doesn’t have the sack to show his face, his real name and his address, as he knows perfectly well that legal action would be hand delivered to his door step within days.

The 2nd Bisq member “csjones” takes offense in us using caps lock. A review of the “csjones” profile picture reveals that it has been used under 4 completely different names since the 1st of December 2015 in different accounts. I am sure law enforcement will be interested in that as well. 

We will file litigation against Bisq, its members, and John Doe, and we will publish this lawsuit of course here on GitHub, in all social media and send it to CMC. Stay tuned. 

Kind regards,

Your Aureus Nummus team

**Comment by MwithM** [comment]
You have a 22.8k word Terms and Conditions so you must be a very legit business.
There's no Bisq owner, this is a decentralized project.
You can still buy BSQ and burn it as a donation to the project, if you think it's necessary. Now, new asset listings are [on hold](https://github.com/bisq-network/proposals/issues/166). I didn't know you were offering 1BTC to list your very legit business.

**Comment by AureusNummusGold** [comment]
> You have a 22.8k word Terms and Conditions so you must be a very legit business.
> There's no Bisq owner, this is a decentralized project.
> You can still buy BSQ and burn it as a donation to the project, if you think it's necessary. Now, new asset listings are [on hold](https://github.com/bisq-network/proposals/issues/166). I didn't know you were offering 1BTC to list your very legit business.

Being decentralized does not provide protection or immunity from and against legal action. Any organization, any undertaking comes down to one  or more human beings, the beneficiaries. You better contact legal aid if you cannot afford proper legal advice. 

This really begs the question, why that unnecessary unprofessional and stupid behaviour. What are you? Is Bisq a serious business or a bunch of immature /criminal trolls hiding behind anonymous? Do you want to advance a serious business or be happy to engage in felony trolling?

What is this nonsense about?
