### ISSUE TITLE
BSQ Explorer Operator

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#11]
This role is responsible for operating an instance of the BSQ explorer webapp. See also the BSQ Explorer Maintainer role at #103.

Docs: TBD
Team: @bisq-network/bsq-explorer-operators 

Instances and their operators: 
- bsq.ninja (@wiz)
- bsq.sqrrm.net (@sqrrm)
- bsq.bisq.services (@devinbileck)
- bsq.vante.me (@mrosseel)
- bsq.emzy.de (@Emzy)
- bsq.bisq.cc (@m52go)

**Comment by ManfredKarrer** [comment]
@sqrrm @KanoczTomas : Would you be ok to take over the BSQ explorer role after the DAO launch? 
We should have 2 explorers running for resilience.

**Comment by sqrrm** [comment]
Yeah, I'm good to run one explorer instance. Would be great if someone with some web dev experience could take over the development though.

**Comment by sqrrm** [comment]
@KanoczTomas From what I understand you have some more experience on the operations side so you're probably better situated to improve on the stability of running the explorers. I'm already running one and if you run the other we should get together to figure out what we can do to make them better.

**Comment by KanoczTomas** [comment]
@ManfredKarrer yes, I am ok with running a second instance.

@sqrrm it would be perhaps interesting to somehow move the BSQ explorer to esplora if the current one has problems with developement. Esplora uses electrs in the background, so maybe if bisq dao created a json in the format as electrs returns it would be a way to go. It if just a thought for now. Would require more analysis of the code.

I will create a vm and contact you how to proceed @sqrrm .

**Comment by ManfredKarrer** [comment]
@KanoczTomas Yes basically that would be good but will require more work to see what is needed. After the DAO launch we can look into it.

**Comment by sqrrm** [comment]
## 2019.03 report

Started as explorer operator/maintainer. I'm running one node for betanet right now at explorer.sqrrm.net/betanet

Will move that over to mainnet when we go live, which shouln't be much of a problem as betanet is already on mainnet but with test BSQ.

https://github.com/bisq-network/compensation/issues/253

**Comment by KanoczTomas** [comment]
I will take over the role from april 1. I had no time to setup the 2nd node yet, as planned. Will do in the coming days.

**Comment by sqrrm** [comment]
## Cycle 1 report

I've been running an explorer, both clearnet and onion on https://explorer.sqrrm.net/ and murt7p2srbvorslyhud2rvvg2dkjpmtmku5p67lms72hqmuauibbisqd.onion respectively. 

There has been no issues with the setup during the first cycle. I don't even think I've restarted the seednode once. I plan on moving this to explorer2.bisq.network or something like that as well.

https://github.com/bisq-network/compensation/issues/282

**Comment by ManfredKarrer** [comment]
@sqrrm Takes over primary role owner

**Comment by sqrrm** [comment]
## Cycle 2 report
I have taken over primary role owner. I'm also managing both explorers. The explorers have been running without problem but they're rather primitive. It would be good to get someone to take over this role and the management of the explorers.

https://explorer.bisq.network/
https://explorer.sqrrm.net/

https://github.com/bisq-network/compensation/issues/293

**Comment by sqrrm** [comment]
## Cycle 3 report

Running two explorers

https://explorer.bisq.network/
https://explorer.sqrrm.net/

There was quite a lot of trouble with the explorer nodes this cycle. I think the seed nodes are not stable when dumping DAO data to disk and the monitor then reads it. It would probably be better if there was an api for the explorer to get the data from the seed node.

It's also really slow to parse from genesis, each block taking up to 20s, that needs to be investigated.

https://github.com/bisq-network/compensation/issues/311

**Comment by sqrrm** [comment]
## Cycle 4 report

Running two explorers

https://explorer.bisq.network/
https://explorer.sqrrm.net/

Fixed quite a few issues with the explorers, they're now running smoother but still require quite a lot of attention.

bisq-network/compensation#325

**Comment by sqrrm** [comment]
## Cycle 5 report

Running two explorers

https://explorer.bisq.network/
https://explorer.sqrrm.net/

There are some issues with the explorer, would need more time to look at it. Main issue has still been the stability of the seed nodes but seems to be better with the latest version.

https://github.com/bisq-network/compensation/issues/356

**Comment by sqrrm** [comment]
## Cycle 6 report

Running two explorers

https://explorer.bisq.network/
https://explorer.sqrrm.net/

Explorers have been needing restart a few times, although it's possible they would've recovered with the automatic restart.

https://github.com/bisq-network/compensation/issues/375

**Comment by sqrrm** [comment]
## Cycle 7 report
Running two explorers

https://explorer.bisq.network/
https://explorer.sqrrm.net/

There are some issues after the latest upgrade so explorer.bisq.network is still running a seednode on 1.1.6

https://github.com/bisq-network/compensation/issues/403

**Comment by sqrrm** [comment]
## Cycle 8 report

Running two explorers

https://explorer.bisq.network/
https://explorer.sqrrm.net/

Running ok now. Bitcoind crashed once.

bisq-network/compensation#441

**Comment by wiz** [comment]
test

**Comment by wiz** [comment]
test

**Comment by sqrrm** [comment]
## Cycle 9 report

I have moved to running only bsq.sqrrm.net. Costs are up as it's a vps with large ssd rather than a hd.

Also ran two explorers https://explorer.bisq.network/ https://explorer.sqrrm.net/ that will soon be decommissioned

There are now 6 explorers run by @wiz @sqrrm @devinbileck @mrosseel @Emzy @m52go 

bisq-network/compensation#461

**Comment by Emzy** [comment]
## Cycle 9 report

- Setup of one explorer 

- Running one explorer
https://bsq.emzy.de/ 

/cc bisq-network/compensation#467

**Comment by mrosseel** [comment]
Cycle 9 report

* setup of one explorer
* running of one explorer at https://bsq.vante.me/

/cc bisq-network/compensation#468

**Comment by devinbileck** [comment]
## Cycle 9 report

I have setup and am now running a BSQ explorer.
- https://bsq.bisq.services

https://github.com/bisq-network/bisq/pull/3861

### Requested Compensation
- 40 USD for server costs (4 CPU, 8 GB RAM)
- 35 USD for storage costs (350 GB)
- 50 USD for maintenance/operational costs

Total: 120 USD

/cc [bisq-network/compensation#472](https://github.com/bisq-network/compensation/issues/472)

**Comment by Emzy** [comment]
## Cycle 10 report

- Running one explorer
https://bsq.emzy.de/ 

/cc bisq-network/compensation#484

**Comment by devinbileck** [comment]
## Cycle 10 report

Running 1 instance. Nothing to report this cycle.

/cc [bisq-network/compensation#481](https://github.com/bisq-network/compensation/issues/481)

**Comment by sqrrm** [comment]
## Cycle 10 report

Running one instance at bsq.sqrrm.net, had one issue with the seednode getting in conflict with the DAO state. Don't know why, and it looks like some other seed nodes had the same issue.

bisq-network/compensation#488

**Comment by Emzy** [comment]
## Cycle 11 report

- Running one explorer
https://bsq.emzy.de/ 

/cc bisq-network/compensation#508

**Comment by mrosseel** [comment]
## Cycle 10&11 report

* running one explorer at https://bsq.vante.me/

/cc bisq-network/compensation#511

**Comment by devinbileck** [comment]
## Cycle 11 report

Running 1 instance. Nothing to report this cycle.

/cc [bisq-network/compensation#512](https://github.com/bisq-network/compensation/issues/512)

**Comment by wiz** [comment]
## Cycle 11 report

Running my [bsq.ninja](https://bsq.ninja) explorer - nothing to report

/cc bisq-network/compensation#515

**Comment by cbeams** [comment]
@wiz, please update https://github.com/orgs/bisq-network/teams/explorer-maintainers/members and the description of this issue to reflect the actual set of BSQ explorer operators, thanks.

**Comment by cbeams** [comment]
> @wiz, please update https://github.com/orgs/bisq-network/teams/explorer-maintainers/members and the description of this issue to reflect the actual set of BSQ explorer operators, thanks.

Sorry, scratch the first part of that request. I was confusing the @bisq-network/bsq-explorer-maintainers group with the @bisq-network/bsq-explorer-operators team. These roles need to be separated out, I'm doing that now.

**Comment by cbeams** [comment]
Ok, I've just separated out the BSQ explorer operator and maintainer roles. This role represents the operator role and has been renamed accordingly. @sqrrm has agreed to own the maintainer role, and #103 has been created to reflect.

@wiz, please paste a definitive list here of which operator operates which instance and I'll update the description accordingly.

I've already updated the assignee list. @bisq-network/bsq-explorer-operators, please continue to issue your cycle reports here, thanks.

**Comment by wiz** [comment]
https://github.com/bisq-network/bisq/blob/master/core/src/main/java/bisq/core/user/Preferences.java#L110

bsq.ninja (@wiz)    
bsq.sqrrm.net (@sqrrm)    
bsq.bisq.services (@devinbileck)    
bsq.vante.me (@mrosseel)    
bsq.emzy.de (@emzy)    
bsq.bisq.cc (@m52go)

**Comment by sqrrm** [comment]
## Cycle 12 report

Running one instance at https://bsq.sqrrm.net, no issues.

bisq-network/compensation#536

**Comment by devinbileck** [comment]
## Cycle 12 report

Running 1 instance at https://bsq.bisq.services/.
I recently increased disk size to 400GB since it was close to getting full.

/cc [bisq-network/compensation#531](https://github.com/bisq-network/compensation/issues/531)

**Comment by Emzy** [comment]
## Cycle 12 report

- Running one explorer
https://bsq.emzy.de/ 

/cc bisq-network/compensation#541

**Comment by mrosseel** [comment]
## Cycle 12 report

* running one explorer at https://bsq.vante.me/

/cc bisq-network/compensation#543

**Comment by wiz** [comment]
## Cycle 12 report

https://bsq.ninja/ running stable with latest patches

https://github.com/bisq-network/compensation/issues/547

**Comment by devinbileck** [comment]
## Cycle 13 report

Running 1 instance at https://bsq.bisq.services/.
Increased TMPFS allocation for growing datastore, see https://github.com/bisq-network/bisq/pull/4246.

/cc [bisq-network/compensation#560](https://github.com/bisq-network/compensation/issues/560)

**Comment by mrosseel** [comment]
## Cycle 13 report

* running one explorer at https://bsq.vante.me/
Needed updates because of dao bug, but kept lagging.
Still debugging

/cc bisq-network/compensation#562

**Comment by Emzy** [comment]
## Cycle 13 report

- Running one explorer
https://bsq.emzy.de/ 

Increased TMPFS allocation for growing datastore, see bisq-network/bisq#4246.

/cc bisq-network/compensation#570

**Comment by sqrrm** [comment]
## Cycle 13 report

Running one instance at https://bsq.sqrrm.net, no issues.

bisq-network/compensation#564

**Comment by wiz** [comment]
## Cycle 13 report

* Other than minor patch needed for TMPFS issue, running stable

/cc https://github.com/bisq-network/compensation/issues/569

**Comment by devinbileck** [comment]
## Cycle 14 report

Running 1 instance at https://bsq.bisq.services/.
Nothing to report.

/cc [bisq-network/compensation#593](https://github.com/bisq-network/compensation/issues/593)

**Comment by Emzy** [comment]
## Cycle 14 report

- Running one explorer
https://bsq.emzy.de/ 

Nothing to report.

/cc bisq-network/compensation#595

**Comment by sqrrm** [comment]
## Cycle 14 report

Running one instance at https://bsq.sqrrm.net. Had some issues and had to upgrade to latest seed node, which turned out to be quite painful as the scripts had changed the name of the seed node service. Now running ok

bisq-network/compensation#597

**Comment by mrosseel** [comment]
## Cycle 14 report

* running one explorer at https://bsq.vante.me/
Reinstalled from scratch due to not working anymore, scripts didn't like updating.
Now it's running again but still lagging, investigating.

/cc bisq-network/compensation#601

**Comment by wiz** [comment]
## Cycle 14 report

https://bsq.ninja/ is running stable

/cc https://github.com/bisq-network/compensation/issues/602

**Comment by m52go** [comment]
## Cycle 14 Report

https://bsq.bisq.cc has been running better with the increased tmpfs allocation but still seems to lag occasionally.

https://github.com/bisq-network/compensation/issues/604

**Comment by mrosseel** [comment]
## Cycle 15 report

* running one explorer at https://bsq.vante.me/
Was still lagging, but now there's a cron job restarting every hour which makes these lags go away rather quickly so it's no longer an issue.

/cc bisq-network/compensation#615

**Comment by Emzy** [comment]
## Cycle 15 report

- Running one explorer
https://bsq.emzy.de/ 

- redirects now to mempool.emzy.de/bisq

/cc bisq-network/compensation#617

**Comment by sqrrm** [comment]
## Cycle 15 report

1 explorer in operation, been current since fixing some stuff last month. Looking forward to moving to the mempool explorer

https://github.com/bisq-network/compensation/issues/623

**Comment by devinbileck** [comment]
## Cycle 15 report

Running 1 instance at https://bsq.bisq.services/.
Nothing to report.

/cc [bisq-network/compensation#621](https://github.com/bisq-network/compensation/issues/621)

**Comment by m52go** [comment]
## Cycle 15 Report

Running 1 instance at https://bsq.bisq.cc. Nothing to report.

https://github.com/bisq-network/compensation/issues/631

**Comment by wiz** [comment]
## Cycle 15 report

* Launched new Bisq Explorer at mempool.space/bisq per https://github.com/bisq-network/projects/issues/37
* Redirecting bsq.ninja -> mempool.space/bisq per https://github.com/bisq-network/projects/issues/37#issuecomment-660492410

/cc https://github.com/bisq-network/compensation/issues/632

**Comment by mrosseel** [comment]
## Cycle 16 report

* running one explorer at https://bsq.vante.me/

/cc bisq-network/compensation#638

**Comment by Emzy** [comment]
## Cycle 16 report

- Running one explorer on mempool.emzy.de/bisq

/cc bisq-network/compensation#644

**Comment by devinbileck** [comment]
## Cycle 16 report

Running 1 instance at https://bsq.bisq.services/.
This cycle I performed the following tasks:
- [Added onion-location HTTP header](https://github.com/bisq-network/ops/issues/5#issuecomment-671638719)
- [Enabled DNSSEC](https://github.com/bisq-network/ops/issues/7#issuecomment-674311005)
- [Enrolled in HSTS preload list](https://github.com/bisq-network/ops/issues/6#issuecomment-674308640)

/cc [bisq-network/compensation#647](https://github.com/bisq-network/compensation/issues/647)

**Comment by m52go** [comment]
## Cycle 16 Report

Running 1 instance at https://bsq.bisq.cc. 

Looked into enabling DNSSEC but my registrar doesn't support it for my TLD. May need to move to another domain name.

/cc https://github.com/bisq-network/compensation/issues/649

**Comment by sqrrm** [comment]
## Cycle 16 report

Running 1 old style explorer

bisq-network/compensation#646

**Comment by wiz** [comment]
## Cycle 16 report

* My old Bisq Explorer bsq.ninja is redirected to the new Mempool Explorer instance mempool.space

/cc https://github.com/bisq-network/compensation/issues/650

**Comment by wiz** [comment]
# 🚨 This role is retired 🚨

At the end of Cycle 16, this role is eliminated and replaced by the [Mempool Explorer Operator](https://github.com/bisq-network/roles/issues/107) role. Please upgrade your BSQ Explorer to Mempool Explorer when possible.

**Comment by cbeams** [comment]
Closing as superseded by #107 per @wiz's request, and I've renamed @bisq-network/bsq-explorer-operators team to @bisq-network/mempool-operators accordingly.

**Comment by sqrrm** [comment]
## Cycle 17 report
Since migration is still not completed I report my BSQ explorer here, it's running.

https://github.com/bisq-network/compensation/issues/667

**Comment by m52go** [comment]
## Cycle 17 Report

Running 1 instance at https://bsq.bisq.cc...have not migrated to mempool yet.

/cc https://github.com/bisq-network/compensation/issues/676

**Comment by mrosseel** [comment]
## Cycle 17 report

* running one explorer at https://bsq.vante.me/
- added HSTS
- TODO: https://github.com/bisq-network/ops/issues/7
- TODO: https://github.com/bisq-network/ops/issues/5

/cc bisq-network/compensation#681

**Comment by mrosseel** [comment]
## Cycle 18 report

* running one explorer at https://bsq.vante.me/
- added HSTS
- TODO: https://github.com/bisq-network/ops/issues/7
- TODO: https://github.com/bisq-network/ops/issues/5

/cc bisq-network/compensation#691

**Comment by sqrrm** [comment]
## Cycle 18 report

I have setup a server for mempool but it's taking a while to get it running properly. Until then, I'm running https://bsq.sqrrm.net

https://github.com/bisq-network/compensation/issues/693

**Comment by m52go** [comment]
## Cycle 18 Report

Running 1 instance at https://bsq.bisq.cc.

/cc https://github.com/bisq-network/compensation/issues/702

**Comment by m52go** [comment]
## Cycle 19 Report

Now that my instance is removed from v1.5.0, I'll be taking it offline shortly.

EDIT: explorer is now offline. Visitors are told the explorer has been depcrecated and should instead visit https://explorer.bisq.network to be redirected to other instances. The domain name expires in January, and I don't plan to renew it.

**Comment by mrosseel** [comment]
## Cycle 19-25 Report

running one explorer at https://bsq.vante.me/
