### ISSUE TITLE
Reimbursement for trade yhqfamml

### ISSUE THREAD

**Issue by TheTotalConnector** [bisq-network/roles#112]
Hi, I overlooked a failed tx with possibly lost miner fee from Dec1st 2022. 

My lost mining fee?: Taker: 0.00006990 BTC

Taker fee tx ID: 0f44f29dcfefc6576693f08b06c9d16f02ed29b5b483ed01704cdb3d0c758266

Please, see alos screenshot for further detaills. 
Thanks.

**Comment by leo816** [comment]
Hi @TheTotalConnector , please create the reimbursement request here: https://github.com/bisq-network/support/issues

create an issue copying the same format as the rest

**Comment by cbeams** [comment]
Closing as invalid
