### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Chordbridge** [bisq-network/roles#113]
I was told to upload the log.  Here it is.

**Comment by Chordbridge** [comment]
I hope the file arrived.

**Comment by Chordbridge** [comment]
[exception_29_12.log](https://github.com/bisq-network/roles/files/13792875/exception_29_12.log)

**Comment by pazza83** [comment]
Hi @Chordbridge 

What are these logs in relation to? 

What contributor advised you to upload your logs here? This is the roles repository.

**Comment by cbeams** [comment]
Closing as invalid
