### ISSUE TITLE
Arbitrator (legacy 2-of-3 model)

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#13]
This role is responsible for arbitrating Bisq exchange trade disputes.

See:

 - The [Arbitration section](https://github.com/bisq-network/docs/blob/master/exchange/whitepaper.adoc#arbitration) of the original Bisq whitepaper 
 - The dedicated [Arbitration System]( https://docs.google.com/document/d/1DXEVEfk4x1qN6QgIcb2PjZwU4m7W6ib49wCdktMMjLw/edit) doc

**Comment by cbeams** [comment]
## 2017.12 report

I serviced approximately 55 trade disputes during the month of December, which is many more than usual (I don't have exact stats for comparison as this is the first month I'm reporting these numbers).

A number of these trades were challenging and drawn out due to blockchain congestion causing slow trade confirmations. Indeed, it's these delayed confirmations that required most trades to be opened in the first place.

Something that came up multiple times in the process was what to do about "no-fault" disputes, e.g. when an external force causes a trading window to be exceeded. I had several lengthy discussions about this with traders, and would like to put together some kind of discussion that will move toward a policy on this matter. Trade `WQYVFAKS` in particular is important here. It was the most detailed conversation I had with traders on this matter, and both traders agreed to let me use the transcript of our chats to help in discussing and crafting this policy. I am going to have to come back to this later, but wanted to document it here briefly for future reference.

Another major issue this month was timeouts on maker/taker transactions causing lost fees. @ManfredKarrer believe's he's got this problem nailed down (It's bitcoinj not being able to handle transactions with dependent v2 transactions), but it remains to be seen whether this will actually solve the problem. In the meantime, I'm still working through a considerable backlog of these issues to get everyone affected reimbursed or otherwise appropriately taken care of. This has been a huge drain on my time.

A final issue that came up this month was dropping of arbitration chat messages. This has only happened a few times, and we believe it was due to unstable seed nodes or something in the new netlayer Tor library we're using. @keo-bisq and I have been dealing with this in a variety of ways, and we believe that everyone is getting taken care of, but even the possibility that we cannot see a trader's message, or that they cannot see ours adds a level of uncertainty to the arbitration process that ends up eating a lot of time and energy. @ManfredKarrer has rolled back the netlayer changes in our seed nodes (where mailbox messages get queued on the network), and we'll see how that works. Again, I only experienced this issue several times, and I have not experienced it since the rollback, so we may be out of the woods on this one, but we still have to be on high alert.

Overall, these issues notwithstanding, arbitration still went quite well this month. In the end, we were able to keep up with the huge surge in trading volumes, but it certainly stress-tested the system (and us as arbitrators) in the process.

**Comment by cbeams** [comment]
## 2018.02 report

I arbitrated ~30 trade disputes this month, and the second half of the month was very quiet. Many days went by without a single ticket coming in, which is unusual.

I'm still seeing occasional dropped arbitration messages, and I've logged them at https://github.com/bisq-network/exchange/issues/1173.

A number of trades continued to suffer from dropped trade protocol messages, and I've logged them. It seems to be the "Payment Started" message not getting through most of the time. I've logged these as well at https://github.com/bisq-network/exchange/issues/1174.

Additionally, several times this month people dealt with an error in which Bisq claims the user has funds locked up in a failed trade. The popup that explains this pops up over and over again. I experienced this myself when doing a test trade with @flix1. It seemed to be caused by me clicking "Payment Started" on our trade when his client was not online. My client was never able to send the message, and then at some point, possibly after restarting Bisq, my client started to raise this popup repeatedly as well. I worked with @keo-bisq to get the trade dispute closed out and the problem went away. This problem needs to be properly documented, though, and it hasn't been yet.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

I arbitrated 40 cases this month.

Major issues continue to be:

 - dropped "Payment Started" trade protocol messages (bisq-network/support#84)
 - failed bitcoin transaction broadcasts (bisq-network/support#94)
 - dropped arbitration chat messages (bisq-network/support#85)

By far the most important issue to fix is dropped 'Payment Started' trade protocol messages.

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

I arbitrated 45 cases this month.

Major issues continue to be:

 - dropped "Payment Started" trade protocol messages (bisq-network/support#84)
 - dropped arbitration chat messages (bisq-network/support#85)

A seemingly disproportionate number of issues came up around the new N26/MoneyBeam payment method as well. Buyer's having issues adding seller's to their contact book or some such, and before they did it, they couldn't send the seller more than 100 EUR. I don't yet have a support tracking issue for this, but need to get one set up. Heads up, @bisq-network/payment-method-experts.

By far the most important issue to fix remains the dropped 'Payment Started' trade protocol messages.

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
The following is our dispute-to-trade ratios over the last 5 months:

```
2017.12: (55*2)/711 = 15.5%
2018.01: (50*2)/620 = 16.1%
2018.02: (30*2)/576 = 10.4%
2018.03: (40*2)/792 = 10.1%
2018.04: (45*2)/976 = 9.2%
```

The numerator is the estimated number of disputes arbitrated, taking my own values as tracked in the monthly reports above, and multiplying it by 2 to take into account the likely number of trades that @keo-bisq arbitrated as well.

The denominator is the total number of trades processed on the network in that month.

The resulting percentage is our "dispute rate".

I would estimate that we can get this value down to 6% just by fixing the known issue around dropped "Payment Sent" protocol messages (bisq-network/support#1174).

**Comment by ManfredKarrer** [comment]
@cbeams Regarding the messages after closed: We could add a feature to auto-re-open a ticket if you receive a message later, including the red icon so you see that there is something open. A different close feature would be the required as well (as current close makes the payout tx).

To not close a ticket as long you have not received from both traders the confirm msg would be another good feature.

**Comment by cbeams** [comment]
Thanks, @ManfredKarrer. I've copied that comment over to the dedicated issue at bisq-network/bisq-desktop#1561.

**Comment by cbeams** [comment]
## 2018.06 report

I performed arbitration for 52 disputes this month (second highest number since I started counting in December, and it was the big run-up in December that had 55 disputes). Many were failed trades due to timeouts / non-broadcast txns, some were due dropped trade protocol messages, many were due to run-of-the mill mistakes and protocol violations. I certainly ran into several dropped arbitration messages along the way; very much looking forward to the ACK messages in v0.7.1 helping us to track this stuff down.

/cc bisq-network/compensation#89

**Comment by cbeams** [comment]
## 2018.07 report

I performed arbitration for 27 disputes this month. This is a steep drop off from recent months, which may be attributable to lower-than-usual overall Bisq trading volume in July, the new ACK messages that came out in v0.7.1  to help avoid dropped trade protocol messages, or a combination of both. Let's see how the trend continues to play out over the months to come.

/cc bisq-network/compensation#101

**Comment by cbeams** [comment]
## 2018.09 report

I resumed my arbitration duties this month, and performed arbitration for 23 disputes. This number is lower than it would have been, as Manfred was still registered for a number of cases that started the month prior but only went to arbitration after the 1st of the month.

Noteworthy issues:

 - I had 3 or 4 cases where dropped arbitration messages caused significant problems, slowing down and confusing the resolution process.
 - I had two failed trades where transactions failed to broadcast. Such issues have been rare lately, so it was surprising to see these two: bisq-network/support#139, bisq-network/support#140.
 - I created the following issue to deal with a known UX problem where buyers select the wrong bank account at payment time, causing particularly time-consuming arbitration disputes: bisq-network/bisq#1733

/cc bisq-network/compensation#139

**Comment by cbeams** [comment]
## 2018.10 report

I arbitrated 68 disputes this month, and as @ManfredKarrer reported at https://github.com/bisq-network/proposals/issues/52#issuecomment-433663600, quite a few are due to bugs / networking issues. The most common ones this month are dropped trade protocol messages between buyer and seller, where the seller doesn't know the buyer has initiated payment because the 'Payment Started' message never gets to the seller, or the seller's 'Payment Received' message never makes it to the buyer's client. These issues are happening even though the affected clients report that the message was 'received by peer'. In any case, these all end up in arbitration, and as Manfred reported, they are responsible for something like 40% of all cases.

On the bright side, it's good to see that the number of disputes has not gone up linearly with the number of trades during this recent volume spike. 68 is certainly more than I usually do in a month, but only by 10 or 20, i.e. a 25% or so increase. That's pretty good considering that we doubled the number of trades we usually do this month (2000 vs 1000). Much of this can be attributed to the fact that most of this month's volume increase was Monero-related, and that Monero users are generally more sophisticated and less likely to end up with disputes, but it doesn't explain why we wouldn't see 2x as many bug-related disputes.

In any case, getting somebody to work on these dropped message bugs is important.

/cc bisq-network/compensation#160

**Comment by cbeams** [comment]
## 2018.11 report

I arbitrated 91 disputes this month. Common causes were similar to those reported last month, including:

 - Buyer's 'Payment Started' message not being received by seller 
 - Bitcoin transaction broadcast failures

Manfred believes he may have solved one of the causes of messages being dropped. We'll see how that fix plays out with the release of 0.9.0.

/cc bisq-network/compensation#179

**Comment by cbeams** [comment]
Per https://github.com/bisq-network/roles/issues/1#issuecomment-444857417, I've handed off my arbitration duties to another contributor that will remain anonymous for now. I generally plan to pick this duty back up when I return.

**Comment by cbeams** [comment]
Closing as superseded by Refund Agent at #93 (which will actually be renamed to Arbitrator shortly). In any case, @keo-bisq and @Arbitrator22 have revoked their legacy arbitration keys and are no longer performing this role.
