### ISSUE TITLE
GitHub Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#16]
Docs: WIP at https://github.com/bisq-network/bisq-docs/pull/64 (should move to https://bisq.wiki/GitHub_Admin)
Team: @bisq-network/github-admins 

Note: @ripcurlx uses the Owner-privileged service account @bisq-github-admin-3 to perform GitHub administration duties.

**Comment by cbeams** [comment]
## 2017.12 report

 - Experimented with GitHub's new 'team discussions' feature, and discovered that it's not ready for primetime / suitable for our uses under the Bisq DAO. Perhaps that will change.
 - Performed usual admin activities related to creating new repositories, assigning access rights, etc.
 - Migrated from having bisq-network/github act as the 'root node' for our org and all its repositories (i.e. where our `.mrconfig` is stored) to having this managed under bisq-network/dao.

There were no major changes or incidents otherwise.

/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
## 2018.01 report

We started using Atomist this month as a replacement for Slack's built-in GitHub integration. You've probably seen the @atomist bot in most of our channels reporting commits and comments on GitHub issues and pull requests, etc. This is just the beginning of what Atomist can do, though. It's really all about automating the process of development itself (or automating everything about development that _can_ be automated anyway). People can read up about it elsewhere, but I'm excited about how Atomist can take our already pretty serious GitHub-fu to the next level and make a lot of the stuff I do manually happen automatically.

Note that Atomist is also built by a lot of my old friends and colleagues from the Spring team, so I'm extra excited about it, as they have a tendency to build excellent, useful things. I've already had some initial chats with them about what we're up to with the Bisq DAO and how Atomist might be able to help. We'll see where it goes.

Otherwise, there's not much to report. Just basic day-to-day GitHub admin activities like inviting new contributors to the @bisq-network org, managing team memberships, creating repositories, etc.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

Not much to report this month.

GitHub published a new `/github` Slack app that looks promising. I'll be replacing our old Slack GitHub integration over the next month, and possibly swapping out Atomist for the new native GitHub app if the latter seems like a complete replacement for what we're using Atomist for now.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.04 report

@cbeams and @emzy began logging @bisq-network GitHub organization notifications to github@lists.bisq.network. See https://github.com/bisq-network/lists/issues/5.

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
## 2018.05 report

 - @alfsbs created the https://github.com/bisq-network/payment-methods repository, and has migrated existing issues from bisq-desktop.
 - @cbeams created the @bisq-network/design-contributors team
 - @cbeams created the @bisq-network/docs-contributors team
 - 2 members were added to the @bisq-network org and 2 members left
 - @cbeams has begun drafting a `GitHub` doc at https://github.com/bisq-network/bisq-docs/pull/64

/cc bisq-network/compensation#74

**Comment by cbeams** [comment]
## 2018.05 report (cont)

I forgot to mention above that GitHub released a new, long-awaited feature this month, that allows users to see the revision history of issue descriptions and comments. As I wrote in [this tweet](https://twitter.com/bisq_network/status/1001795148559343616), this is important for the Bisq DAO, where certain kinds of issues, like those in https://github.com/bisq-network/proposals are quite important, and where changes to them can really matter.

See https://blog.github.com/changelog/2018-05-24-comment-edit-history/ for details.

**Comment by cbeams** [comment]
## 2018.07 report

 - I realized well after the fact of last month's voting that I forgot to leave a 2018.06 report. Oops.
 - Serviced requests to invite several members to the @bisq-network org
 - Monitored the #github channel, kept up on GitHub news and features

**BSQ requested:** `50`

/cc bisq-network/compensation#101

**Comment by cbeams** [comment]
## 2018.08 report

Nothing to report.

**BSQ Requested: `25`**

/cc bisq-network/compensation#114

**Comment by cbeams** [comment]
## 2018.09 report

Nothing to report.

**BSQ Requested: `25`**

/cc bisq-network/compensation#139

**Comment by cbeams** [comment]
## 2018.10 report

Nothing to report.

BSQ Requested: `25`

/cc bisq-network/compensation#160

**Comment by cbeams** [comment]
## 2018.11 report

Installed and authorized TestQuality GitHub integration at @devinbileck's request.

BSQ requested: `25`

/cc bisq-network/compensation#179

**Comment by cbeams** [comment]
Per https://github.com/bisq-network/roles/issues/1#issuecomment-444857417, I'll be away for the next ~2 months. I've made @ManfredKarrer the primary owner of this role in the meantime; please direct any GitHub administration requests to him.

**Comment by ManfredKarrer** [comment]
## 2019.01 report

@ripcurlx added a plugin (stale) for auto-closing old GH issues to reduce the number of un-maintained and outdated issues.

/cc bisq-network/compensation#205

**Comment by ManfredKarrer** [comment]
## 2019.02 report

Nothing to report.

/cc bisq-network/compensation#227

**Comment by ManfredKarrer** [comment]
## 2019.03 report

Nothing to report.

/cc bisq-network/compensation#252

**Comment by ripcurlx** [comment]
@ManfredKarrer I just recognized that this role was closed, but actually it is still required (I'm handling it right now as primary owner). I guess it was closed by mistake so I'll re-open it as GitHub admin.

**Comment by ripcurlx** [comment]
### Cycle 3 report
Nothing to report.

/cc bisq-network/compensation#269

**Comment by ripcurlx** [comment]
### Cycle 4 report
Nothing to report.

/cc bisq-network/compensation#269

**Comment by ripcurlx** [comment]
### Cycle 5 report
Nothing to report.

/cc bisq-network/compensation#269

**Comment by ripcurlx** [comment]
### Cycle 6 report
Added users to GitHub organisation whenever required and added new permission groups and users for mediation.

Based on discussions on [GitHub](https://github.com/bisq-network/proposals/issues/122) and Slack we decided to open incubator repositories. Added new incubator repositories and required permission groups:
- https://github.com/bisq-network/incubator-bisq-xmr-integration
- https://github.com/bisq-network/incubator-bisq-api

/cc bisq-network/compensation#369

**Comment by ripcurlx** [comment]
### Cycle 7 report
Added users to GitHub organisation and granted @wiz maintainer permission for the [markets repository](https://github.com/bisq-network/bisq-markets).

I've also applied more restrictions to our protected master branch. These are not new restrictions, I just enforce them now as close as possible on GitHub. See new settings in the screenshot below.

![Bildschirmfoto 2019-11-11 um 09 23 08](https://user-images.githubusercontent.com/170962/68572202-1cd2b380-0465-11ea-833a-2879d3bcaecc.png)


/cc bisq-network/compensation#401

**Comment by ripcurlx** [comment]
### Cycle 8 report
- Added https://github.com/bisq-network/bisq-android as a new repository for the efforts to develop a native Android client for Bisq (based on https://github.com/bisq-network/proposals/issues/139)
- Added Webhook for https://github.com/bisq-network/bisq-markets for Keybase integration maintained by @wiz 

/cc bisq-network/compensation#439

**Comment by ripcurlx** [comment]
### Cycle 9 report
- On @wiz's request I added @bodymindarts to the Bisq organization to be able to assign him to issues regarding the market server
- Added [codacy](https://www.codacy.com/) to the bisq-website repository to have automated code quality and security checks for PRs. Still a work in progress to configure it properly for our needs. Might be extended to the bisq repository as well if it proves itself useful.

/cc bisq-network/compensation#466

**Comment by ripcurlx** [comment]
### Cycle 10 report
- Added [codacy](https://www.codacy.com/) to the Bisq repository as well to have automated code quality and security checks for PRs. Still a work in progress to configure it properly for our needs.
- Cleaned up some stale teams as part of the new team structure.

/cc bisq-network/compensation#493

**Comment by cbeams** [comment]
## Cycle 10 report

This is my first report on this role in quite a while, as I've been away from the project for an extended period of time. I'll report here regularly once again from this point forward. There were many changes affected by me as GitHub Admin over the last cycle, and all are part of implementing the organizational changes detailed in the Q1 2020 Update call, video and slide deck. See bisq-network/admin#5. I will continue making a number of changes like these into the next cycle as we continue to iron out GitHub infrastructure changes to help meet our goals.

**Comment by ripcurlx** [comment]
## Cycle 11 report
Just minor team cleanups based on changes introduced in https://github.com/bisq-network/admin/issues/5.

/cc bisq-network/compensation#499

**Comment by cbeams** [comment]
## Cycle 12 report

I performed many GitHub admin functions over the last cycle, as I usually do, and they are too numerous to recall or enumerate here. In the future, I will make a point to reference this role issue whenever I complete a task that required GitHub admin action. These are usually things like creating a new GitHub team to support a new role or inviting a new contributor to join the bisq-network GitHub organization. Some items (like the latter) are just too minor to track.

I also submitted bisq-network/proposals#210 to post my bond for this role, which has been long overdue.

Note that as part of https://github.com/bisq-network/bisq/pull/4114, we will need to start paying for Git LFS storage data packs. I plan to pay for them out of pocket and request reimbursement via the DAO under this role. This has not been done yet, however.

/cc bisq-network/compensation#533

**Comment by ripcurlx** [comment]
## Cycle 12 report
Nothing to do this cycle from my side.

/cc bisq-network/compensation#542

**Comment by cbeams** [comment]
## Cycle 13 report

As I mentioned I would in my last report, I've [purchased a Git LFS data pack](https://github.com/bisq-network/bisq/pull/4114#issuecomment-629996984) for the bisq-network org at a cost of 60 USD per year. I'll be adding that to my compensation request this month at bisq-network/compensation#573

**Comment by cbeams** [comment]
## Cycle 14 report

This will be my last cycle report as GitHub Admin. I will work with @ripcurlx to determine when it's best for me to actually relinquish control of the role, but it will happen sometime between now and the time my bond expires roughly 80 days from the time of this writing.

Note that I will ask @ripcurlx to become the billing admin for the bisq-network GitHub org, and to be responsible for renewing our "data pack" used for Git LFS (https://github.com/bisq-network/bisq/pull/4114). I just paid for a year of this service last cycle, so it won't renew until ~11 months from now, and this is the only paid service we have with GitHub.

/cc bisq-network/compensation#600

**Comment by ripcurlx** [comment]
## Cycle 13 - 15 report
I took over the primary role from @cbeams and will continue to be the main contact for everything GitHub related.

Forked https://github.com/bisq-network/mempool into the Bisq organisation and fixed issues with Codacy not running anymore for the Bisq and the Bisq website repository.

/cc bisq-network/compensation#624

**Comment by cbeams** [comment]
## On the recent inability to assign issues to team members

### The problem 
An issue has cropped up several times recently in which I or other people have been unable to assign an issue to a given GitHub user ID. For example, see https://github.com/bisq-network/roles/issues/30#issuecomment-667965511. @wiz discovered that this was happening is because the would-be assignee did not have explicit read access to the repository in question.

### The cause
This was a non-issue until recently when I changed the default repository permissions for the bisq-network GitHub org. When creating the bisq-network/security repository, we wanted to have it be fully private and invite-only, such that only members of the @bisq-network/security team could see and interact with it. The only way to achieve this was to switch the default repository access for organization members from 'read' to 'none'. This worked well for the purpose, but had the side effect of making it impossible to assign issues to anyone that does not have explicit read access to the repository. This is a bummer.

### The 'solution' that doesn't really work
All organization members are (or should be) added to the @bisq-network/dao team via one or more specific sub-teams. This means that technically, we could assign read access to all repositories (except security) to the @bisq-network/dao team, and all members would once again be able to be assigned to any issue in any repository. Unfortunately, we have a lot of repositories, and GitHub's UI doesn't allow for doing this kind of thing in bulk, so, I've taken a 'best efforts' approach for now, see below.

### The current, imperfect solution

For now, I've just assigned the @bisq-network/dao team read access to the ops, proposals and roles repositories, as these are the ones that (IIRC) had issues lately. If any further repositories need the same treatment, just request that your friendly GitHub Admin to do so. It's probably only a small minority of our total set of repositories where this problem will manifest in practice, so this shouldn't be too much hassle over time.

### An idea how to eliminate this problem altogether
Thus far, the security repository hasn't seen much action (there's just one issue open there at present), and it seems like overkill to have to deal with everything I wrote above just to keep that repository private. One alternative would be to create a bisq-security repository outside of the bisq-network organization, and invite the members of the @bisq-network/security team to it individually. That localizes the 'hassle' to the team that needs and cares about the repository, instead of externalizing it on potentially everyone else in the org, as is the status quo.

**Comment by ripcurlx** [comment]
## Cycle 16 report
Nothing to report this cycle.

/cc bisq-network/compensation#652

**Comment by cbeams** [comment]
## Cycle 17 report

As noted above, I am no longer regularly reporting on this role, but I wanted to give an update here this time anyway. I thought that I had started the process of unlocking my bond for this role, but I realize now that I in fact have not. This is good thing, because it's become clear over time that in order to efficiently play the Roles Maintainer role (which I do), it is also very helpful to have GitHub Admin access. Without having this access, actually performing Roles Maintainer duties becomes quite bureaucratic, because it very often involves creating and updating GitHub Teams, making edits to existing role issue descriptions in the roles repository, and other changes that would require a GitHub Admin. For example, @wiz asked me to make several such changes during this cycle that would have been cumbersome if I didn't play both of these roles. So I plan to continue playing the GitHub Admin role indefinitely (as a secondary) in order to support my work as the Roles Maintainer.

/cc https://github.com/bisq-network/compensation/issues/668

**Comment by cbeams** [comment]
Just to be clear, it's this comment that I'm referring to when I say above that "I thought that I had started the process of unlocking my bond for this role":

@cbeams wrote at https://github.com/bisq-network/roles/issues/16#issuecomment-646964503:

> I will work with @ripcurlx to determine when it's best for me to actually relinquish control of the role, but it will happen sometime between now and the time my bond expires roughly 80 days from the time of this writing.

So while I had intended to begin the unlocking process at the time of that comment, I never actually did so. Again, this is all for the better; just making sure this change of course is explicit.

**Comment by ripcurlx** [comment]
## Cycle 17 report
I only removed the Slack GitHub app and denied Slack access to our repository. Besides that nothing to report.

/cc bisq-network/compensation#671

**Comment by ripcurlx** [comment]
## Cycle 18 report
I created a [Bisq issue maintainers](https://github.com/orgs/bisq-network/teams/bisq-issues-maintainers) team adding @cd2357 as the only member right now. I haven't proposed a specific role for it yet, as I wanted to see how it turns out within the last cycle. I included Git LFS objects in the source archives for Arch Linux, so it behaves similar as it had before the Git LFS switch. 

/cc bisq-network/compensation#704

**Comment by ripcurlx** [comment]
## Cycle 19 report

Nothing to report this cycle.

/cc bisq-network/compensation#723

**Comment by ripcurlx** [comment]
## Cycle 20 report

Nothing to report this cycle.

/cc bisq-network/compensation#746

**Comment by ripcurlx** [comment]
## Cycle 21 report

Nothing to report this cycle.

/cc bisq-network/compensation#758

**Comment by cbeams** [comment]
Update: At @pazza83's request, I've just installed the "Polls" GitHub app (https://github.com/evenchange4/gh-polls-bot) in the bisq-network/bisq repository.

**Comment by cbeams** [comment]
> Update: At @pazza83's request, I've just installed the "Polls" GitHub app (https://github.com/evenchange4/gh-polls-bot) in the bisq-network/bisq repository.

CORRECTION: It was at @huey735's request, not @pazza83. In any case, the polls app has been installed. @huey735, perhaps you could comment here on what you plan to use it for, just so folks know what to expect. Thanks.

**Comment by huey735** [comment]
So that for discussions we could have more diverse voting mechanism than upvote/downvote.

**Comment by ripcurlx** [comment]
## Cycle 22 report

Blocked one user from the organization because of repeated spam messages in issues and PRs.

/cc bisq-network/compensation#795

**Comment by ripcurlx** [comment]
## Cycle 23 report

Added following new repositories to the bisq-network organization:
- https://github.com/bisq-network/bisq-relay
- https://github.com/bisq-network/bisqremote
- https://github.com/bisq-network/bisqremote_Android
- https://github.com/bisq-network/bisqremote_iOS

I also created a new mobile-maintainer team and added @devinbileck as maintainer.

/cc bisq-network/compensation#813

**Comment by ripcurlx** [comment]
## Cycle 24 report

Nothing to report this cycle.

/cc bisq-network/compensation#846

**Comment by ripcurlx** [comment]
## Cycle 25 report

I've added a new repository for Misq (https://github.com/bisq-network/misq) with a basic repository setup and created the necessary team adding @ghubstan and @jmacxx as maintainers.

/cc bisq-network/compensation#860

**Comment by ripcurlx** [comment]
## Cycle 26 report

I've added  @BtcContributor as new support team member.

/cc bisq-network/compensation#882

**Comment by ripcurlx** [comment]
## Cycle 27 report

Blocked @Dpalazue from the organization because of SPAM.

/cc bisq-network/compensation#904

**Comment by ripcurlx** [comment]
## Cycle 28 report

Nothing to report.

/cc bisq-network/compensation#904

**Comment by ripcurlx** [comment]
## Cycle 29 report

Transferred https://github.com/bisq-network/bisq-client to the bisq-network and granted maintainer permissions to @devinbileck .

/cc bisq-network/compensation#931

**Comment by ripcurlx** [comment]
## Cycle 30 report

Forked https://github.com/JesusMcCloud/jtorctl to https://github.com/bisq-network/jtorctl and granted maintainer permissions to @cd2357.

/cc bisq-network/compensation#939

**Comment by ripcurlx** [comment]
## Cycle 31 report

Added @chimp1984 and @stejbac as maintainer to https://github.com/bisq-network/misq and removed review requirement for PRs during the Bisq 2.0 rapid prototyping phase.

/cc bisq-network/compensation#966

**Comment by ripcurlx** [comment]
## Cycle 32 report

- Removed loitering Travis CI integration (unused) and had to re-enable Codacy integration because of [this change](https://github.blog/2021-09-01-improving-git-protocol-security-github/) by GitHub.
- Renamed Misq repository to Bisq2
- Had to increase the Git LFS account plan to 1,800 GB to match our consumed bandwidth (1,400 GB consumed already) > 180 USD/year ATM.

/cc bisq-network/compensation#984

**Comment by ripcurlx** [comment]
## Cycle 33 report

- Had to increase the Git LFS account plan again to 2,400 GB to match our consumed bandwidth (1,800 GB consumed already) > 240 USD/year ATM.

/cc bisq-network/compensation#1016

**Comment by ripcurlx** [comment]
## Cycle 34 report

- Had to increase the Git LFS account plan again,again to 3,000 GB to match our consumed bandwidth (2,600 GB consumed already) > 300 USD/year ATM. 
- Forked https://github.com/bisq-network/slate for Bisq API documentation
- Gave @pazza83 permissions to manage project repository

/cc bisq-network/compensation#1041

**Comment by ripcurlx** [comment]
## Cycle 35 report

- Had to increase the Git LFS account plan again,again,again to 3,600 GB to match our consumed bandwidth (3,118 GB consumed already) > 360 USD/year ATM. Our data will reset in 21 days, so hopefully that will be our yearly plan from now on.
- Gave @UX-P  permissions to manage the design repository
- Added @alvasw and @alkum as Triage maintainer for the bisq2 repository

/cc bisq-network/compensation#1060

**Comment by ripcurlx** [comment]
## Cycle 36 report

- Luckily this time no new data package necessary as we started a new accounting year. So €360 were payed for GitHub.
- Gave @devinbileck temporary admin permissions for https://github.com/bisq-network/bisqremote_iOS and https://github.com/bisq-network/bisqremote_Android
- Added https://github.com/bisq-network/bisq-api-reference repository
- Added @ghubstan as maintainer to https://github.com/bisq-network/bisq-api-reference 

/cc bisq-network/compensation#1088

**Comment by ripcurlx** [comment]
## Cycle 37 report

- Forked https://github.com/bisq-network/jsocks and https://github.com/bisq-network/java-opentimestamps on request from @chimp1984 

/cc bisq-network/compensation#1088

**Comment by ripcurlx** [comment]
## Cycle 38 report

- Created https://github.com/bisq-network/bisq-pricenode based on request from @ghubstan 
- Created https://github.com/bisq-network/bisq-monitor based on request from @ghubstan 
- Created https://github.com/bisq-network/bisq-gradle based on request from @ghubstan 
- Created https://github.com/bisq-network/bisq-inventory based on request from @ghubstan 

/cc bisq-network/compensation#1154

**Comment by ripcurlx** [comment]
## Cycle 39 report

- Created https://github.com/bisq-network/bisq-daonode based on request from @ghubstan 
- Created https://github.com/bisq-network/bisq-relay based on request from @ghubstan 

/cc bisq-network/compensation#1154

**Comment by ripcurlx** [comment]
## Cycle 40 report

Nothing to report.

/cc bisq-network/compensation#1154

**Comment by ripcurlx** [comment]
## Cycle 41 report

Added @gabernard to the Bisq organization making him GitHub Admin after https://github.com/bisq-network/proposals/issues/382 was approved and Bond was locked successfully.

/cc bisq-network/compensation#1184

**Comment by cbeams** [comment]
I've assigned @gabernard to this role, and I've also removed myself from it. I've unlocked my associated bond, and have asked @ripcurlx to remove my Owner role from the GitHub org. This change has been planned for a while, and now's the time to do it with @gabernard taking it on. Welcome @gabernard!

**Comment by ripcurlx** [comment]
## Cycle 42 report

Added @alejandrogarcia83 to the Bisq organization making him Bisq maintainer after https://github.com/bisq-network/proposals/issues/394 was approved and Bond was locked successfully.
Removed @cbeams as Github Owner. I've also started to unlock my bond for GitHub admin and will request @gabernard  to remove me from this role as soon as hand over is done.

/cc bisq-network/compensation#1197

**Comment by ripcurlx** [comment]
## Cycle 43 report

Added @w0000000t to the Bisq organization.

/cc bisq-network/compensation#1237

**Comment by ripcurlx** [comment]
## Cycle 44 report

Nothing to report. As it seems that @gabernard can take everything over from now on, I'll request him to remove my GitHub Admin account as GitHub owner.

/cc bisq-network/compensation#1237

**Comment by gabernard** [comment]
## Cycle 41 report
Nothing to report.

/cc bisq-network/compensation#1274

**Comment by gabernard** [comment]
## Cycle 42 report
Nothing to report.

/cc bisq-network/compensation#1274

**Comment by gabernard** [comment]
## Cycle 43 report
- Added @alejandrogarcia83 as maintainer to https://github.com/bisq-network/bisq-website
- Added @alejandrogarcia83 as maintainer to https://github.com/bisq-network/bitcoinj

/cc bisq-network/compensation#1274

**Comment by gabernard** [comment]
## Cycle 44 report
Removed @ripcurlx as Github Owner

/cc bisq-network/compensation#1274

**Comment by gabernard** [comment]
## Cycle 45 report
- Added @alejandrogarcia83 as maintainer to https://github.com/bisq-network/netlayer

/cc bisq-network/compensation#1274

**Comment by gabernard** [comment]
## Cycle 46 report
Added https://github.com/bisq-network/bisq-api-reference repository based on request from @salokiam

/cc bisq-network/compensation#1274

**Comment by gabernard** [comment]
## Cycle 46 report
- Added https://github.com/bisq-network/bisq2-web-ui repository based on request from @salokiam
- Added @salokiam as maintainer to https://github.com/bisq-network/bisq2-web-ui

/cc bisq-network/compensation#1274
