### ISSUE TITLE
Twitter Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#21]
This role is responsible for managing all aspects of the https://twitter.com/bisq_network Twitter handle.

---
Docs: https://github.com/bisq-network/roles/blob/master/twitter-admin.adoc (should be reworked per instructions in [Roles](https://docs.bisq.network/roles.html) doc.
Team: @bisq-network/twitter-admins 
Primary owner: @m52go

**Comment by cbeams** [comment]
## 2017.11 update

Upstats all around during November, as we began to get much more active on Twitter. All the buzz around the Baltic Honeybadger conference was certainly a help here, but was not the only factor. I'm particularly happy to see the 430 new followers. That's a ~8% increase (from ~5400->~5800) in a single month, and more than 10 new followers per day on average. A pretty good indicator of interest, I think.

The screenshot below is taken from @bisq_network's Twitter Analytics summary. As the owner of the Twitter Operator role, I'll post these kind of updates as comments here on this issue every month going forward.

![image](https://user-images.githubusercontent.com/301810/33479057-eb794d02-d68b-11e7-97a7-3e2b92764356.png)

**Comment by cbeams** [comment]
## 2017.12 report

As I tweeted at https://twitter.com/bisq_network/status/947011519082041345, we had a big surge in followers this month, around 25% when the whole month of December was taken into account. This surely had a lot to do with our appearance on WCN's Bitcoin News show, but I think is also attributable to momentum in general around Twitter. We've had a pretty consistent presence there over the last few months now, and it looks like more and more folks are finding it valuable to follow us.

Twitter takes up a good chunk of my time, but I find it worth the effort. I believe it's currently our best channel for outreach and connecting to our future contributor base, and can be really powerful as we return to volume growth efforts in the weeks and months to come. I plan to keep going like I have been on this front, but of course feedback is welcome.

![image](https://user-images.githubusercontent.com/301810/34566352-7eb1f3a2-f15e-11e7-8b19-782c521ba9a7.png)

Note that the above does not take into account the even bigger surge that came a couple days later, spurred on by Trace Mayer's shout out about Bisq. But I'll cover that in next month's `2018.01` update 😎

/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
## 2018.01 report

This was, I believe, our best month ever in terms of Twitter engagement. Our follower count grew by grew by 27% again this month, adding 2,127 new followers in total to hit **10,000 followers** right on Jan 31st. Wow!

Upstats across the board otherwise, too.

![image](https://user-images.githubusercontent.com/301810/35655882-85ddc1aa-06f4-11e8-910d-f0d4aaf5f2df.png)

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

Twitter, along with YouTube only becomes a more important resource for us to get the word out about Bisq.

 - Followers grew by ~800 this month
 - Note the doubling of Tweet impressions as well

![image](https://user-images.githubusercontent.com/301810/36822263-6bb71d6c-1cf7-11e8-82f0-8a160cff65e3.png)

This week I learned a couple fun things:

 - @bisq_network is one of 182 members in (the newly public) [@naval/crypto](https://twitter.com/naval/lists/crypto) list
 - @bisq_network is one of 16 members of [@eiane/ProfilePicsThatILike](https://twitter.com/eiaine/lists/profilepicsthatilike/members):

![image](https://user-images.githubusercontent.com/301810/36822459-6b7329ee-1cf8-11e8-962d-5708f17c1819.png)

**Comment by cbeams** [comment]
## 2018.03 report

Observations: We tweeted ~half as many times this month, had half as many profile visits, half as many new followers, half as many mentions as last month, and our overall number of tweet impressions grew about 10% from 1.11M to 1.22M. I can't draw any conclusions from that data, but it's interesting to see how things play out.

In general, I'm not following any strategy with Twitter other than tweeting things I'm reasonably certain our audience will find valuable. So far, this has meant that some months, we have a lot of tweets and resulting activity, and other months we have relatively little. It all seems to be working well enough, but feedback is welcome.

It's also worth noting that I've been trying to delegate tweeting a bit more. @ripcurlx and @flix1 have been putting together tweets for growth calls, liquidity weeks, and I simply retweet them from @bisq_network. This has always been the idea, but we haven't done a whole lot of it in practice. I'm glad to start ramping that up a bit more now, as it doesn't scale for me to craft every tweet.

One note, @flix1, you don't need to @mention `@cbeams` or `@bisq_network` in your tweets that you want me to retweet. You're one of just a handful of accounts that `@bisq_network` follows, so I always see your tweets, and I always consider retweeting anything suitable. If you want to make sure I retweet something, though, please DM me via Twitter about it, or @mention me in the #twitter Slack channel about it.

![image](https://user-images.githubusercontent.com/301810/38295712-2591c0a4-37ef-11e8-917f-ef057854a3eb.png)

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

I'm not sure whether it's obvious to others in the same way it is to me, watching the @bisq_network's handle as closely as I do, but Twitter sentiment about Bisq is really very good. We get positive mentions most every day, and sometimes many times per day, and have vanishingly few negative mentions.

Nothing else specific to report this month, here are the analytics as usual. 900+ new followers this month is a nice stat, and our reach (tweet impressions) continues to grow, just as it has every month since we've started recording this stuff.

![image](https://user-images.githubusercontent.com/301810/39591446-108ecc20-4f04-11e8-9d78-20e22cd43994.png)

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
## 2018.05 report

Accounts impersonating Bisq with ETH giveaway scams etc have become a complete pain in the ass now. I've offered a bounty to anyone who puts together software to automatically report them, but no takers yet.

Otherwise, everything is going well. Nothing particularly remarkable happened this month, but outside of the aforementioned scammers, Bitcoin Twitter is a lovely place to be. Bisq gets @mentioned frequently in relevant and interesting conversations, and in general awareness continues to grow, sentiment continues to be positive, etc.

![image](https://user-images.githubusercontent.com/301810/40841542-1cd6d0aa-65ab-11e8-97b7-601d748d7d6d.png)

/cc bisq-network/compensation#74

**Comment by cbeams** [comment]
Note that we had almost identical numbers this month as compared to last for tweets sent (55), and impressions (1.29M) and profile visits (14.3K), but our number of mentions increased dramatically from 592 to 926. I would bet that almost the entire difference can be attributed to the above mentioned scammers, whose MO is always to reply to one of our legit tweets with one of their bogus tweets. All of these replies count as mentions, and there were a ton of them this month.

**Comment by cbeams** [comment]
## 2018.06 report

I tweeted a little less frequently this month, but generally things are looking healthy anyway. 840 new followers is a pretty nice stat, especially considering the reduced activity.

From https://analytics.twitter.com/user/bisq_network/home:

![image](https://user-images.githubusercontent.com/301810/42127473-ae06670c-7c99-11e8-8451-50e518653e59.png)

/cc bisq-network/compensation#89

**Comment by cbeams** [comment]
## 2018.07 report

Many fewer tweets than usual this month (just 15), and downstats ensued as a result. The reduced activity was largely health-related for me, but I did still keep up on Twitter, responding to people, etc. Just did less original tweeting of my own.

![image](https://user-images.githubusercontent.com/301810/43469295-21dab372-94e6-11e8-9f10-69f447370599.png)

**BSQ requested:** `1500`

/cc bisq-network/compensation#101

**Comment by cbeams** [comment]
## 2018.08 report

Due to health issues I did the bare minimum around Twitter this month, monitoring our account, tweeting and retweeting release announcements and weekly growth calls, etc. Only nine tweets in total, and predictable downstats as a result.

![image](https://user-images.githubusercontent.com/301810/44919049-ccc67000-ad3c-11e8-9ce1-658c7922968f.png)

**BSQ Requested: `300`**

/cc bisq-network/compensation#114

**Comment by cbeams** [comment]
## 2018.09 report

This month's performance was than the last couple, due to my being able to spend more time with Twitter. With that said, I was only operating at perhaps 2/3rds my usual engagement, e.g. number of tweets, responses, etc. 

In the conversation at https://github.com/bisq-network/compensation/issues/115#issuecomment-422035138, @ManfredKarrer suggested that we go with a 3000K / mo budget for Twitter, and the rough estimate that I was operating a 2/3rds my usual pace and producing commensurate results is why I've requesting 2000 vs 3000 below.

![image](https://user-images.githubusercontent.com/301810/46259218-b98ef780-c4d6-11e8-8369-2b14528b173b.png)

**BSQ Requested: `2000`**

/cc bisq-network/compensation#139

**Comment by cbeams** [comment]
## 2018.10 report

![image](https://user-images.githubusercontent.com/301810/47819363-8ef4c080-dd5a-11e8-9fb6-2f4037e4291c.png)

BSQ Requested: `1800`

/cc bisq-network/compensation#160

**Comment by cbeams** [comment]
## 2018.11 report

Manfred and I agreed that I would lay off tweeting this month. We've been seeing massive volume increases over the last months, and until the DAO is launched, it's probably wise to keep a somewhat lower profile for the project. This doesn't mean we won't be tweeting at all anymore, but will rather focus on highlighting our educational efforts (cc @m52go) as opposed to tweeting every time we see a new ATH, etc. And our Twitter stats this month reflect this change:

![image](https://user-images.githubusercontent.com/301810/49315438-ffc00180-f4ed-11e8-950a-fcda2d820212.png)

BSQ requested: `250`

/cc bisq-network/compensation#179

**Comment by cbeams** [comment]
Per https://github.com/bisq-network/roles/issues/1#issuecomment-444857417, I'll be away for the next ~2 months. @m52go will take over this role in my absence, and we're in the process of transitioning everything now.

**Comment by m52go** [comment]
## 2019.01 Report

Pretty good month for Twitter. We had 1 especially good tweet early in the month that might have been the most successful tweet yet (by engagement). I also know it led to at least [one article in Cointelegraph](https://cointelegraph.com/news/controversial-content-creators-shift-to-crypto-after-censorship).

Also picked up almost 600 new followers.

![screencapture-analytics-twitter-user-bisq_network-home-2019-02-01-00_24_51](https://user-images.githubusercontent.com/735155/52104296-dee05f00-25b7-11e9-8a65-534b25b8ed4a.png)

/cc https://github.com/bisq-network/compensation/issues/219

**Comment by m52go** [comment]
## 2019.02 Report

It was a rather meager month on Twitter. Didn't tweet as much, as it seemed I kept hitting the same tropes of privacy, freedom, etc. Started to feel boring, which might be the worst possible outcome for a social channel. So tweet output was lower. I'm working on an expanded variety of topics and insights to make March go better.

We got 180 new followers. I docked my requested compensation a bit to reflect the reduced activity.

![fireshot capture 001 - twitter analytics account overview for bisq_network - analytics twitter com](https://user-images.githubusercontent.com/735155/53602673-7916d100-3b7d-11e9-941b-1e9ac717da74.png)

/cc https://github.com/bisq-network/compensation/issues/234

**Comment by m52go** [comment]
## 2019.03 Report

Great month on Twitter. Pivotal, actually. The numbers are nice, but the real win was in what I sense was a shift in the general mindset about the Bisq DAO.

Before this month, trolls and low engagement on DAO-related tweets made me hesitant to tweet about the DAO at all. It was mainly the trolls that stopped me, as any sort of conflict ran a high chance of exploding and destroying the Bisq "brand" and I didn't want to risk that. Mobs are impossible to reason with, and Bitcoin Twitter is often very tribal.

In the past month, things have changed. Not only have our own DAO tweets done much better, but there's been strong support from the community any time trolls did try to troll. 

Saw the same dynamic [on Reddit](https://www.reddit.com/r/Bitcoin/comments/ayfahn/the_bisq_dao_for_bitcoin_maximalists/) as well, and [more than once](https://www.reddit.com/r/Bitcoin/comments/b5c74j/bisq_dao_testers_are_needed/). It's been _fantastic_.

We gained 396 new followers.

![screencapture-analytics-twitter-user-bisq_network-home-2019-03-31-12_20_43](https://user-images.githubusercontent.com/735155/55292075-52ce9600-53b4-11e9-9887-af196fe4ab8b.png)

/cc https://github.com/bisq-network/compensation/issues/257

**Comment by m52go** [comment]
## 2019.04 Report

Ho-hum month on Twitter. Nothing notable to report.

We gained 185 new followers.

![Screenshot from 2019-05-03 10-54-13](https://user-images.githubusercontent.com/735155/57410073-cc2d8580-71b7-11e9-982b-7bc3c0eb7863.png)

/cc https://github.com/bisq-network/compensation/issues/277

**Comment by m52go** [comment]
## 2019.05 Report

Nothing notable to report. We gained 166 new followers.

![Screenshot from 2019-06-07 15-58-19](https://user-images.githubusercontent.com/735155/59130339-29defa00-893d-11e9-8507-d804b10d4fc7.png)

/cc https://github.com/bisq-network/compensation/issues/294

**Comment by m52go** [comment]
## 2019.06 Report

Nothing notable to report for Twitter this month. We gained 362 new followers.

Even though we've been hitting new volume records, I've been hesitant to promote them since fiat trading is still hobbled.

![Screenshot from 2019-07-05 10-17-38](https://user-images.githubusercontent.com/735155/60737004-1c5e6500-9f27-11e9-9a5b-bf18af911b7c.png)

/cc https://github.com/bisq-network/compensation/issues/304

**Comment by m52go** [comment]
## 2019.07 Report

Nothing notable to report for Twitter this month. We gained 340 new followers.

![Screenshot from 2019-08-01 09-19-47](https://user-images.githubusercontent.com/735155/62594126-5d8bc100-b8a7-11e9-9130-4649480cf79d.png)

/cc https://github.com/bisq-network/compensation/issues/323

**Comment by m52go** [comment]
## 2019.08 Report

Nothing notable to report for Twitter this month. We gained 419 new followers.

![Screenshot from 2019-09-02 12-39-14](https://user-images.githubusercontent.com/735155/64548719-363c6f80-d2fd-11e9-8f93-39c73204e30f.png)

/cc https://github.com/bisq-network/compensation/issues/361

**Comment by m52go** [comment]
## 2019.09 Report

Nothing notable to report for Twitter this month. We gained 373 new followers.

![Screenshot from 2019-10-02 09-21-36](https://user-images.githubusercontent.com/735155/66489332-6ce0e380-ea7d-11e9-82ab-722638628ae6.png)

/cc https://github.com/bisq-network/compensation/issues/372

**Comment by m52go** [comment]
## 2019.10 Report

Nothing notable to report for Twitter this month. We gained 343 new followers.

![Screenshot from 2019-11-01 14-40-29](https://user-images.githubusercontent.com/735155/68683432-c634aa80-0534-11ea-95f7-624363393d2d.png)

/cc https://github.com/bisq-network/compensation/issues/408

**Comment by m52go** [comment]
## 2019.11 Report

Nothing notable to report for Twitter this month. We gained 287 new followers.

![Screenshot from 2019-12-02 21-32-33](https://user-images.githubusercontent.com/735155/70852456-80ebfb80-1e99-11ea-899a-3a647a72662f.png)

/cc https://github.com/bisq-network/compensation/issues/442

**Comment by m52go** [comment]
## 2019.12 Report

Nothing notable to report for Twitter this month. We gained 340 new followers.

![Screenshot from 2020-01-08 12-37-18](https://user-images.githubusercontent.com/735155/72420467-af017b80-3776-11ea-94aa-a940a9bdd132.png)

/cc https://github.com/bisq-network/compensation/issues/471

**Comment by m52go** [comment]
## 2020.01 Report

Nothing notable to report for Twitter this month. We gained 275 new followers.

I asked for relatively less this month because I tended to be more reactive than proactive than usual, and compensation for this role will be coming down in Cycle 11 anyway as new roles are established for others to follow and manage the various social channels important for Bisq.

![Screenshot from 2020-02-15 08-48-32](https://user-images.githubusercontent.com/735155/74589077-19b60900-4ffa-11ea-93eb-673bbaf4934d.png)

/cc https://github.com/bisq-network/compensation/issues/497

**Comment by m52go** [comment]
## Cycle 11 Report

Nothing notable to report for Twitter in February. We gained 406 new followers.

Twitter has been the primary means for getting the word out about March growth initiatives. I launched a handful of tweetstorms summarizing 2020 initiatives, why-bisq, and onboarding items (mostly in March, so they aren't reflected in analytics below).

I've included reports for February and March, since a lot of notable activity for Cycle 11 occurred in March. **Note that tweets, tweet impressions, and profile visits for March are already comparable to those of the whole month of February.**

### February

![Screenshot from 2020-03-16 10-10-01](https://user-images.githubusercontent.com/735155/76766631-3330a900-6790-11ea-8671-95bf343f2baf.png)

### March

![Screenshot from 2020-03-16 16-49-50](https://user-images.githubusercontent.com/735155/76798574-c0432480-67c7-11ea-8d93-8ad6734eb04a.png)

/cc https://github.com/bisq-network/compensation/issues/513

**Comment by m52go** [comment]
## Cycle 12 Report

The bisq_network Twitter account gained 258 new followers in March, a rather low increase considering the high degree of activity the account saw. 

I often monitor account activity in real-time, and it seems that the account is being "throttled" or otherwise hampered by some invisible algorithms or filters. I have no hard evidence for this, but it does make me wonder if we should have some kind of a backup plan in mind in case this account loses its power.

### March

![Screenshot from 2020-04-17 17-02-41](https://user-images.githubusercontent.com/735155/79614125-6481f900-80ef-11ea-9752-1dd5fadec90a.png)

/cc https://github.com/bisq-network/compensation/issues/540

**Comment by m52go** [comment]
## Cycle 13 Report

The bisq_network Twitter account gained 185 new followers in April—not the best performance but news and developments during the month weren't the best either.

![Screenshot from 2020-05-17 22-44-50](https://user-images.githubusercontent.com/735155/82169752-042ed480-98b2-11ea-8e09-614521fd6229.png)

/cc https://github.com/bisq-network/compensation/issues/572

**Comment by m52go** [comment]
## Cycle 14 Report

The bisq_network Twitter account gained 361 new followers in May. Only sent 73 tweets, about 20% fewer than normal, but a number of them outperformed.

![Screenshot from 2020-06-22 07-50-14](https://user-images.githubusercontent.com/735155/85284368-9c564580-b47e-11ea-9133-a466e3e327be.png)

/cc https://github.com/bisq-network/compensation/issues/604

**Comment by m52go** [comment]
## Cycle 15 Report

The bisq_network Twitter account gained 237 new followers in June. Didn't send very many tweets due to being away for (mostly) unexpected reasons, and requested compensation reflects this.

![Screenshot from 2020-07-23 15-25-08](https://user-images.githubusercontent.com/735155/88359438-1883c780-cd62-11ea-863e-538f70263758.png)

/cc https://github.com/bisq-network/compensation/issues/631

**Comment by m52go** [comment]
## Cycle 16 Report

The bisq_network Twitter account gained 114 new followers in July. Apparently I sent fewer tweets than I thought, for no particular reason. I'll adjust compensation accordingly.

![Screenshot from 2020-08-21 11-25-42](https://user-images.githubusercontent.com/735155/90907760-e7c79a00-e3c2-11ea-9efa-9a9363838e77.png)

/cc https://github.com/bisq-network/compensation/issues/649

**Comment by m52go** [comment]
## Cycle 17 Report

The bisq_network Twitter account gained 321 new followers in August. Nothing notable to report.

![Screenshot from 2020-09-22 20-00-35](https://user-images.githubusercontent.com/735155/93949570-7c117d80-fd30-11ea-89f1-3893ba6867d4.png)

/cc https://github.com/bisq-network/compensation/issues/676

**Comment by m52go** [comment]
## Cycle 18 Report

The bisq_network Twitter account gained 224 new followers in September.

![Screenshot from 2020-10-23 21-00-12](https://user-images.githubusercontent.com/735155/97064285-51ffe500-1594-11eb-9638-c7301e29c19b.png)

/cc https://github.com/bisq-network/compensation/issues/702

**Comment by m52go** [comment]
## Cycle 19 Report

The bisq_network Twitter account gained 364 new followers in October and 565 in November. It seems intensifying gloomy headlines about regulation fueled interest in Bisq in November, leading to more of a pick-up in followers than usual.

### October

![Screenshot from 2020-12-02 03-00-28](https://user-images.githubusercontent.com/735155/100845072-92e0f880-3474-11eb-8491-7f89e4876dfa.png)

### November

![Screenshot from 2020-12-02 03-00-42](https://user-images.githubusercontent.com/735155/100845028-85c40980-3474-11eb-87ef-b93e28bee48b.png)

**Comment by m52go** [comment]
## Cycle 20 Report

The bisq_network Twitter account gained 1,231 new followers in December. That's a lot more than usual, and seemed to be drive by the 60%+ increase in impressions and mentions that took place as a result of recent news.

BTCSessions' video on Bisq, as well as a couple of key users' testimonies, helped ignite interest.

### December

![Screenshot from 2021-01-01 10-56-28](https://user-images.githubusercontent.com/735155/103441986-f0ba5900-4c49-11eb-9ddb-d304e79132cc.png)

**Comment by m52go** [comment]
## Cycle 21 Report

The bisq_network Twitter account gained 1,533 new followers in January. Activity started the month strong but lately engagement has been rather lackluster.

![Screenshot from 2021-03-07 23-25-13](https://user-images.githubusercontent.com/735155/110274302-6930f380-7fc6-11eb-83bc-65ee503a7b11.png)

/cc https://github.com/bisq-network/compensation/issues/775

**Comment by m52go** [comment]
## Cycle 22 Report

The bisq_network Twitter account gained 1,902 followers in February, which is crazy-high for any month, let alone a short month like February. One of those new followers was a Twitter founder known as `@jack`. There was lots of buzz in general, undoubtedly helped by wiz's appearance on Citadel Dispatch.

![Screenshot from 2021-03-07 23-24-35](https://user-images.githubusercontent.com/735155/110274328-79e16980-7fc6-11eb-9991-0a27ec62deac.png)

**Comment by m52go** [comment]
## Cycle 23 Report

The bisq_network Twitter account gained 820 followers in March. Not much to report.

![march-twitter](https://user-images.githubusercontent.com/735155/117592857-327f7280-b108-11eb-99db-b6ec5dde1c7b.png)

**Comment by m52go** [comment]
## Cycle 24 Report

The bisq_network Twitter account gained 1,021 followers in April. Got a little caught up in drama set off by the Samourai guys that ended up appearing as animosity toward Haveno...not proud of it.

![april-twitter](https://user-images.githubusercontent.com/735155/117765036-61c2dc00-b1fb-11eb-88e1-26aa24cabdaa.png)

**Comment by m52go** [comment]
## Cycle 25 Report

The bisq_network Twitter account gained 599 followers in May. There was some buzz about L-BTC as a base currency on Bisq, as well as some excitement around the INR market.

![Screenshot from 2021-08-06 14-01-16](https://user-images.githubusercontent.com/735155/128561213-7d9a9c78-e09f-4fae-9e8a-c12a883da7a3.png)

**Comment by m52go** [comment]
## Cycle 26 Report

The bisq_network Twitter account gained 558 followers in June.

![Screenshot from 2021-08-06 16-04-07](https://user-images.githubusercontent.com/735155/128565579-df6a649f-0b44-440c-b7db-4bd00cb14aa4.png)

**Comment by m52go** [comment]
## Cycle 27 Report

The bisq_network Twitter account gained 826 followers in July.

![Screenshot from 2021-11-19 17-21-06](https://user-images.githubusercontent.com/735155/142698947-bc075db9-ea96-4257-a1cd-4aae4205e9cb.png)

**Comment by m52go** [comment]
## Cycle 28 Report

The bisq_network Twitter account gained 342 followers in August.

![Screenshot from 2021-11-19 17-21-28](https://user-images.githubusercontent.com/735155/142699030-9021bed2-538f-4561-b8e0-c488768d1a0f.png)

**Comment by m52go** [comment]
## Cycle 29 Report

The bisq_network Twitter account gained 1,911 followers in September. Not sure what exactly resulted in the follower spike...there were a handful of notable tweets and a nice release (v1.7.4).

![Screenshot from 2021-11-19 17-21-44](https://user-images.githubusercontent.com/735155/142699097-8aa6b800-8730-4c46-b447-7a64994b0bbe.png)

**Comment by m52go** [comment]
## Cycle 30 Report

The bisq_network Twitter account gained 964 followers in October.

![Screenshot from 2021-11-19 17-21-54](https://user-images.githubusercontent.com/735155/142699140-4c87f391-5f8b-4da2-b063-100ddc3094fa.png)

**Comment by w0000000t** [comment]
No access to main bisq stats with my privileges, but I've been replying to mentions of other accounts, and sent some posts, thinking about coming up with interesting and short content each day.
My most successful tweets:
https://twitter.com/bisq_network/status/1529465524878548992
https://twitter.com/bisq_network/status/1528659940646260739
https://twitter.com/bisq_network/status/1528463306528370688

**Comment by w0000000t** [comment]
Managed twitter account until June 6th.
Most successful, and maybe controversial, tweet:
https://twitter.com/bisq_network/status/1532059719317454848

**Comment by w0000000t** [comment]
> Managed twitter account until June 6th.

Officially making it known (silly me to think it was obvious from the content of the previous post) that I in fact do *not* have control of the twitter account anymore.  Since 6th of June, as per previous report.
I feel this is necessary due to current drama ongoing about some late (re)tweets on the Bisq account, and me being addressed for it on Matrix.
