### ISSUE TITLE
Freenode IRC Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#22]
This role is responsible for administering the `#bisq` and (legacy) `#bitsquare` Freenode IRC channels, as well as the `#chat-bridge` bot / channel in Slack. Owners of this role have `op` (operator) status in Freenode IRC terminology.

---

Docs: none, other than the above
Team: @bisq-network/irc-admins 
Primary owner: @mrosseel

**Comment by cbeams** [comment]
I've assigned @mrosseel, @ManfredKarrer and myself to this role, as we three in fact have op rights in #bisq and #bitsquare.

@mrosseel is the only one actively managing this, though, and we should consider what we want to do going forward with these rights. It would be better to get the keys out of my and Manfred's hands, and into another new and active operator so we have at least two who are responsible.

**Comment by cbeams** [comment]
## 2017.12 report

Like @ManfredKarrer, I am only _technically_ a Freenode Admin. It's really @mrosseel that's doing the work here, showing up every day, answering questions etc. @mrosseel, could you start providing monthly updates here from your side? It can be a simple one-liner if there's nothing to report.

/cc bisq-network/compensation#26

**Comment by mrosseel** [comment]
## 2017.12 report

Nothing special to report, apart from the fact that the topic has been indicating the pending move from #bitsquare to #bisq for some time now, so it could be done any time now. Will be postponed till the bridge discussion is concluded.

**Comment by cbeams** [comment]
I think it's worth mentioning above, @mrosseel, something about the work you do moderating / answering questions in IRC as well. I don't track this closely, but when I do look at `#chat-bridge` or get matrix updates by email, I very frequently see you (tarcus) fielding Q&A. Feel free to include that sort of thing in your updates, e.g. some commentary on or mention of the relative time and effort you're putting into keeping these channels well-served. It's certainly valuable to the network that you do so.

**Comment by mrosseel** [comment]
## 2018.01 report

Not many discussions on IRC, not much effort was needed to keep up this month.

**Comment by cbeams** [comment]
## 2018.01 report

Thanks, @mrosseel. I have nothing to report, as I had no involvement with IRC this month. Going forward, I'll let you do these updates. I'm happy to keep my op status in Freenode, but will play a passive role from now on and won't do further reports here unless something changes.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

Not a 'monthly report' per se, but I just noticed that the `#chat-bridge` channel in Slack is publishing duplicate messages. @mrosseel, could you look into that?

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
@mrosseel, can you leave monthly report comments here in conjunction with your compensation requests? Your request for this month (bisq-network/compensation#55) does have a link to a comment in this issue, but it's old, and refers to the `2017.12` comment above.

If there's nothing to report, you can just say "nothing to report". These updates are, at minimum, a 'heartbeat' signal that role owners are on top of their responsibilities. So it can be as quick as you like, but saying _something_ every month is important. I'll write something up on the bisq-contrib list (or in proposals) about this soon to get consensus about everybody doing this consistently.

FYI, this is the template I use for these report comments:

```
## 2018.03 report

[your notes]

/cc bisq-network/compensation#55
```

**Comment by cbeams** [comment]
I also updated the description of this issue to show that you, @mrosseel, are the 'primary' for this role, and that @ManfredKarrer and I are 'secondary'. I think we need a distinction like this so that folks know who should be "on point" (the 'primary') with servicing requests, doing monthly reports, etc, and who is there as a backup (the 'secondaries') that can provide emergency support or fill in for a primary when they're away.

**Comment by mrosseel** [comment]
## 2018.03 report

* solved the duplicate messages error which was caused by the 'restart=always' feature of docker. I stopped one container and started another, but the old one came back from the dead.
* answered a few support requests

/cc bisq-network/compensation#55

**Comment by cbeams** [comment]
I updated the description of this issue to distinguish @mrosseel as the primary role owner and @cbeams and @ManfredKarrer as secondary, per bisq-network/proposals#12.

**Comment by mrosseel** [comment]
## 2018.04 report

* created https://github.com/bisq-network/proposals/issues/16
==> this resulted in #bitsquare no longer being accessible.
So effectively the only working irc channel is #bisq as intended. The transition however was not good, mainly due to the fact that only the creator of a channel can perform certain things, not an operator - a communication misunerstandig did the rest. Even trying to fix this (if possible) requires the creator account, so there's very little I can do about it at this point.

/cc bisq-network/compensation#63

**Comment by mrosseel** [comment]
## 2018.05 report

Nothing to report.

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#80

**Comment by cbeams** [comment]
@mrosseel or @emzy, could one of you de-op me (cbeams) in the `#bisq` and `#bitsquare` channels? Once I have confirmation that I no longer have any special rights there, I'll remove myself as a secondary from this role. Thanks.

**Comment by cbeams** [comment]
It appears I no longer have `op` status (or the ability to regain it via ChanServ) for either of our channels, so I have removed myself as a secondary from this role. I've also updated the description of the role and the members of the @bisq-network/irc-admins team to reflect.

**Comment by mrosseel** [comment]
## 2018.07 report

Nothing to report

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#105

**Comment by mrosseel** [comment]
## 2018.08 report

There was some spam in the #bisq irc channel. Freenode seems to have taken measures to stop this so no action was necessary from my side.

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#116

**Comment by mrosseel** [comment]
## 2018.09 report

Nothing to report. 
Since I don't spend a lot of time on IRC some new blood is needed in the IRC department, either as helping hand or full replacement.

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#141

**Comment by mrosseel** [comment]
## 2018.10 report

Nothing to report. 
Since I don't spend a lot of time on IRC some new blood is needed in the IRC department, either as helping hand or full replacement.

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#157

**Comment by mrosseel** [comment]
## 2018.11 report

Had some conversations with m52go regarding his rocket-chat syncing, to try using the same bridge as is used with IRC.

PS: Since I don't spend a lot of time on IRC some new blood is needed in the IRC department, either as helping hand or full replacement.

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#181

**Comment by mrosseel** [comment]
## 2018.12 - 2019.02 report

Nothing to report
Since I don't spend a lot of time on IRC a new maintainer would be good for the IRC department

Hosting 1 syncing node on a shared server with monitoring node.

bisq-network/compensation#220

**Comment by mrosseel** [comment]
## 2019.03 - 2019.04 (Cycle 1) report

Nothing to report
Since I don't spend a lot of time on IRC a new maintainer would be good for the IRC department

Hosting 1 syncing node on a shared server with monitoring node.

Because of the disabled syncing and not spending much time on IRC, no compensation will be requested for this period.

bisq-network/compensation#281

**Comment by mrosseel** [comment]
## Cycle 2&3 report

_Since I don't spend a lot of time on IRC a new maintainer would be good for the IRC department_

Hosting 1 syncing node on a shared server with monitoring node.

The #chat-bridge channel on slack was reenabled and resulted in better IRC response times by various contributors (special thanks to Homard)

bisq-network/compensation#312

**Comment by mrosseel** [comment]
## Cycle 4 report

Hosting 1 syncing node on a shared server with monitoring node.

The #chat-bridge channel is still helping us keeping an active presence on slack

bisq-network/compensation#331

**Comment by mrosseel** [comment]
## Cycle 5 report

Hosting 1 syncing node on a shared server with monitoring node.
Server was down for some time, need to find the cause. 

The #chat-bridge channel is still used so good for PR

bisq-network/compensation#362

**Comment by mrosseel** [comment]
## Cycle 6&7 report

Moved the slack and irc bridge to Matrix, this has the advantage that it's always up (as long as the matrix servers are up)
The #chat-bridge channel on slack is still being used.

bisq-network/compensation#407

**Comment by mrosseel** [comment]
## Cycle 8&9 report


The #chat-bridge channel on slack is still being used, mirroring matrix/irc/slack.
A solution for keybase will have to be found, matterbrideg supports keybase but the currently used matrix plugin doesn't.

bisq-network/compensation#468

**Comment by mrosseel** [comment]
## Cycle 10&11 report

Nothing to report.

bisq-network/compensation#511

**Comment by mrosseel** [comment]
## Cycle 12 report

Nothing to report.

bisq-network/compensation#543

**Comment by mrosseel** [comment]
## Cycle 13 report

Nothing to report.

bisq-network/compensation#562

**Comment by mrosseel** [comment]
## Cycle 14 report

Nothing to report.
Some activity in the matrix/irc channels

bisq-network/compensation#601

**Comment by mrosseel** [comment]
## Cycle 15 report

Nothing to report.

bisq-network/compensation#615

**Comment by mrosseel** [comment]
## Cycle 16 report

Nothing to report.

bisq-network/compensation#638

**Comment by mrosseel** [comment]
## Cycle 17 report

Nothing to report.

bisq-network/compensation#681

**Comment by mrosseel** [comment]
## Cycle 18 report

Nothing to report.

bisq-network/compensation#691
