### ISSUE TITLE
Slack Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#23]
This role is responsible for owning (in Slack terminology) and administering Bisq's Slack workspace at https://bisq.slack.com.

 - Slack: `#slack-ops`
 - Issues: https://github.com/bisq-network/slack
 - Invites: https://bisq.network/slack-invite

---

Docs: none, other than the above
Team: @bisq-network/slack-admins 
Primary owner: @m52go

**Comment by cbeams** [comment]
I've just added @ManfredKarrer as an assignee to this role, reflecting the fact that he and I in fact have Owner rights in Slack.

**Comment by cbeams** [comment]
Note that I've just created a repository for this role at https://github.com/bisq-network/slack. See bisq-network/dao#19 for details.

**Comment by cbeams** [comment]
## 2017.12 report

 - Created the `#slack-ops` channel and bisq-network/slack repo to track requests and work related to Slack administration
 - Did lots of normal Slack admin activities, e.g. creating channels etc.
 - Kept an eye on all channels to make sure that infrastructure is working for everyone, that channel design is useful and well-understood etc.
 - Encouraged everybody to keep as many conversations public as possible. As seen in the data below, it seems that this is beginning to work.
 - We have 333 members currently, and had 325 at the turn of the month, which was +68 more members than we had at the beginning of December.
 - The 10,000 message limit is starting to get painful. I often cannot search back to older messages, for example. I looked into how much it would cost to get on a paid plan and have unlimited message history, and it was around $1500 USD. Pretty steep for an out-of-pocket expense, so we'll hold off for now and keep making do with the limited free version.

![screencapture-bisq-slack-admin-stats-1515073313463](https://user-images.githubusercontent.com/301810/34566102-a5cb25a4-f15d-11e7-98df-d0acbd7ba7ec.png)

/cc bisq-network/compensation#26

**Comment by ManfredKarrer** [comment]
1500/month or year? Per months would be really heavy...

**Comment by cbeams** [comment]
> 1500/month or year? Per months would be really heavy...

Per month, given our current number of active users.

**Comment by cbeams** [comment]
## 2018.01 report

As I mentioned a few days ago in `#general` at https://bisq.slack.com/archives/C0336TYTG/p1516633849000423, we're doing amazingly well at keeping our conversations public:

![image](https://user-images.githubusercontent.com/301810/35655395-f31bc490-06f1-11e8-9bfb-e61f812623d6.png)

Otherwise, nothing remarkable to mention, other than that we've been growing our total users and active daily/weekly users pretty nicely.

As a point of reference, the Bisq Slack workspace has about 400 members and the Lightning Network Developer Slack workspace has about 1400. Not bad by comparison, given how much attention Lightning has (deservedly) been getting lately!

Anyway, here are the usual monthly stats:

![screencapture-bisq-slack-admin-stats-1517445943399](https://user-images.githubusercontent.com/301810/35655338-ab78a7ca-06f1-11e8-99c1-5713e9f5261c.png)

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

From https://bisq.slack.com/admin/stats. Note how our **weekly active users** stat continues to grow month over month.

![screencapture-bisq-slack-admin-stats-1519866154081](https://user-images.githubusercontent.com/301810/36821712-a5a39a12-1cf4-11e8-8ed1-669e57a627af.png)

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

From https://bisq.slack.com/admin/stats:

![image](https://user-images.githubusercontent.com/301810/38294519-6b6be63a-37eb-11e8-94fa-f6192d7c8ab0.png)

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

From [https://bisq.slack.com/admin/stats](bisq.slack.com/admin/stats):

We're now at 568 members.

Interesting that we doubled our storage used (from 2.6G to 5.2G) in one month this month. I imagine this has to do with how much more we're uploading Zoom call videos now, but I'm not sure.

![screencapture-bisq-slack-admin-stats-2018-05-03-19_26_47](https://user-images.githubusercontent.com/301810/39592857-5bbcae3e-4f08-11e8-9690-063599bca2ba.png)

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
## 2018.05 report

We're now at 602 members.

From https://bisq.slack.com/admin/stats:

![screencapture-bisq-slack-admin-stats-2018-06-01-14_42_23](https://user-images.githubusercontent.com/301810/40841256-218b70fc-65aa-11e8-9c6a-023344f25e98.png)

/cc bisq-network/compensation#74

**Comment by cbeams** [comment]
## 2018.06 report

We're now at 616 members. Interesting to note in the stats below that our "Weekly active users posting messages" has been hovering at around 30 for as long as we've been capturing these reports. So while the number of people joining the workspace grows, the number of people actively using it has pretty much stayed the same.

![screencapture-bisq-slack-admin-stats-2018-06-30-19_04_17](https://user-images.githubusercontent.com/301810/42127435-d9cf2668-7c98-11e8-9023-97daf84c554f.png)
 
/cc bisq-network/compensation#89

**Comment by cbeams** [comment]
## 2018.07 report

I have a hunch that no one cares about the Slack analytics screenshots that I post here every month, so I'm going to leave it out this month and see if anybody asks for it back.

Otherwise, nothing to report.

**BSQ requested:** `25`

/cc bisq-network/compensation#101

**Comment by ripcurlx** [comment]
I am mainly interested in the information of new members added every month for the analytics report. But as this information is not visible in the free plan I deduct the couple of members that were added in the following month (e.g. August) to get the increase of July. Of course this works only as long as we don't add more than 6 new users until I gather the report.

**Comment by cbeams** [comment]
## 2018.08 report

Nothing to report.

![screencapture-bisq-slack-admin-stats-2018-08-31-16_33_27](https://user-images.githubusercontent.com/301810/44918602-aeac4000-ad3b-11e8-9cb6-af6b67c15621.png)

**BSQ Requested: `25`**

/cc bisq-network/compensation#114

**Comment by cbeams** [comment]
## 2018.09 report

Nothing to report.

![screencapture-bisq-slack-admin-stats-2018-09-30-17_14_00](https://user-images.githubusercontent.com/301810/46259077-6b78f480-c4d4-11e8-8728-d6a61e50a2bd.png)

**BSQ Requested: `25`**

/cc bisq-network/compensation#139

**Comment by ManfredKarrer** [comment]
## 2018.10 report

There have been a case of a scammer who impersonated my slack account and tried to trick people into stupid scam. The users contacted me and sent me the conversation. He also mentioned cbeams in that conversation. 
I was quite shocked to disover that Slack has zero protection against such impersonation scams. One can simple set the user name and deplay name to my name, add profile pic and it looks like the same account. I reported to Slack and they said they forwared it to their dev. Shocking to see that they have zero consciousness for security! 
I strongly would be in favor that we get rid of slack. Beside that severe risk there is the annoying business model where your get locked out of your own content if you don't pay their hefty fees for the pro plan.

As soon any contributor will make it his project to operate a Slack alternative I am in favor to move. But it must happen in a way that it does not consume time from the core contributors and founders as we are too busy with other things....
I must also be one who has a good reputation already as it would include probably hosting and we need to have a certain trust on reliability to that person.

/cc bisq-network/compensation#155

**Comment by cbeams** [comment]
## 2018.10 report

@ManfredKarrer wrote:

> As soon any contributor will make it his project to operate a Slack alternative I am in favor to move.

I've just created a WIP proposal for this at https://github.com/bisq-network/proposals/issues/54.

Here are this month's analytics, from https://bisq.slack.com/admin/stats:

![screencapture-bisq-slack-admin-stats-2018-10-31-21_58_39](https://user-images.githubusercontent.com/301810/47818370-31f80b00-dd58-11e8-98f2-5f374c40aeba.png)



BSQ Requested: `25`

/cc bisq-network/compensation#160

**Comment by cbeams** [comment]
I've made @m52go a Slack admin, at least for the time being, so as to facilitate data migration to the new Rocket.Chat instance.

**Comment by ManfredKarrer** [comment]
## 2018.11 report

Helping to get the migration to Rocket.chat organized. 

/cc bisq-network/compensation#180

**Comment by cbeams** [comment]
## 2018.11 report

@chirhonul and @m52go stepped up this month to start building out a Rocket.Chat alternative to Slack. A role for Rocket.Chat Admin has been created at #79. To follow what's going on there, see  bisq-network/proposals#54. In the meantime, here are our Slack [stats](https://bisq.slack.com/admin/stats) for this month:

![screencapture-bisq-slack-admin-stats-2018-11-30-21_59_31](https://user-images.githubusercontent.com/301810/49314668-6d1e6300-f4eb-11e8-8369-085e3579ff2c.png)

BSQ requested: `25`

/cc bisq-network/compensation#179

**Comment by cbeams** [comment]
@m52go has agreed to take on the role of Slack Admin. I already gave him admin access to Slack (see https://github.com/bisq-network/roles/issues/23#issuecomment-442086127), and I've now removed myself as an admin completely. Thanks Steve!

**Comment by ManfredKarrer** [comment]
## 2018.11 report

Nothing to report.

/cc bisq-network/compensation#189

**Comment by m52go** [comment]
## 2018.12 Report

Migration to Rocket stagnated because of 1) the lack of an outgoing email server and 2) failure to get the Matterbridge server configured.

Outgoing email server has been provisioned as a part of the educational DAO initiative. I will continue working with mrosseel to get Matterbridge sorted out this month.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month:

![screencapture-bisq-slack-admin-stats-2019-01-01-11_59_08](https://user-images.githubusercontent.com/735155/50574761-d4feec80-0dbc-11e9-92a5-de1ffa29aea2.png)

/cc bisq-network/compensation#199

**Comment by m52go** [comment]
## 2019.01 Report

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. We passed 900 members this month.

![screencapture-bisq-slack-admin-stats-2019-02-01-00_13_05](https://user-images.githubusercontent.com/735155/52103955-341b7100-25b6-11e9-91b9-7661124e3afa.png)

/cc https://github.com/bisq-network/compensation/issues/219

**Comment by m52go** [comment]
## 2019.02 Report

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

Nothing notable to report. Rocket.Chat migration is being put on hold until after the DAO launch.

![fireshot capture 002 - analytics - bisq slack - bisq slack com](https://user-images.githubusercontent.com/735155/53603146-a4e68680-3b7e-11e9-882f-63b5ae0c20f0.png)

/cc https://github.com/bisq-network/compensation/issues/234

**Comment by m52go** [comment]
## 2019.03 Report

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

We passed 1,000 users this month.

![screencapture-bisq-slack-admin-stats-2019-03-31-13_12_04](https://user-images.githubusercontent.com/735155/55292280-a346f300-53b6-11e9-8913-124655f73941.png)

/cc https://github.com/bisq-network/compensation/issues/257

**Comment by m52go** [comment]
## 2019.04 Report

Nothing to report.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![screencapture-bisq-slack-admin-stats-2019-05-08-16_49_30](https://user-images.githubusercontent.com/735155/57407499-4eff1200-71b1-11e9-9590-2d66f2f573ea.png)

/cc https://github.com/bisq-network/compensation/issues/277

**Comment by m52go** [comment]
## 2019.05 Report

Nothing to report.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![screencapture-bisq-slack-admin-stats-2019-06-07-16_33_00](https://user-images.githubusercontent.com/735155/59132011-f783cb80-8941-11e9-9c45-23dc64b1d354.png)

/cc https://github.com/bisq-network/compensation/issues/294

**Comment by m52go** [comment]
## 2019.06 Report

Nothing to report. Been researching Riot as an alternative to Slack.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![FireShot Capture 001 - Analytics - Bisq Slack - bisq slack com](https://user-images.githubusercontent.com/735155/60760641-771abe00-a006-11e9-9880-c7a698798322.png)

/cc https://github.com/bisq-network/compensation/issues/304

**Comment by m52go** [comment]
## 2019.07 Report

Nothing to report.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![slack-stats](https://user-images.githubusercontent.com/735155/62633630-74133600-b902-11e9-8393-f7a09ac8665d.png)

/cc https://github.com/bisq-network/compensation/issues/323

**Comment by m52go** [comment]
## 2019.08 Report

Nothing to report.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![FireShot Capture 001 - Analytics - Bisq Slack - bisq slack com](https://user-images.githubusercontent.com/735155/64550790-a9e07b80-d301-11e9-90fa-a913f105000e.png)

/cc https://github.com/bisq-network/compensation/issues/361

**Comment by m52go** [comment]
## 2019.09 Report

Nothing to report.

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![FireShot Capture 001 - Analytics - Bisq Slack - bisq slack com](https://user-images.githubusercontent.com/735155/66498946-e7fdc600-ea8c-11e9-935c-c09deca1f6ca.png)

/cc https://github.com/bisq-network/compensation/issues/372

**Comment by m52go** [comment]
## 2019.10 Report

Nothing to report. As Keybase usage grows, we should probably start removing Slack links throughout docs, website, etc. and make Keybase the main communication channel (discussion needed).

[Slack stats](https://bisq.slack.com/admin/stats) for the past month are in the image below. 

![FireShot Capture 001 - Analytics - Bisq Slack - bisq slack com](https://user-images.githubusercontent.com/735155/68685142-a5ba1f80-0537-11ea-8238-5da59d1fa262.png)

/cc https://github.com/bisq-network/compensation/issues/408

**Comment by m52go** [comment]
## 2019.11 Report

Slack is basically dead now. Slack links across the website and documentation were switched just after the month ended. 

We should accomplish a full switch-over within the next month or two ([see here](https://github.com/bisq-network/proposals/issues/144)), and at that time, this role will be closed.

/cc https://github.com/bisq-network/compensation/issues/442

**Comment by m52go** [comment]
## 2019.12 Report

Nothing to report. Slack will be completely retired in Cycle 10 (upcoming cycle).

/cc https://github.com/bisq-network/compensation/issues/471

**Comment by wiz** [comment]
@m52go since we're burning slack to the ground, can you close this role issue?

**Comment by m52go** [comment]
## 2020.01 Report

Slack is already effectively retired right now, as no one can sign up for a new account, but I still keep it open as a convenient way to manage IRC and Matrix messages, both of which have been getting more activity lately. In Cycle 11 we'll split up who follows IRC and Matrix to make this use of Slack unnecessary.

/cc https://github.com/bisq-network/compensation/issues/497

**Comment by m52go** [comment]
## Cycle 11 Report

I only monitored Slack for the #chat-bridge channel, which we're working on migrating to Keybase with a new matterbridge server. Hopefully that gets done in Cycle 12, otherwise, those channels will need to be followed separately so Slack can actually be shut down.

/cc https://github.com/bisq-network/compensation/issues/513

**Comment by m52go** [comment]
## Cycle 12 Report

I stopped using Slack entirely, using separate means to occasionally follow IRC and Matrix. Slack can now _really really_ be shut down, but I think only the primary workspace owner can do it, so I'll need to arrange for that to happen. Once that's done, this role can be closed.

/cc https://github.com/bisq-network/compensation/issues/540

**Comment by m52go** [comment]
The Slack workspace was deleted during the past cycle, so this role is no longer relevant. @cbeams this issue can probably be closed.

https://bisq.slack.com

![Screenshot from 2020-05-17 22-58-17](https://user-images.githubusercontent.com/735155/82170266-78b64300-98b3-11ea-85ef-6116c6477adf.png)

**Comment by m52go** [comment]
@cbeams this issue can be closed.

**Comment by cbeams** [comment]
Closed as no longer relevant, thanks @m52go.
