### ISSUE TITLE
Telegram Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#24]

**Comment by cbeams** [comment]
I've reached out to Alf Werrmann, who (I believe) moderates https://telegram.me/bisq to see if he is interested in officially owning on this role.

Alf if you are interested in owning this role, please let me know what your GitHub ID is and I'll invite you to our organization and assign you to it.

**Comment by cbeams** [comment]
![image](https://user-images.githubusercontent.com/301810/34688780-9042fbfe-f4b3-11e7-9109-513ebd660fed.png)

**Comment by thob** [comment]
current Tg group link is https://t.me/bisq_p2p - _I help out there with automatized moderation efforts…_

**Comment by cbeams** [comment]
Thanks for the heads-up, @thob! Would you be interested in officially taking on this role of Telegram Admin and earning BSQ for your efforts?

**Comment by thob** [comment]
Hi, I'm gonna discuss it with Alf

**Comment by thob** [comment]
Had a talk with Alf, it's a yes from me. Please advise what to do.

**Comment by cbeams** [comment]
Great, I'll get back to you about this with more details, @thob. In the meantime, can you explain what kind of administrative rights you already have over the Bisq Telegram channel? How do they compare to Alf's rights? Thanks.

**Comment by thob** [comment]
Alf is the creator of this group, I'm an admin _(there're others as well)_ who took care of automatizing moderation and a few other things in order to avoid/reduce spam. 
![screen-2018-02-03 11-26-12](https://user-images.githubusercontent.com/755337/35766251-e5241e3e-08d4-11e8-8ef9-461a3f6b6fa5.png)

**Comment by ManfredKarrer** [comment]
As that role was not further maintained I will close it. If one becomes active handling that role feel free to open up again.
