### ISSUE TITLE
MailChimp Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#27]
This role is responsible for every aspect of the Bisq Newsletter, including crafting its content, determining its frequency of publication, and owning and administering its Mailchimp account.

The Bisq Newsletter currently has 2,500+ subscribers, but we don't send news out very often simply because of resource constraints.

**Comment by cbeams** [comment]
## 2017.12 report

We didn't do a newsletter this month, primarily due to bandwidth issues. We don't have any particular commitment to do a newsletter every month, but given that we have a large and growing subscriber base and that we're now paying for the service every month, it would probably be good to get something out roughly every month.

It always takes time to put together a good newsletter, though, and this is why it would be great to have someone step up and take on this role. 

In any case, here are some quick stats from last month:
 - +333 subscribers / +16% growth
 - 2,481 subscribers total

![image](https://user-images.githubusercontent.com/301810/34564447-09369ea4-f157-11e7-86dd-e7882ae12561.png)

/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
We've been bumped up to a new price tier after crossing 2500 subscribers:

![image](https://user-images.githubusercontent.com/301810/34660474-e737d446-f442-11e7-9708-b0640a2a1828.png)

**Comment by cbeams** [comment]
I've just changed the title of this role from "Mailchimp Admin" to "Newsletter Editor", as this is really the role we most need. The editor will also own and administer the Mailchimp account, but the most important work is actually crafting and sending a regular newsletter. See the updated description for further details.

**Comment by cbeams** [comment]
## 2018.01 report

Our newsletter continued to grow this month—we're now up to 2,800 subscribers. Unfortunately, I've had no time to get a newsletter out, which is really a shame. This is a role we should start aggressively trying to hand off to someone. It's an amazing opportunity, really, to communicate with ~3K people about what we're doing. There's so much going on now, that the newsletter can just about write itself in terms of news. And that would be enough for a start. Just getting the word out about new releases and new features is all we need for now. Ideally we'd have someone who can start writing additional material for the newsletter, too, to really start building the subscriber base and turning the newsletter into something truly interesting. But we can start with small steps.

I'm not sure what the best way to try to find that person is. My first thought is Twitter, but am open to suggestions. We want to find a well-written cypherpunk who wants to help get the word out, as opposed to a generally good newsletter marketing manager. The latter can be learned relatively quickly, while the former is something that takes years to fully realize.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

I sent one newsletter this month, regarding USD liquidity week: https://github.com/bisq-network/newsletter/issues/8. While it got a decent response, I'm not sure it was worth the work I put into it.

In general, the Bisq newsletter remains a bit of a wasted resource. We are now at 2800+ subscribers and I'm paying $45/month for that, but we're not sending them any regular communications.

This role should be handed off to someone who can give the Bisq newsletter the TLC it deserves. See last month's comments for further context / requirements.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

Per this Slack conversation between @cbeams, @ManfredKarrer and @flix1, we have tentatively planned to shut down our MailChimp account as soon as possible.

https://bisq.slack.com/archives/C6C8ELRD4/p1522579176000005:

![image](https://user-images.githubusercontent.com/301810/38294071-029cb1ee-37ea-11e8-8061-2e49711afd0a.png)

I am considering setting up a bisq-announce@lists.bisq.network mailing list, as a place for our MailChimp audience to land (heads up, @emzy). One question is whether to port all the addresses to the new list by default, or to provide a link to sign up in the final MailChimp newsletter we send?

On one hand, I'd rather let people choose, and only end up with those people who really want to keep in touch with Bisq announcements, but on the other hand, I know most people don't really read the newsletter emails they get (they scan them at best), and this means that many will be dropped from our mailing list not because they wanted to be dropped, but because they didn't get the memo about signing up for the new one.

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

We have not yet gone ahead with the plan to decommission Mailchimp described in last month's report. The jury is still out for me on whether we should, and in particular with @pedromvpg's new design refresh coming together, we could see increased interest in our mailing list, and that much more reason to take advantage of it.

I haven't heard any additional complaints about MailChimp shutting down crypto projects. It may be that their change to the acceptable use policy was just CYA on their part and that they're actually using discretion about which projects to target, e.g. scams.

Another thing that's made me reconsider pulling the trigger on decommissioning MailChimp right away is that @m52go has been getting involved with writing projects around Bisq, and if I'm not mistaken, Steve, you operate one or more MailChimp accounts elsewhere, yeah? Would you be interested in taking on this role for us, and managing a monthly (or even less frequent) Bisq newsletter? We have 3K+ subscribers and we're completely silent on this channel just for lack of time and resources. Could be a big/high-leverage opportunity for Bisq to ramp this up.

... AND IT'S GONE:

![image](https://user-images.githubusercontent.com/301810/39576334-11bd4408-4ede-11e8-9ad6-51437014f22b.png)

Nevermind all of the above, folks. It looks like we just got shut down, exactly like we were concerned we might. Should have acted right away after all. I'll email them and see if it's possible to extract any of our data. Ugh.

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
Here is the mail I just sent to compliance@mailchimp.com about this, and their auto-response:

![image](https://user-images.githubusercontent.com/301810/39576774-96ebce00-4edf-11e8-8f82-fbe02d81728d.png)

**Comment by m52go** [comment]
Yeah their compliance team shut me down yesterday but the account was still functional. I just couldn't send any campaigns. You should be able to export contacts while deactivated.

Email is still tremendously powerful...in my opinion, it's not worth skipping email just because MailChimp is throwing a fit. I'd be happy to take on this role if/when we find something that works out.

Should I look into an email marketing service that will allow Bisq?

**Comment by cbeams** [comment]
As I mentioned above in https://github.com/bisq-network/roles/issues/27#issuecomment-378507227:

> I am considering setting up a bisq-announce@lists.bisq.network mailing list, as a place for our MailChimp audience to land (heads up, @Emzy). One question is whether to port all the addresses to the new list by default, or to provide a link to sign up in the final MailChimp newsletter we send?

I don't know why we couldn't do it this way. It's lo-fi, no fancy templates, etc, but it's something we can own completely. I'm open to ideas about this or going with another different service, but most projects don't have their own mailing list infrastructure; we do. Why not use it?

Ultimately we should do a proposal about this change, i.e. where we're going to do newsletter-style operations in the future. I meant to put together exactly this proposal last month, but never got to it. @m52go, that would be a very welcome next step. Make sure you've read https://docs.bisq.network/proposals.html first.

We can just chat about it, brainstorm, etc in #newsletter first, though, of course.

**Comment by cbeams** [comment]
Here is the mail I just got back from MailChimp. We have 48 hours to clear out our stuff before we're locked out for good. I'll take care of this today.

![image](https://user-images.githubusercontent.com/301810/39616184-7de18850-4f7a-11e8-9ef7-8e92e8da50df.png)

**Comment by ManfredKarrer** [comment]
What a crappy company to close accounts without proper notice! But good to get rid of it. Maybe we should rethink other commercial services we depend on as well. Just imagine Slack would start the same crap.... would be quite a hit for our communication infrastructure...

**Comment by cbeams** [comment]
Closing as complete. See details in bisq-network/mailchimp#9, and note that I've republished our MailChimp newsletter archive at https://bisq-network.github.io/mailchimp. I have also exported the ~3000 subscriber names and email addresses and I'll be writing a proposal shortly on what to do with them.
