### ISSUE TITLE
Compensation Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#31]
In lieu of a proper spec, here are the basic requirements for this role:
 1. Maintain the bisq-network/compensation repository, which mainly consists of compensation request issues
 2. Conduct monthly compensation request voting, including emails to bisq-contrib list
 3. Maintain the [BSQ stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0)

See also: https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#track-stake-voting-and-bonding-via-spreadsheet

---

Docs: none, other than the above and a [WIP PR](https://github.com/bisq-network/bisq-docs/pull/62)
Team: @bisq-network/compensation-maintainers 
Primary owner: @ripcurlx
Team: @bisq-network/compensation-maintainers

**Comment by cbeams** [comment]
## 2017.12 report

I conducted November compensation request voting in bisq-network/dao#18, and everything went well. See that issue for links to voting results and other details.

/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
## 2018.01 report

I conducted December voting in bisq-network/dao#26. See issue for results and other details.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

I conducted Feb 1st–3rd voting in https://github.com/bisq-network/dao/issues/39.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

I conducted Mar 1st–3rd voting in https://github.com/bisq-network/compensation/issues/44.

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

I conducted Apr 4th–6th voting https://github.com/bisq-network/compensation/issues/56.

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
## 2018.05 report

@cbeams conducted the May 5th–7th voting at https://github.com/bisq-network/compensation/issues/58.

@cbeams started work to produce a `Compensation` doc at 
https://github.com/bisq-network/bisq-docs/pull/62.

/cc bisq-network/compensation#74

**Comment by ripcurlx** [comment]
## 2018.6 report
@cbeams conducted the Jun 1st–4th voting at https://github.com/bisq-network/compensation/issues/70.

@ripcurlx took over managing the voting process starting with this month at https://github.com/bisq-network/compensation/issues/82.  

/cc https://github.com/bisq-network/compensation/issues/84

**Comment by ripcurlx** [comment]
## 2018.07 report
@ripcurlx conducted the Jun 1st–3rd voting at https://github.com/bisq-network/compensation/issues/82.

/cc bisq-network/compensation#98

**Comment by cbeams** [comment]
Note: I've updated the description of this issue for accuracy and removed @ManfredKarrer as a secondary owner.

**Comment by ripcurlx** [comment]
## 2018.08 report
@ripcurlx conducted the Jul 1st–3rd voting at https://github.com/bisq-network/compensation/issues/94.

/cc bisq-network/compensation#109

**Comment by ripcurlx** [comment]
## 2018.09 report
@ripcurlx conducted the September 1st–3rd voting at https://github.com/bisq-network/compensation/issues/107.

/cc bisq-network/compensation#126

**Comment by ripcurlx** [comment]
## 2018.10 report
Conducted the October 1st–3rd voting at https://github.com/bisq-network/compensation/issues/121.

/cc bisq-network/compensation#148

**Comment by ripcurlx** [comment]
## 2018.11 report
Conducted the November 1st–3rd voting at https://github.com/bisq-network/compensation/issues/149.

/cc bisq-network/compensation#177

**Comment by ripcurlx** [comment]
## 2018.12 report
Conducted the December 1st–4th voting at https://github.com/bisq-network/compensation/issues/165.

/cc bisq-network/compensation#195

**Comment by ripcurlx** [comment]
## 2019.01 report
Conducted the January 1st–4th voting at https://github.com/bisq-network/compensation/issues/183.

/cc bisq-network/compensation#206

**Comment by ripcurlx** [comment]
## 2019.02 report
Conducted the February 1st–4th voting at https://github.com/bisq-network/compensation/issues/204.

/cc bisq-network/compensation#224

**Comment by ripcurlx** [comment]
## 2019.03 report
Conducted the March 1st–4th voting at https://github.com/bisq-network/compensation/issues/222.

/cc bisq-network/compensation#247

**Comment by ripcurlx** [comment]
## 2019.04 report
Conducted the April 1st–4th voting at https://github.com/bisq-network/compensation/issues/243.

/cc bisq-network/compensation#269

**Comment by ManfredKarrer** [comment]
Should we close that role as it is now done by software?

**Comment by ripcurlx** [comment]
> Should we close that role as it is now done by software?

I agree. The only reason to keep this role active would be to remind contributors to file compensation requests. It will be difficult to automate that properly within Slack as our timing is now based on blocks. Not sure if it is worth to continue to set the different phases in the Google Calendar as well. I'm definitely not the one who wants to keep this role alive 😉

**Comment by ManfredKarrer** [comment]
Ok, I will close. People will learn to take care themself on the phases. Once missed one is probably enough to remember next time...

**Comment by cbeams** [comment]
Note that this role was resurrected in #86, as there are management duties to be carried out around each cycle, e.g. sending out announcements about BSQ/USD rate, submission deadlines, keeping the (new) compensation board up-to-date, etc.
