### ISSUE TITLE
Bitcointalk Moderator

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#37]
This role is about keeping the [Bisq thread](https://bitcointalk.org/index.php?topic=4509053.0) on the Bitcointalk forum up-to-date.

----

Docs: none, other than the above
Team: @bisq-network/bitcointalk-moderators 
Primary owner: @flix1 
Secondary owner: @alexej996

**Comment by alexej996** [comment]
I am keeping up with the thread, but the original post is very outdated.
It is still called bitsquare.io and has broken image links.

Only Manfred can change this and I don't think he is able to give anyone access to it without giving them his personal Bitcointalk account that he used to create this topic, which would be a bad idea.

I think we should maybe create a new Bitcointalk account with "Bisq" in it's name and create a new self-moderated topic. Then give the credentials to whoever takes this role.

**Comment by ManfredKarrer** [comment]
Agree. I can close then the thread and forward to the new one. Done that also with the very first thread (when Bisq was Bankrun ;-))

**Comment by flix1** [comment]
I can help with this. I used to have a Bitcointalk account (https://bitcointalk.org/index.php?action=profile;u=5507)  but lost it, but I'll be happy to create a new one or use the Bisq one.

**Comment by ManfredKarrer** [comment]
@flix1 Can I add you as primary role owner? 
@alexej996 can I add you as secondary?

**Comment by alexej996** [comment]
Sure. I have been successfully keeping up to date on that thread so far.
The problem is however that it is outdated and that it is a self-moderating thread, which means the thread creator (and only the thread creator) can moderate it. There is no way of adding other people as moderators on a self-moderation thread.

I think we should create a new account on bitcointalk called "Bisq" or something and create a new self-moderating thread with it. Then close the old thread and link to the new one.
Having a bitcointalk account specific to this role would be an easy way to transfer this role between people without losing the self-moderation ability.

**Comment by ManfredKarrer** [comment]
Yes, feel free to create a new one and I will close then the old.

**Comment by flix1** [comment]
@alexej996 I agree it's good to have accounts with "Bisq" in them. Rather than have an official Bisq account I would do **Bisq_flix**, **Bisq_alex**, etc.. so that each person can **own** their account, manage their own passwords, etc.

**Comment by alexej996** [comment]
@flix1 Sure, but some account needs to be used to create a Bisq thread and that account will forever have self-moderating access to it. You can't add new people to be moderators of a thread so only way of transferring a Bitcointalk moderator role would be to give credentials to that account that created the Bisq thread.

**Comment by flix1** [comment]
@alexej996 You are right! There has to be a Bisq_network main forum account. I'll create it today.

**Comment by flix1** [comment]
@ManfredKarrer please lock the old thread to make sure replies go to new one.

My plan as moderator is simple:

1. Check the thread every day and respond to user questions.
2. Add new content every week (videos, tutorials, events, news, etc..) to keep the thread active.

My initial committment is for 6 months. So by December 2018 at the latest I should be replaced by someone else. I think that forum mod/user support is a good learning role where we can try out new contributors before moving them on to other stuff. Rotation should be baked in.

**Comment by ManfredKarrer** [comment]
I locked the old thread. Thanks!

**Comment by cbeams** [comment]
I updated the link to the thread in the description of this issue.

**Comment by flix1** [comment]
Nothing much beyond the plan.

> 1. Check the thread every day and respond to user questions.
> 2. Add new content every week (videos, tutorials, events, news, etc..) to keep the thread active.

https://bitcointalk.org/index.php?topic=4509053.0

**Comment by flix1** [comment]
Not much activity this month. Still sticking to the plan:

> 1. Check the thread every day and respond to user questions.
> 2. Add new content every week (videos, tutorials, events, news, etc..)

https://bitcointalk.org/index.php?topic=4509053.0

The thread has been viewed 664 times. Only a handful of responses. I try to keep it in the top page of the [Bitcoin Forum > Economy > Marketplace > Service Discussion > Exchanges] subforum without spamming or posting useless content.

**Comment by ArnaudFR86** [comment]
> I think that forum mod/user support is a good learning role where we can try out new contributors

i'll like to give myself a try !

**Comment by m52go** [comment]
@flix1 @alexej996 was this a valuable endeavor? It seems to have faded...I assumed it's because it lost value.

**Comment by flix1** [comment]
@m52go value was moderate, but effort was also low. I agree that it is a good learning role.

It faded because I was unable to continue in any of my roles due to family issues. However I would support someone taking over the role.

@ArnaudFR86 just go right ahead!

**Comment by ArnaudFR86** [comment]
@flix1 it works, i'll take care of it from now ! Thanks for your reply.  Does it require to apply in the Bisq client under DAO->Governance like for being an ambassador ?

**Comment by flix1** [comment]
>  Does it require to apply in the Bisq client under DAO->Governance like for being an ambassador ?

I don't think that is necessary. Just make a monthly compensation request as for other roles and submit it to the DAO in each cycle.

**Comment by alexej996** [comment]
There wasn't much activity on bitcointalk thread, as far as I remember, less than other platforms, but there was some.

There isn't much work needed there, maybe one post every couple of days/weeks. But it is good to have someone watching it in my opinion.

**Comment by ArnaudFR86** [comment]
I've made 2 posts during the last month, but I did not got yet interactions from others users.

https://bitcointalk.org/index.php?topic=4509053.msg51359592#msg51359592

Thinking about roles, I can also post dedicated annonces to attract new contributors being able to complete tasks having special bounty. I can also create a Bisq topic in the French area.

 I think regional ambassadors roles should include communication on all socials medias in their native langages, that should allow to post more on Twitter, Telegram and others without risks to damage reputation on mains accounts like the Twitter one, it could be call "Bisq Community" like it is done for Basic attention token https://twitter.com/BAT_Community.

@flix1 What is the compensation for this role ? As it is not an heavy one yet, may be, it can be combined with some tasks from a regional ambassador role ? 

Thanks for your views

**Comment by ArnaudFR86** [comment]
I've posted weekly growth calls sum up on Bitcointalk, I still don't get questions but users are looking at it as "read"  raised from 2083 to 3084.

I've also created a Bisq France community Twitter account: https://twitter.com/BisqF

**Comment by ArnaudFR86** [comment]
Since last month, BTT topic reads increased from 3084 to 5380, so despite the fact that ppl don't ask questions on main topic, it seems to be read by users.

I've also created a post about Bisq looking for devs,110 reads and got replies from users.
https://bitcointalk.org/index.php?topic=5175007.msg52149456#msg52149456 

It seems that posting 3-4 times per month is a good ratio, I will continue to post on regular basis infos about software update, Bisq news, online meeting sum up, new marketing content from Bisq, press,  community and infos about market volums. I'll try a longer post format for the next posts, may be including pictures.

I think It is also positive to create specific topic for specific needs (as the one for devs needs), So I will post if we have more bounty or translators needs.

@m52go I had to back to you about the framework of this role, if you have some ideas or comments, thanks !

**Comment by ArnaudFR86** [comment]
Hello everyone,
Not a big role, but I keep posting on Bitcointalk topic: 
https://bitcointalk.org/index.php?topic=4509053.80
Views **10816 ** and comments are friendly.

**Comment by cbeams** [comment]
@m52go, what should be done with this role? I believe this sort of thing falls under the Community Manager role (#95) now, correct? I also see that a recent post by @ArnaudFR86 was marked as off-topic on that role issue. Not sure if we should close this issue as superseded by Community Manager or not, please advise.

**Comment by m52go** [comment]
> I believe this sort of thing falls under the Community Manager role (#95) now, correct?

Yes, no need for this separate role any more.

**Comment by cbeams** [comment]
Closing as superseded by #95.
