### ISSUE TITLE
Bitcoin Node Operator

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#39]
The idea here is that a number of Bisq contributors take on this role, run a full node and publicly attest that their full node will run the latest major version of **Bitcoin Core**. Doing this provides a service to Bisq users who want to ensure they're on the correct chain during contentious forks like that posed by the forthcoming SegWit2X project.

See https://lists.bisq.network/pipermail/bisq-contrib/2017-November/000006.html for further details and links.

| operator | clearnet IP:port | clearnet name | onion address |
|----|----|----|----|
| @ManfredKarrer | 159.89.16.222 | btc1.0-2-1.net | r3dsojfhwcm7x7p6.onion |
| @ManfredKarrer | 165.227.34.56 | btc2.0-2-1.net | vlf5i3grro3wux24.onion |
| @ManfredKarrer | 165.227.44.202 | btc3.0-2-1.net | i3a5xtzfm4xwtybd.onion |
| @emzy | 78.47.61.83 | kirsche.emzy.de | fz6nsij6jiyuwlsc.onion |
| @emzy | 62.75.210.81 | node2.emzy.de | c6ac4jdfyeiakex2.onion:8333 |
| @emzy | 163.172.171.119 | node1.emzy.de| sjyzmwwu6diiit3r.onion:8333 |
| @emzy | n/a | n/a | poyvpdt762gllauu.onion:8333 |
| @ripcurlx | 174.138.35.229:8333 | btc.christophatteneder.com | lgkvbvro67jomosw.onion |
| @mrosseel | 138.68.117.247:8333 | btc.vante.me | 4jyh6llqj264oggs.onion |
| @mrosseel |  67.207.75.7 | btc2.vante.me | mxdtrjhe2yfsx3pg.onion |
| @sqrrm | 185.25.48.184 | btc4.0-2-1.net | 3r44ddzjitznyahw.onion:8333 |
| @sgeisler | 5.189.166.193:8333 | bcwat.ch | z33nukt7ngik3cpe.onion |
| @jhoenicke | 88.198.39.205:8333 | btc.jochen-hoenicke.de | sslnjjhnmwllysv4.onion:8333 |
| @tbocek | 192.41.136.217:8333 | bitcoin4-fullnode.csg.uzh.ch | n/a |

**Comment by ManfredKarrer** [comment]
See also https://docs.google.com/document/d/1Fgxfrcpx1RNm36-YjqM5dLw3wXETsneEF2CKdXwJJ5Q/edit#heading=h.1rb4hptmf06h for more details.

**Comment by cbeams** [comment]
I've just assigned myself to this role. As I also [just tweeted](https://twitter.com/cbeams/status/927884227634491393), I'm running a Bitcoin fullnode at btc.beams.io:8333. It's running Bitcoin Core 0.15.0.1 and I'll keep it up to date over time.

**Comment by cbeams** [comment]
Please add a comment similar to mine if you're a Bisq contributor willing to run a Bitcoin fullnode and keep it up to date over time. I'll add you as an assignee.

Note that this is a bonded role, so only BSQ stakeholders should apply. We'll figure out the exact bonding level later, but it'll probably be at least 1,000 BSQ.

**Comment by Emzy** [comment]
Please assign me to this role. I'm running a Bitcoin fullnode at kirsche.emzy.de:8333
It's running Bitcoin Core 0.15 and I'll keep it up to date over time. 
FYI 0.15.0.1 is a GUI fix so I haven't installed it on the headless node.

**Comment by cbeams** [comment]
Done, thanks @Emzy.

**Comment by mrosseel** [comment]
Also up for this, not yet running a node atm though.

**Comment by cbeams** [comment]
Thanks @mrosseel, just post a comment here when it's up and running and I'll assign you.

**Comment by ManfredKarrer** [comment]
@cbeams @Emzy Please add your IP as well as a hostname requires DNS lookup which can be avoided here.

**Comment by cbeams** [comment]
I've added a list to the description with hostname, port and IP address. I'll update the list as folks comment here.

**Comment by Emzy** [comment]
kirsche.emzy.de (78.47.61.83)

**Comment by cbeams** [comment]
@manfredkarrer, note that it might be good to rely on DNS lookups at first; we may want / need to move these nodes around physically over the next few months until roles etc are settled.

**Comment by ManfredKarrer** [comment]
@cbeams Ok, good point.

**Comment by ManfredKarrer** [comment]
The DNS lookup (over Tor) takes about 600 ms on my bad internet connection (might be faster for others). So for that reason I would prefer to use the IP instead the hostname. There might be room for improvements for the DNS lookup as well...

**Comment by cbeams** [comment]
How often does that lookup happen? In any case, please do as you see fit; just wanted to put the idea out there.

**Comment by ripcurlx** [comment]
Here we go: 174.138.35.229 - a nice subdomain for the ip is coming soon :-)
My very creative subdomains: bitcoin.christophatteneder.com or btc.christophatteneder.com
Both would work...

**Comment by ManfredKarrer** [comment]
@cbeams At startup once. But it is a blocking call atm so would try to avoid it.

**Comment by alexej996** [comment]
Clearnet node: spidernet.tk:8333 (it has a dynamic IP unfortunately so it needs to use DNS to get it)
Tor node: vlf5i3grro3wux24.onion:8333

PS: The clearnet node has a onion address as well if you need.

**Comment by cbeams** [comment]
Great @alexej996, thanks!

**Comment by ManfredKarrer** [comment]
@alexej996 Yes if you can provide the onion of the spidernet.tk:8333 node would be better. We are short on onion nodes...

**Comment by alexej996** [comment]
The onion address for the clearnet node is r3dsojfhwcm7x7p6.onion

**Comment by ManfredKarrer** [comment]
@alexej996 Perfect! I will use only the 2 onion addresses.

**Comment by cbeams** [comment]
Cool, table has been updated (and now it's a proper table)

**Comment by ManfredKarrer** [comment]
FYI: 
https://twitter.com/MrHodl/status/927916865183240193
https://people.xiph.org/~greg/banlist.cli.txt

**Comment by Emzy** [comment]
Bitcoin node with onion address: poyvpdt762gllauu.onion:8333
This node has no clearnet address.

**Comment by ripcurlx** [comment]
@cbeams My clearnet name is: btc.christophatteneder.com:8333

**Comment by sqrrm** [comment]
I've got and onion only 0.15.0 node on 3r44ddzjitznyahw.onion:8333

Do we require upgrades to latest minor release? Upgrading requires some downtime that I'd rather avoid.

**Comment by ManfredKarrer** [comment]
Thanks!
No upgrade needed, latest patch was UI only changes. Also good to have a bit diversity with versions.

**Comment by ManfredKarrer** [comment]
I sent out invitations to 10 other devs for providing their BTC nodes. No answer so far ;-(. If we don't get enough nodes added by them I would ask you (@cbeams,  @ripcurlx, @mrosseel, @sqrrm) to run a second one if possible. Would be good to have about 50% onion nodes. If I find time I will also setup some but super buys with getting the release ready....

**Comment by tbocek** [comment]
Here is a full BTC node I'm operating: bitcoin4-fullnode.csg.uzh.ch, it has a fixed IP.

**Comment by cbeams** [comment]
Thanks, @tbocek. I've added your node to the table above, and I've sent you an invite to join the @bisq-network GitHub org, such that I can assign you to this issue.

**Comment by ManfredKarrer** [comment]
Yes that is great news! So the urgent threat is gone. We will still keep that feature as it avoids the privacy problems with bloom filters and because we are protected in future if such attacks repeat. We did not see such the first time (XT, Unlimted, Classic, BCH). Better to be prepared in advance.
I think it is also a good resource for people who want to pick nodes from people with good reputation to connect to.

**Comment by sgeisler** [comment]
I have already sent a mail to @ManfredKarrer, you can include bcwat.ch in your list (5.189.166.193:8333).

**Comment by cbeams** [comment]
Thanks, @sgeisler. Like with with @tbocek, I've just sent you an invitation to join the @bisq-network GitHub org, so we can assign you to this issue.

**Comment by cbeams** [comment]
Note that I've updated the description of this issue to indicate that our nodes should run the latest *major version* of Bitcoin Core (where major version means, say, 0.14.* vs 0.15.*). Some diversity in  minor versions is probably a good thing, and we can in most cases probably be a bit relaxed about upgrading to the very latest minor releases.

**Comment by sgeisler** [comment]
@cbeams I've started a core 0.15.0.1 node on bcwat.ch (running on port 8333). The old btcd is still running on port 8334.

**Comment by cbeams** [comment]
Roger that, @sgeisler. Did you get the invitation to join the GitHub org?

**Comment by sgeisler** [comment]
@cbeams yes, couldn't find it at first ;) (somehow it was only shown on the project's page and not in my notifications)

**Comment by mrosseel** [comment]
On slack there's a new channel called #fullnode where we can discuss installation, running and upgrades of our full nodes. Could not find slack users for @sgeisler and @tbocek => if you want please join slack via this link: https://bisq.network/slack-invite

**Comment by jhoenicke** [comment]
My node's (btc.jochen-hoenicke.de) ip is: 37.221.198.57:8333 ; ipv-6: [2a03:4000:9:8e::1]:8333

**Comment by mrosseel** [comment]
clearnet node IP: 138.68.117.247
clearnet name: btc.vante.me
tor node: mxdtrjhe2yfsx3pg.onion

Note: the clearnet node and tor node are hosted on 2 separate machines

**Comment by sqrrm** [comment]
Added a new node:
clearnet: 80.233.134.60:8333
no name:
tor: i3a5xtzfm4xwtybd.onion:8333

**Comment by cbeams** [comment]
@sqrrm, I've added the node details above, and the table now reflects that you're running two nodes. Thanks.

**Comment by cbeams** [comment]
I've also updated the table to strike out my node for the time being. I'm in the process of upgrading the target machine and may not be able to have the node up and running reliably by the time 0.6.0 is out. I'll update the table and add another comment when I do get the node up permanently.

**Comment by themighty1** [comment]
Hi, dansmith here.
Running my always-on node on 7sl6havdhtgefwo2.onion

**Comment by ManfredKarrer** [comment]
@themighty1 Thanks! We are getting more onion nodes than clear net nodes. Great!

**Comment by ripcurlx** [comment]
@tbocek & @jhoenicke: Hi Thomas & Jochen! Could you join us on Slack (https://bisq.network/slack-invite) in the #monitoring channel as well?  @mrosseel has set up some basic monitoring of the full nodes and has problems connecting to your nodes now and then.  Would be great to check if the error messages are false positives at the moment or if there is a real problem. Thanks! :-)

**Comment by ManfredKarrer** [comment]
@themighty1 Your node is not available. Could you have a look to it?

**Comment by Emzy** [comment]
Two new Bitcoin nodes from me:
62.75.210.81 c6ac4jdfyeiakex2.onion
163.172.171.119 sjyzmwwu6diiit3r.onion

**Comment by sqrrm** [comment]
I have moved 3r44ddzjitznyahw.onion and it now also has a clearnet address:
185.25.48.184 3r44ddzjitznyahw.onion

**Comment by ManfredKarrer** [comment]
r3dsojfhwcm7x7p6 was moved to one of @Emzy clearnet nodes.

**Comment by Emzy** [comment]
r3dsojfhwcm7x7p6.onion is now running temporary on 62.75.210.81 as second hidden service.

**Comment by jhoenicke** [comment]
I upgraded to a more powerful server, hopefully with fewer timeouts. Can you change the ip from 37.221.198.57 to 88.198.39.205?

**Comment by ManfredKarrer** [comment]
Thanks for the update. The 37.221.198.57 server is not used then anymore I assume. The nodes are hard coded so the change will be only in the next update. I will change also that the domain name will be used instead of the IP (costs extra DNS lookup via Tor but is more flexible for such cases).

**Comment by jhoenicke** [comment]
The old server is still running, but that may change in the future.  So it is not a problem, if the change isn't immediate.

**Comment by ManfredKarrer** [comment]
Ah cool. We will have soon an update anyway and our users are usually fast with updating. Just changed that we use the domain instead the IP if both are available.

**Comment by sgeisler** [comment]
I added a tor hidden service to my bcwat.ch node: z33nukt7ngik3cpe.onion:8333

**Comment by ManfredKarrer** [comment]
@sgeisler Ah great thanks!

**Comment by ManfredKarrer** [comment]
@tbocek @jhoenicke : Co you have your nodes also reachable as onion nodes?

**Comment by ripcurlx** [comment]
My node with hidden service: lgkvbvro67jomosw.onion:8333

**Comment by Emzy** [comment]
New hostnames for my nodes:
node1.emzy.de has address 163.172.171.119
node2.emzy.de has address 62.75.210.81

**Comment by mrosseel** [comment]
* 138.68.117.247 now has an onion address as well: 4jyh6llqj264oggs.onion
* mxdtrjhe2yfsx3pg.onion now has a clearnet IP as well: 67.207.75.7

**Comment by ManfredKarrer** [comment]
@mrosseel Can you set a domain name as well. Gives more flexibility in case of moving the host.

**Comment by ManfredKarrer** [comment]
@Emzy Can you setup tor for 78.47.61.83 and provide a domainname + IP for poyvpdt762gllauu.onion?

**Comment by ManfredKarrer** [comment]
@jhoenicke, @tbocek, @sgeisler : 
Do you have the maxconnections set to default (125) or do you have set it higher? 
500 seems to be good but of course cause more traffic. 
We saw that the nodes are not getting filled up (and then rejecting new connections) if that limit is > 400. 

Also the timeout for btc nodes is default 5 sec. which seems for Tor connections too low. We increase that now to 30 sec. Do you see any concerns by changing that?  

I use those settings in bitcoin.conf:
maxconnections=500
timeout=30000

I use Tor only for incoming connections, so no setup on the btc side just edited the torrc files. That way the btc node has no risk to get partitioned from the rest of the btc network as it get mixed incoming connections and connects itself via clearnet to other btc nodes.

We will change the behavior also that we will connect to onion nodes only if the user has Tor enabled for BitcoinJ. That prevents privacy and performance issues with Tor exit nodes if Bisq nodes would connect to clearnet btc nodes over Tor.
Do you see any concerns by sticking to Tor btc nodes only (as mentioned above there should be no risk for btc network partitioning issues).

**Comment by Emzy** [comment]
My node kirsche.emzy.de has now a onion address:
78.47.61.83:8333 | kirsche.emzy.de | fz6nsij6jiyuwlsc.onion:8333

**Comment by cbeams** [comment]
Closing as superseded by #67, primarily because this issue has gotten so long and is in many ways now out of date. See also the new "Bitcoin Node Maintainer" role at #66.

The distinction between Maintainer and Operator here is important. Going forward, the Bitcoin Node Maintainer (currently @ManfredKarrer) will be responsible for updating shared `bitcoin.conf` config files and ensuring that all operators in the federation are aware of and up to date with changes to it. This way we should have clear lines of responsibility about ensuring that config changes get propagated across the federation in a consistent and timely way.

**Comment by heyaco** [comment]
Is this list still being maintained? I am looking for some trusted & reliable Tor fallback nodes for bitcoin.
