### ISSUE TITLE
Analytics Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#40]
Spec: https://github.com/bisq-network/roles/blob/master/data-analyst.adoc

**Comment by cbeams** [comment]
Per [Slack conversation](https://bisq.slack.com/archives/C7WRK8DBM/p1510228736000271), I have just handed over administrative rights to Google Analytics to @ripcurlx, to be managed going forward as part of this role.

I have removed my administrative / user management / editing rights, but left intact my ability to view and collaborate. @ripcurlx, it's all yours from here!

**Comment by cbeams** [comment]
I've updated the title of this role from 'number cruncher' to 'data analyst', reflecting discussions between me and @ripcurlx in Slack and elsewhere. The GitHub repository has already been renamed to bisq-network/analytics as well.

**Comment by ripcurlx** [comment]
# 2017.11 update

![bisq-monthly-report-nov-2017](https://user-images.githubusercontent.com/170962/33556200-643fdcb4-d903-11e7-9208-3629842c94bd.png)

**Comment by ripcurlx** [comment]
## Report for December
### Google Analytics
Continuous monitoring of metrics to react to certain issues.

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing)
Integrated trades API into reporting sheet to add detailed reporting sheets on different markets (EUR_BTC, USD_BTC, BTC_XMR) and created our [first monthly report](https://github.com/bisq-network/roles/issues/40). Infographic for December will follow soon!

Communication and Investigation on volume number discrepancy issue with coin.dance https://github.com/bisq-network/analytics/issues/1. Now it should only be a matter of developer resources on coin.dances side.

General moderation of `#analytics` channel.

**Comment by ripcurlx** [comment]
![bisq-monthly-report-dec-17](https://user-images.githubusercontent.com/170962/34560981-615bb6f0-f148-11e7-8766-2c944bdab1d8.png)

**Comment by ripcurlx** [comment]
## Report for January
### Google Analytics
Adding of captions for each video posted on the youtube channel to be able to see changes in referral traffic from youtube more easily. Continuous monitoring of metrics to react to certain issues.

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing)
Improvements of "All Trades from API" sheet to support trades with different base coin (e.g. ltc), switching from GoogleFinance as price provider to CoinMarketCap (Cryptofinance add-on) and created our [monthly report for December 2017](https://github.com/bisq-network/roles/issues/40#issuecomment-355256901). Infographic for January will follow soon!

General moderation of `#analytics` channel.

**Comment by ripcurlx** [comment]
![Monthly Report January 2018](https://user-images.githubusercontent.com/170962/35730393-420795b8-0812-11e8-97f7-ce5a1d1d544e.png)

**Comment by thob** [comment]
I'm gonna share it in the Telegram group…

**Comment by ripcurlx** [comment]
## Report for February
### Google Analytics
Continued to add captions for each video posted on the youtube channel to be able to see changes in referral traffic from youtube more easily. Monitoring of metrics to react to certain issues.

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing)
Added sheet for number of trades for all markets, GBP/BTC market and created our [monthly report for January 2018](https://github.com/bisq-network/roles/issues/40#issuecomment-362558691). Infographic for February will follow soon!

General moderation of `#analytics` channel.

**Comment by ripcurlx** [comment]
![bisq-monthly-report-feb-2018](https://user-images.githubusercontent.com/170962/36892790-29aeaa10-1e06-11e8-8a27-cb1f1c6ff106.png)

**Comment by ripcurlx** [comment]
## Report for March
### Google Analytics
Continued to add captions for each video posted on the youtube channel to be able to see changes in referral traffic from youtube more easily. Monitoring of metrics to react to certain issues.

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing)
Updated sheets were needed and created our [monthly report for February 2018](https://github.com/bisq-network/roles/issues/40#issuecomment-369872863). Infographic for March will follow soon!

General moderation of `#analytics` channel.

**Comment by ripcurlx** [comment]
![Monthly Report April 2018](https://user-images.githubusercontent.com/170962/39639351-4dd16cda-4fc9-11e8-85ce-4dee5c242836.png)

**Comment by ripcurlx** [comment]
## 2018.05 report
### Google Analytics
Monitoring of metrics to react to certain issues.

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing)
Updated sheets were needed and created our [monthly report for April 2018](https://github.com/bisq-network/roles/issues/40#issuecomment-386656504). Infographic for May will follow soon!

General moderation of `#analytics` channel.

/cc https://github.com/bisq-network/compensation/issues/71

**Comment by ripcurlx** [comment]
## 2018.06 report
### Google Analytics
Monitoring of metrics to react to certain issues.

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit)
I needed to add a fallback price service (https://coinmarketcap.com/api/) as Google Finance started to stop delivering BTC/USD exchange rate every now and then. Updated sheets were needed and created our monthly report for May 2018. Infographic for June will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#84

**Comment by ripcurlx** [comment]
![Monthly Report June 2018](https://user-images.githubusercontent.com/170962/42314428-44cdd25c-8045-11e8-9cbb-23b77fe5a46d.png)

**Comment by ripcurlx** [comment]
## 2018.07 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Added new sheets for our two liquidity weeks (XMR/BTC and BTC/CHF) and created our monthly report for June 2018. Infographic for July will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#98

**Comment by ripcurlx** [comment]
![Monthly Report July 2018](https://user-images.githubusercontent.com/170962/43791390-d38c8778-9a75-11e8-9fd8-20340b475413.png)

**Comment by ripcurlx** [comment]
## 2018.08 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Added new sheets on request of @HarryMacfinned to be able to analyze all trades of the last four months.

General moderation of #analytics channel.

/cc bisq-network/compensation#109

**Comment by ripcurlx** [comment]
![Monthly report August 2018](https://user-images.githubusercontent.com/170962/45040936-6bb5d980-b067-11e8-93d4-87cd848598de.png)

**Comment by ripcurlx** [comment]
## 2018.10 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Infographic for October will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#148

**Comment by cbeams** [comment]
@ripcurlx, do you plan to tweet the above? I'll retweet when you do.

**Comment by ripcurlx** [comment]
@cbeams Just tweeted (https://twitter.com/chrisattee/status/1059785307363651585). Was afk until now.

**Comment by bobbyong** [comment]
Hey @ripcurlx cool stuff you have here! Saw that you are looking for some alternative data feed above. If you are still considering, you may look at CoinGecko's API here: http://coingecko.com/api

or the Google Sheets Add-On: https://chrome.google.com/webstore/detail/coingecko-cryptocurrency/ljiodamkcogcfdknlabjlpeiaolmfeeb

**Comment by ripcurlx** [comment]
@bobbyong Thanks for the links. I'll have a look at it next week. Was just too much work to do on our upcoming release this month.

**Comment by ripcurlx** [comment]
## 2018.11 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Infographic for November will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#177

**Comment by ripcurlx** [comment]
![Monthly Report November](https://user-images.githubusercontent.com/170962/49590362-fe6a5b00-f96b-11e8-8e18-675531a1bcf0.png)

**Comment by ripcurlx** [comment]
## 2018.12 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Infographic for December will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#195

**Comment by ripcurlx** [comment]
![Monthly Report December](https://user-images.githubusercontent.com/170962/50682076-f3a7f200-100d-11e9-96cb-368200654cb9.png)

**Comment by ripcurlx** [comment]
## 2019.01 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
- Changed to a fixed fee percentage of 0.4% in the model sheet
- Added [a new sheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=447223194) that puts **BSQ added by vote** and **fees paid** into relation. Fee information for the current month will always be pulled from arbitration addresses via blockchain.info API and statically stored after each month. The BSQ added by value is loaded from the voting spreadsheet.

Infographic for January will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#206

**Comment by ripcurlx** [comment]
## 2019.02 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Infographic for February will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#224

**Comment by ripcurlx** [comment]
![Monthly Report February 2019](https://user-images.githubusercontent.com/170962/53960366-6b65cc00-40e6-11e9-972d-44c8157ee272.png)

**Comment by ripcurlx** [comment]
## 2019.03 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Infographic for March will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#247

**Comment by ripcurlx** [comment]
![Monthly Report March](https://user-images.githubusercontent.com/170962/56363689-16d96480-61ed-11e9-8875-a8d006fe1053.png)

**Comment by ripcurlx** [comment]
## 2019.04 report
### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Infographic for April will follow soon!

General moderation of #analytics channel.

/cc bisq-network/compensation#269

**Comment by ripcurlx** [comment]
![monthly-5c-20re_39737290 (2)](https://user-images.githubusercontent.com/170962/60734446-4aa46a80-9f50-11e9-8314-8c3c045a21bf.png)

**Comment by ripcurlx** [comment]
## Cycle 2 report
Because of personal reasons I missed to provide the report in time for last cycle. Sorry about that!

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
## Cycle 3 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
![Monthly Report July 2019](https://user-images.githubusercontent.com/170962/63352959-4a2a2c80-c362-11e9-89e5-f4d3cac751fa.png)

**Comment by ripcurlx** [comment]
## Cycle 4 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
![Monthly Report August 2019](https://user-images.githubusercontent.com/170962/64336775-1431ad00-cfde-11e9-8b0e-79ff0a4132b3.png)

**Comment by ripcurlx** [comment]
## Cycle 5 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
## Cycle 6 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/369

**Comment by ripcurlx** [comment]
![Monthly Report September 2019](https://user-images.githubusercontent.com/170962/66372843-5700ef00-e9a7-11e9-9e48-80167934da61.png)

**Comment by ifarnung** [comment]
Awesome content, thanks for the summary. Kind of a bummer month, but here's hoping things continue to grow long term!

**Comment by ripcurlx** [comment]
## Cycle 7 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

Monthly report for October will be posted today.

/cc https://github.com/bisq-network/compensation/issues/401

**Comment by ripcurlx** [comment]
![Monthly Report October](https://user-images.githubusercontent.com/170962/68653543-41de2980-052c-11ea-9bde-54282d67fbe8.png)

**Comment by ripcurlx** [comment]
## Cycle 8 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

Monthly report for November will be posted today.

/cc https://github.com/bisq-network/compensation/issues/439

**Comment by ripcurlx** [comment]
![Monthly Report November 2019](https://user-images.githubusercontent.com/170962/71163700-ecddb380-224d-11ea-97e5-2094626c69e2.png)

**Comment by ripcurlx** [comment]
## Cycle 9 report

### Google Analytics
Monitoring of metrics to react to certain issues. 

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary.

General moderation of #analytics channel.

Monthly report for December will be posted today.

/cc https://github.com/bisq-network/compensation/issues/466

**Comment by ripcurlx** [comment]
## Cycle 10 report

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. I'll try to add some automations so my efforts for this will trend towards zero. At the moment I'm checking the sheet every day and found out two times issues with the markets API.

General moderation of #analytics channel.

I won't post any visual reports anymore as we don't want to use it right now for communication and only is partly a duplication what is available on the [website](https://bisq.network/stats/) anyways.

/cc https://github.com/bisq-network/compensation/issues/493

**Comment by ripcurlx** [comment]
## Cycle 11 report

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Still plan to add automations so my efforts for this will trend towards zero. At the moment I'm continuing to check the sheet every day.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/499

**Comment by ripcurlx** [comment]
## Cycle 12 report

### [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090)
Updated sheets where necessary. Although I'm checking the trade performance every day and detected an issue with the Markets API by that, I'm not sure this is still a role that needs to be fulfilled. So I plan to shutdown this role by next cycle. It would also force me to finally automate the last parts of the reporting spreadsheet.

General moderation of #analytics channel.

/cc https://github.com/bisq-network/compensation/issues/542

**Comment by ripcurlx** [comment]
As mentioned in my last report I won't file any more compensation requests and stop reporting for this role as there is no relevant work to be done atm.

**Comment by cbeams** [comment]
Closing as dropped per @ripcurlx's comments above.
