### ISSUE TITLE
Facebook Admin

### ISSUE THREAD

**Issue by csacher** [bisq-network/roles#48]
This role is responsible for the Bisq Facebook page at https://facebook.com/bisqnetwork.

**Comment by cbeams** [comment]
@ManfredKarrer, please transfer admin rights for the Bitsquare Facebook page to @csacher, such that he can take full control of it.

**Comment by ManfredKarrer** [comment]
@csacher What is your FB handle? 
Not sure if the url and name can be changed in FB. https://www.facebook.com/bitsquareexchange
If not feel free to just set up a new page.

**Comment by cbeams** [comment]
I've unassigned @ManfredKarrer from this issue, as @csacher is now fully set up to man the helm of our new Facebook page at https://www.facebook.com/bisqnetwork.

@csacher, please leave monthly reports here on this issue, with whatever stats and information you think are relevant, and provide a link to those updates in your compensation requests. These can be as brief or detailed as you like.

For an example of what these monthly updates can look like, see the latest update for the Twitter Admin role at https://github.com/bisq-network/roles/issues/21#issuecomment-362125076.

Thanks again for your contributions here—it's great to know Bisq will have a quality presence on Facebook now.

**Comment by csacher** [comment]
Facebook handle has been updated regularly sourcing information from twitter.com/bisq_network

Insights:
![bildschirmfoto 2018-04-14 um 19 05 44](https://user-images.githubusercontent.com/34270328/38768009-e2c3b586-4016-11e8-91db-79230daa5788.JPG)
![bildschirmfoto 2018-04-14 um 19 05 31](https://user-images.githubusercontent.com/34270328/38768010-e305bcce-4016-11e8-9eea-c48b87f318cb.JPG)
![bildschirmfoto 2018-04-14 um 19 04 58](https://user-images.githubusercontent.com/34270328/38768011-e33dea40-4016-11e8-8733-27387aa9a9ef.JPG)
![bildschirmfoto 2018-04-14 um 19 04 10](https://user-images.githubusercontent.com/34270328/38768012-e374c966-4016-11e8-9983-6ef1bbf93f38.JPG)

**Comment by cbeams** [comment]
Thanks, @csacher! Please consider [submitting a compensation request](https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation) next month.

**Comment by goo-technology** [comment]
There's any reason for have the Bisq Facebook page unattended?

**Comment by m52go** [comment]
@goo-technology my guess is that it's a channel most contributors don't use very much, and we don't expect to find users on there either given the anti-privacy nature of Facebook. Just my guess though, maybe others who know more can chime in.

**Comment by huey735** [comment]
@m52go despite that, 'facebookers' are probably one of the core beneficentes of Bisq. People who haven't entered the central exchanges databases yet. Also, Facebook is very popular still and there loads of people who use it as their whole internet.

**Comment by goo-technology** [comment]
@m52go well, at least in México there a lot of traders in facebook groups releated to trading bitcoin. I believe that with a correct administration of the Facebook page, a good number of new traders could be attracted.

**Comment by ghost** [comment]
For my part, I would by far prefer attracting solid users to Bisq.
So, if some marketing effort is too provide, I would prefer to orient it on users sharing privacy values and a bit technical minded.
Attracting poorly skilled users = more support + more scams + more reimbursements.
We have to be careful with Bisq ecosystem. atm it works.

**Comment by goo-technology** [comment]
@HarryMacfinned saying poorly skilled users you mean without skills using Bisq o without trading skills?

**Comment by ghost** [comment]
I mean privacy skills. Which implies in turn some technical skills.
I mean that I would prefer people from the linux world than from the windows world.
And for what I know linux users are not so much on FB, while 99% of FB users are on windows.

So, if marketing, then marketing on the right (coherent) target.

The stats say that 1 BTC on 2 was stolen at a given moment.
If Bisq gets such stats, I wonder how we could manage it ?

**Comment by huey735** [comment]
I disagree @HarryMacfinned. I think there way more people that could benefit from Bisq that are not privacy literate. And Bisq could be a way for them to learn more.
I do share your view that a flood of noobs could damage Bisq'a perception. Their mistakes would be marketed as Bisq's flaws. But I don't think that the solution is to shy away from it.

**Comment by ManfredKarrer** [comment]
I agree that despite Facebook is of course terrible from all aspects there are regions where many less technical people or communities are still very much locked in to FB.

**Comment by goo-technology** [comment]
Well, if there is a need for someone to help maintain the Facebook page, you can count on me.  Perhaps with information focused on a certain profile of users and simply so that it does not leave an image of abandonment.

**Comment by AgataBPL** [comment]
I've done a lot of e-marketing via Facebook. It works much better if you create a group connected to the fan page. Let me know if I can help.

**Comment by goo-technology** [comment]
I started a group for México, it's not linked to the Bisq Facebook page but anyway is growing: https://www.facebook.com/groups/bisqmexico/

**Comment by cbeams** [comment]
Closing as dropped due to inactivity. If Bisq is to have any kind of compensated Facebook presence, it should probably be handled under the new Community Manager role at #95.

/cc @m52go (but no further action required as far as I'm concerned).
