### ISSUE TITLE
Pricenode Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#5]
Docs: 
Team: @bisq-network/pricenode-maintainers 
Primary owner: @wiz

**Comment by cbeams** [comment]
## 2018.01 report

As I mentioned in this month's Exchange Maintainer update at https://github.com/bisq-network/roles/issues/3#issuecomment-362110355, we removed the old `provider` module from the bisq-network/exchange repository and created the new https://github.com/bisq-network/pricenode repository to replace it.

I'm still working on some refactoring there, and there is a lot we can do to make this simple service better in a variety of ways, but for the moment, we just want to get all the existing pricenodes upgraded successfully to be based on the code in the new repo. We can take next steps from there. See bisq-network/pricenode#2 and bisq-network/pricenode#4 for details.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

I spent a lot of time this month on refactoring the newly-extracted pricenode at bisq-network/pricenode#7. It is up and running now as my own pricenode, but the PR itself has not yet been merged, and thus other operators have not updated to it. Therefore, **I'm not going to ask for compensation for this work this month, given that it is not finished work.** I'll include it next month.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

See my comments in the Pricenode Operator role at https://github.com/bisq-network/roles/issues/14#issuecomment-378524487.

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

@cbeams completed the pricenode refactoring at bisq-network/bisq-pricenode#7, and it has been merged, but not all @bisq-network/pricenode-operators have upgraded yet.

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
## 2018.05 report

There were no changes to bisq-pricenode this month, but I believe I am still the only operator who has upgraded to the latest, fully refactored version.

@bisq-network/pricenode-operators, please make it a priority to upgrade this coming month, and let me know (#pricenode in Slack) if you need help.

Also, @bisq-network/pricenode-operators, when you add your monthly report comment to https://github.com/bisq-network/roles/issues/14, please copy the format I used at https://github.com/bisq-network/roles/issues/14#issuecomment-393202362, such that you include hosting provider info, cost and version you're running, thanks.

/cc bisq-network/compensation#74

**Comment by mrosseel** [comment]
## 2018.06 report

* all operators have switched to the 0.7.1-SNAPSHOT release
* updated docker image to be compatible with the latest version
* fixed bug where the startup params were wrong for the docker file

All nodes are running the latest version with the same params, nothing further to report.

/cc bisq-network/compensation#83

**Comment by cbeams** [comment]
## 2018.07 report

Nothing to report.

**BSQ requested:** `25`

/cc bisq-network/compensation#101

**Comment by cbeams** [comment]
## 2018.08 report

Nothing to report.

**BSQ requested:** `25`

/cc bisq-network/compensation#114

**Comment by cbeams** [comment]
## 2018.10 report

Nothing to report.

BSQ Requested: `25`

/cc bisq-network/compensation#160

**Comment by cbeams** [comment]
## 2018.11 report

Nothing to report.

BSQ requested: `25`

/cc bisq-network/compensation#179

**Comment by cbeams** [comment]
## 2018.11 report (cont)

Actually, I'm closing this role now, given that the pricenode code has been merged back into the main bisq-network/bisq repository. I have listed myself in the CODEOWNERS file there as being responsible for the pricenode module, and it is therefore probably no longer worth doing a monthly update here. We'll keep the pricenode operator role at #14 intact, though, as the individual pricenode instances are still run by different operators across different hosting environments.

**Comment by wiz** [comment]
I think we need to bring back the pricenode maintainer role. Currently due to the lack of an active maintainer we have the following issues:
1) The active pricenodes seem to be unmaintained and [running different versions of Bisq](https://github.com/bisq-network/roles/issues/10#issuecomment-542153534)
2) The [elephant in the room](https://github.com/bisq-network/bisq/issues/1074) of BitcoinAverage being a trusted third party and CPOF for Bisq
3) We need someone responsible to investigate [issues like this when prices are way off](https://github.com/bisq-network/bisq/issues/3337)

If nobody objects I'd like to bring back this role and start working on these issues.

**Comment by cbeams** [comment]
No objection fron my side, @wiz, and I’d be happy to field any questions.

**Comment by bodymindarts** [comment]
IMO a better approach would be to remove the price nodes outright. I don't see what value it is adding. They are a centralized SPOF. Clients could just as well reach out to the third parties directly themselves to get the up to date prices. It reduce complexity and improve decentralization.

(EDIT) - Ignore this... I didn't realize that the API we call out to from the price nodes to get the price for the various markets requires a paid-for API key. This means each node would need their own api key if following the current solution.

**Comment by wiz** [comment]
## Cycle 9 report

* BitcoinAverage has changed its pricing plans, and the old $10/month plan will no longer allow us to access the API endpoints that Bisq pricenode uses. All @bisq-network/pricenode-operators must [upgrade to the "startup" plan which costs $60/month](https://bitcoinaverage.com/en/plans) when their current plan expires

* I have begun researching alternative data providers to add into the pricenode and https://www.coinapi.io/ looks interesting so far - perhaps we can add it as a secondary provider and create some kind of weighted index to average the 2 data providers together. We must consider how to avoid price discrepancies between the price nodes, and monitoring will become critical.

**Comment by Svisstack** [comment]
CoinAPI here. Discussing this with @wiz over the email. If you have any questions then let me know.

**Comment by seknokdkk** [comment]
> which costs $60/month 
Correction: $49/month. Consider Bisq in the startup phase now, not a developer.

**Comment by cbeams** [comment]
@wiz wrote:

> I think we need to bring back the pricenode maintainer role.

@cbeams responded:
> No objection fron my side

I responded too hastily on this. We really should drop the Pricenode Maintainer role altogether (again), because the notion of "maintainer" in our definition is really about maintaining code, i.e. being a maintainer of a GitHub repository, responsible for merging PRs, as described at http://docs.bisq.network/roles.html#maintainer.

The need that @wiz was talking about here is just that someone needs to take initiative to make sure that all pricenodes are in order. @wiz, in his role as ops team lead is the right person to own this by default anyway, so all is well.

So I'm closing this once again as dropped.

**Comment by wiz** [comment]
@cbeams I propose to re-open and assign the role to @cd2357 who has recently worked on the pricenode code the most, he is the best person to maintain the exchanges, assets, etc.

**Comment by Svisstack** [comment]
Let me know if you need anything from CoinAPI.

**Comment by cd2357** [comment]
Unfortunately time is limited, so I can't take this role in the near future.
