### ISSUE TITLE
Establish README.adoc for repository guidance

### ISSUE THREAD

**Issue by csacher** [bisq-network/roles#53]
README: https://github.com/bisq-network/roles/blob/master/README.adoc

The README.adoc should help navigating through the repository, give an overview over all the bonded roles within the dao and guide the process of role creation. Furthermore it will help facilitate the process of compensation.

**Comment by cbeams** [comment]
Closing as complete. @csacher and I got a README in place a while ago, and just forgot to close this issue when we did.
