### ISSUE TITLE
Add "role specification" as requirement for bonded roles in phase-zero.adoc

### ISSUE THREAD

**Issue by csacher** [bisq-network/roles#54]
phase-zero.adoc: https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc

In order to ensure the role specification completion of all assigned roles I will add it as a requirement in the phase zero document.

**Comment by cbeams** [comment]
@csacher, I believe this is a duplicate of bisq-network/docs#19, yeah? I'll close on your confirmation.

**Comment by cbeams** [comment]
Your title was better than mine, though :)

**Comment by cbeams** [comment]
Closing as duplicated by bisq-network/docs#19 per https://github.com/bisq-network/roles/issues/54#issuecomment-350963324.
