### ISSUE TITLE
Keybase Admin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#60]
Closed as superseded by #79.

**Comment by cbeams** [comment]
## 2017.12 report

I set up the `bisq` team on Keybase when they announced teams a couple months ago, just to reserve the name. New features rolled out this month that made it possible to mark teams as 'open' for anyone to join, and so I change that setting on our team and tweeted about it at https://twitter.com/bisq_network/status/947035060989054980.

We now have 10 members in the team, but no real activity yet. We'll see where this goes.

/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
## 2018.01 report

Our `bisq` team on Keybase actually started to get some traffic this month, but most of the conversation was off topic, and a lot of it was about BCH. I didn't moderate it at all; just answered people's questions if they had them, and let the conversation go where it may. Figured I might learn something in the process, and since I'm not sure what role if any Keybase will play for us, it seems prudent to just sit back for a bit and see what happens there.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

Nothing to report.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

Nothing to report.

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.05 report

Nothing to report.

/cc bisq-network/compensation#74

**Comment by cbeams** [comment]
## 2018.06 report

Final report (for now). I'm closing this issue as no one is using the Keybase `bisq` team. I will continue to have administrative rights there, and if the Keybase team picks up in activity, or someone else wants to take ownership there, we can re-open this role then.

/cc bisq-network/compensation#89

**Comment by m52go** [comment]
Reopening as the Keybase group is now seeing more activity.

**Comment by wiz** [comment]
## Cycle 7 report

The Bisq team has been restarted, and the community has mostly migrated from Slack to Keybase for the security and privacy it provides. I've taken over the Keybase Admin role together with @m52go, and we are gaining more users every day. Keybase is great!

/cc [bisq-network/compensation#398](https://github.com/bisq-network/compensation/issues/398)

**Comment by cbeams** [comment]
## Cycle 12 update

I've removed @m52go as an assignee here as he does not in fact have admin status in Keybase, and added myself as I'm the owner of the team. @wiz remains assigned as he's an admin.

/cc bisq-network/compensation#533

**Comment by wiz** [comment]
@cbeams actually if you check https://github.com/bisq-network/proposals/issues/128 you can see @m52go was assigned secondary keybase admin role with me... but if you really want to fire him, we can do that too! :fire:

**Comment by cbeams** [comment]
Yeah, this was my bad. @m52go pinged me about it as well. I've re-added him to @bisq-network/keybase-admins and re-assigned him here. Sorry, Steve.

**Comment by cbeams** [comment]
Closing as superseded by the new Keybase Admin role at #79 (formerly Rocket Chat Admin, see https://github.com/bisq-network/roles/issues/79#issuecomment-618459741 for details why it was necessary to do this).
