### ISSUE TITLE
Events Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#65]
This role is responsible for maintaining the Bisq Events Google calendar at https://bisq.network/events, as well as the issues-only https://github.com/bisq-network/events repository.

It would also be ideal for this role to be responsible for "looking out" for events and conferences that Bisq can / should have a presence at, letting the team know, being proactive about coordinating these activities, etc.

Team: @bisq-network/events-maintainers 
Primary: @ManfredKarrer (would like to hand over role)
Secondary: @ripcurlx (would like to hand over role)

**Comment by cbeams** [comment]
## 2018.01 report

I created this role this month primarily because I created the bisq-network/events repository so that we'd have a place to plan upcoming conferences like FOSDEM 2018 (bisq-network/events#9). At that same time, I retroactively created a number of issues for events we've already done like 34C3 in December (bisq-network/events#7), so folks would have a sense of what the repository is supposed to be all about, and also so that there's a permanent record of all that work we did.

What would be really great is to have someone take on this role and get way ahead of events, start being proactive about it, figuring out where we want to have Bisq represented, who's going to go, getting materials together (e.g. stickers etc). An events manager / maintainer for Bisq would be an amazingly useful addition to the team. In the meantime, I'll just try to "keep the lights on", but let me know if you're interested in doing this kind of work.

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

### Conferences and meetups

 - @mrosseel promoted Bisq at FOSDEM: https://github.com/bisq-network/events/issues/9
 - @meapistol and @remyers presented Bisq at the Malmö Bitcoin Users Meetup: https://github.com/bisq-network/events/issues/12
 - @csacher presented on Bisq at Bitcoin Cambodia / Penom Penh: https://github.com/bisq-network/events/issues/13

### Interviews

 - Part I of @cbeams' podcast interview with Steal This Show dropped this month: https://github.com/bisq-network/events/issues/10
 - @cbeams' written interview with Forklog came out: https://github.com/bisq-network/events/issues/11
 - @cbeams' written interview with Bitcoin Magazine came out: https://github.com/bisq-network/events/issues/14

> _NOTE: I'm still not sure where the best repo/board for these issues is. They're not quite "events", and we don't have a repo for "ambassador" issues. Maybe we should. In the meantime, I'll duplicate the above entries in my report this month on the Ambassador role (#35)._

### YouTube live streams

 - 4 weekly growth calls:
   - https://github.com/bisq-network/growth/issues/35
   - https://github.com/bisq-network/growth/issues/37
   - https://github.com/bisq-network/growth/issues/38
   - https://github.com/bisq-network/growth/issues/39
 - Security Deposit Q&A: https://github.com/bisq-network/events/issues/17
 - Account Age Witness Q&A: https://github.com/bisq-network/events/issues/18
 - USD liquidity week kickoff: https://github.com/bisq-network/events/issues/15
 - Live demo: How to buy BTC for USD using Bisq and Cash App: https://github.com/bisq-network/events/issues/16

### Calendar

From https://bisq.network/calendar:

![image](https://user-images.githubusercontent.com/301810/36814287-6108c728-1cd7-11e8-8994-d22fe05554f4.png)

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

### Conferences and meetups

None this month.

### Interviews

I am moving interviews and podcasts to the Ambassador (#35) role going forward.

### YouTube live streams

@ripcurlx is covering these now in the YouTube Admin role (#56)

### Calendar

From https://bisq.network/calendar:

![image](https://user-images.githubusercontent.com/301810/38263070-5275a084-376f-11e8-92ed-cbe29e77b58b.png)

/cc bisq-network/compensation#57

**Comment by dsbeasley** [comment]
I'd be more than happy to take on this role and promote Bisq!

**Comment by cbeams** [comment]
## 2018.04 report

### Conferences and meetups

None this month.

@cbeams submitted a talk for HCPP18 in October: https://github.com/bisq-network/events/issues/21

### Meetings and live streams

 - @ripcurlx held 4 regular weekly growth calls
 - @ManfredKarrer and @cbeams did Bisq Tech Sessions 3 and 4

### Calendar

From https://bisq.network/calendar:

![image](https://user-images.githubusercontent.com/301810/39575489-030084fa-4edb-11e8-9ca7-910320817579.png)

/cc bisq-network/compensation#68

**Comment by cbeams** [comment]
## 2018.05 report

@cbeams talk at HCPP18 was accepted, but is now seeing whether he he can deliver it remotely. See https://github.com/bisq-network/events/issues/21.

Podcast with @ManfredKarrer, @jwweatherman and Anders Kargaard on "Equity Tokens, DAOs and the future of companies" at https://github.com/bisq-network/events/issues/26

@ripcurlx did 2 growth calls (3 with the call happening tomorrow the 31st)

From https://bisq.network/calendar:

![image](https://user-images.githubusercontent.com/301810/40732710-2c30d9f6-6434-11e8-903d-20cad69e2ff0.png)

/cc bisq-network/compensation#74

**Comment by ManfredKarrer** [comment]
## 2018.06 report

I took over primary role ownership that month.

- @ripcurlx did 4 growth calls
- @flix1 did his first growth call

We want to change a bit the format of the growth calls to a more open one, maybe with invited guests discussing topics related to Bisq. 

From https://bisq.network/calendar:
<img width="1076" alt="screen shot 2018-06-30 at 17 38 08" src="https://user-images.githubusercontent.com/1449498/42126720-6617b6ec-7c8c-11e8-80fb-38d267da65dd.png">

/cc bisq-network/compensation#92

**Comment by ManfredKarrer** [comment]
## 2018.07 report
We had 3 growth calls and one dev session that month.

From https://bisq.network/calendar:
<img width="977" alt="screen shot 2018-07-26 at 18 19 02" src="https://user-images.githubusercontent.com/1449498/43274810-797e190a-9100-11e8-98f9-888ec46a66b6.png">

/cc bisq-network/compensation#93

**Comment by ManfredKarrer** [comment]
## 2018.08 report

We had 4 growth calls that month.

From https://bisq.network/calendar:
<img width="1107" alt="screen shot 2018-08-30 at 23 47 55" src="https://user-images.githubusercontent.com/1449498/44881227-297b4980-acaf-11e8-9b6a-484b24a2cba2.png">


/cc bisq-network/compensation#112

**Comment by ManfredKarrer** [comment]
## 2018.09 report

We had 4 growth calls that month.

From https://bisq.network/calendar:
<img width="1114" alt="screen shot 2018-09-26 at 20 26 20" src="https://user-images.githubusercontent.com/1449498/46118099-7b3dc380-c1ca-11e8-88c0-7a639993e2ed.png">

/cc bisq-network/compensation#125

**Comment by ManfredKarrer** [comment]
## 2018.10 report

We had  4 growth calls and several interviews.

/cc bisq-network/compensation#155

**Comment by ManfredKarrer** [comment]
## 2018.11 report

We had only 2 growth calls that months as we tried to stay focussed on the release.

/cc bisq-network/compensation#180

**Comment by ManfredKarrer** [comment]
## 2019.01 report

We had each week a growth call that month as well as a dev call. 

/cc bisq-network/compensation#205

**Comment by ManfredKarrer** [comment]
## 2019.02 report

We had mostly each week a growth call (beside in the release week) that month as well as a dev call.

/cc bisq-network/compensation#227

**Comment by ManfredKarrer** [comment]
@HarryMacfinned  Would you be ok to take that over?

**Comment by ManfredKarrer** [comment]
## 2019.03 report

We had each week a growth call as well as a dev call.

/cc bisq-network/compensation#252

**Comment by ManfredKarrer** [comment]
I close that role as it is not much maintained. If anyone wants to become active with that role feel free to re-open.
