### ISSUE TITLE
Data architect, Database Administrator, SQL Developer

### ISSUE THREAD

**Issue by zero000** [bisq-network/roles#69]
Core skill based on SQL Server (over 15 years) and MySQL . Business Intelligence. In addition to contract work running several personal software development projects, managing remote teams of freelancers, acting as a sponsor and PM

**Comment by cbeams** [comment]
Thanks, @zero000. For posterity, here's the chat we just had about this in Slack at https://bisq.slack.com/archives/C0336TYTG/p1516101556000045:

![image](https://user-images.githubusercontent.com/301810/34987286-eb62de20-faba-11e7-8692-378d0726d8b6.png)

Like I mentioned there, I'm going to close this issue, as we don't have any need to fill such a role right now, but the offer is appreciated, and if ever we reopen this, you'll be the first to know!

**Comment by cbeams** [comment]
Closing as not needed.
