### ISSUE TITLE
Statsnode Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#7]
Docs: none
Team: @bisq-network/statsnode-maintainers 
Primary owner: @ManfredKarrer 

I dropped that role as it can be seen as part of the general code base.

**Comment by ManfredKarrer** [comment]
## 2018.04 report
There have been some bigger refactoring of the startup process which also affected the stats node.

**Comment by ManfredKarrer** [comment]
The maintainer role not really atm, that is about the Github maintenance. Once a developer has worked more on that and has earned reputation and trust we can move over the maintainer role as well.
The operator role though would be open and it is about operating the server for the https://markets.bisq.network/ page which includes running the stats node jar file there. 
See: https://github.com/bisq-network/roles/issues/9

**Comment by ghost** [comment]
Thanks Manfred, I'll look at the provided links.

**Comment by ManfredKarrer** [comment]
## 2018.05 report
Nothing to report

**Comment by ManfredKarrer** [comment]
## 2018.06 report

The have been some code changes related to the startup code refactoring.

**Comment by ManfredKarrer** [comment]
## 2018.07 report

Nothing to report.

/cc bisq-network/compensation#93

**Comment by ManfredKarrer** [comment]
## 2018.08 report

Nothing to report.

/cc bisq-network/compensation#112

**Comment by ManfredKarrer** [comment]
## 2018.09 report

Nothing to report.

/cc bisq-network/compensation#125

**Comment by ManfredKarrer** [comment]
## 2018.11 report

Nothing to report.

/cc bisq-network/compensation#180

**Comment by ManfredKarrer** [comment]
## 2019.01 report

Nothing to report.

/cc bisq-network/compensation#205

**Comment by ManfredKarrer** [comment]
## 2019.02 report

Nothing to report.

/cc bisq-network/compensation#227

**Comment by ManfredKarrer** [comment]
I think we can close that role as there is nearly no extra work included here and it can be seen as part of the general code base.
