### ISSUE TITLE
Onboarding and Marketing

### ISSUE THREAD

**Issue by roghato** [bisq-network/roles#70]
We need to lower the barrier entry into Bisq. We should consider device clear marketing strategy to enable mass adoption. From ZERO to HERO, we should Develop an Onboarding Program to help educate and raise awareness for the new users. I suggest that we should have a stronger social media presence to facilitate more agile and flexible space for all users to interact and collaborate effectively. BIsq is a beautiful solution for the bottleneck problems of centralized exchanges and the on-ramp/off r-ramp crypto/Fiat exchange.

**Comment by cbeams** [comment]
Closing as invalid. @rajahat, thanks for your suggestion, but adding an issue here in the roles repository isn't the right place for it. The issues here represent well-defined roles under the Bisq DAO that are responsible for specific infrastructure and duties. What you're suggesting here needs more discussion prior to showing up here as a role per se. I'd suggest joining us in Slack and discussing your ideas, catching up on existing efforts around onboarding and awareness-raising, and then you can see what makes the most sense from there. Also, please read the https://docs.bisq.network/contributor-checklist.html doc if you haven't already.
