### ISSUE TITLE
Bisq Design Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#75]
Docs: 
Team: @bisq-network/design-maintainers 
Primary owner: @pedromvpg

**Comment by ripcurlx** [comment]
## 2018.07 report
Nothing to report.

/cc bisq-network/compensation#98

**Comment by ripcurlx** [comment]
## 2018.08 report
Nothing to report.

/cc bisq-network/compensation#109

**Comment by ripcurlx** [comment]
## 2018.09 report
Nothing to report.

/cc bisq-network/compensation#126

**Comment by ripcurlx** [comment]
## 2018.10 report
Nothing to report.

/cc bisq-network/compensation#148

**Comment by ripcurlx** [comment]
## 2018.11 report
Nothing to report.

/cc bisq-network/compensation#177

**Comment by ripcurlx** [comment]
## 2018.12 report
Nothing to report.

/cc bisq-network/compensation#195

**Comment by ripcurlx** [comment]
## 2019.01 report
Nothing to report.

/cc bisq-network/compensation#206

**Comment by ripcurlx** [comment]
## 2019.02 report
Nothing to report.

/cc bisq-network/compensation#224

**Comment by ripcurlx** [comment]
## 2019.03 report
Nothing to report.

/cc bisq-network/compensation#247

**Comment by ripcurlx** [comment]
## 2019.04 report
Nothing to report.

/cc bisq-network/compensation#269

**Comment by ripcurlx** [comment]
## Cycle 2 report
Nothing to report.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
## Cycle 3 report
Nothing to report.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
## Cycle 4 report
Nothing to report.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
## Cycle 6 report
Nothing to report.

/cc https://github.com/bisq-network/compensation/issues/369

**Comment by ripcurlx** [comment]
## Cycle 7 report
Nothing to report.

/cc https://github.com/bisq-network/compensation/issues/401

**Comment by ripcurlx** [comment]
## Cycle 8 report
Nothing to report.

As there is hardly any activity for this role, I'll stop reporting and asking for compensation from now on.

/cc https://github.com/bisq-network/compensation/issues/439

**Comment by cbeams** [comment]
Closing as dropped. Maintaining the bisq-network/design repository is something that can be handled on an as-needed basis by the GitHub Admin role, given that there's very little activity there.

**Comment by cbeams** [comment]
I've also deleted the now-obsolete @bisq-network/design-maintainers team.

**Comment by wiz** [comment]
@cbeams I propose to re-open this role and assign it to @pedromvpg who is essentially the bisq design maintainer now

**Comment by cbeams** [comment]
@wiz wrote: 

> I propose to re-open this role and assign it to @pedromvpg who is essentially the bisq design maintainer now

I would be fine with that, but I'd like to hear directly from @pedromvpg that this is what he wants as well. I don't think he's gotten or responded much to GitHub notifications in the past. Having the role open means at a minimum that Pedro would post cycle updates here, and I'm not sure that he's up for that. If so, great!

Note that I did in any case recently grant Pedro access to the bisq-network/design repository (also at @wiz's request).

**Comment by pedromvpg** [comment]
I'm available to take on the role of design maintainer and to report on design issue for each cycle.

I would just ask that if I don't respond to the mentions on here, that contributors try me on keybase.

I can also organize the desig. Repo and start archiving all past design materials on there.

**Comment by cbeams** [comment]
> I'm available to take on the role of design maintainer

Great, thanks @pedromvpg! I've re-created the @bisq-network/design-maintainers team, added you and @ripcurlx to it, assigned you to this issue and noted you're the primary for the role in the description.

**Comment by pedromvpg** [comment]
Thank you!

**Comment by pedromvpg** [comment]
# Cycle 20 report

Growth design materials:
bisq-network/compensation#752

@Jakub-CZ working "buy BSQ" CTA on the "Create offer" screen
bisq-network/bisq/issues/4579

2021 goal of addressing confusion of the use of Create-New-Offer button by pointed out @deusmax
bisq-network/bisq/issues/4934

Make another push to clarify and enhance account signature tooltip
bisq-network/bisq/issues/4416

Planning call with @pazza83 in the beginning of 2021 to define a procedure for future design work, file and asset sharing, software and process.
