### ISSUE TITLE
Arch Linux AUR maintainer

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/roles#78]
The Arch Linux distibution builds all applications from source code and use the AUR format for delivering build instructions. 
See: https://aur.archlinux.org/packages/bisq/

Primary role owner: @freimair (is maintainer of that AUR repository)

**Comment by freimair** [comment]
actually, there are three version of bisq in AUR:

- build from source, latest master: https://aur.archlinux.org/packages/bisq-git/
- build from source, latest release tag: https://aur.archlinux.org/packages/bisq/
- build from latest .deb release: https://aur.archlinux.org/packages/bisq-bin/

**Comment by ManfredKarrer** [comment]
Can you consolidate those?

**Comment by freimair** [comment]
Each of these have their place in the AUR (it is the Arch linux way, kind of). The interested user can either have a quick install (without the need for compilation, borrowed from a binary release), a stable install (built from release tag) or a cutting edge install (built from master).

What characteristics do you suggest for a consolidated package?

**Comment by ManfredKarrer** [comment]
Ah, ok.

**Comment by freimair** [comment]
## 2018.11 report

- The [0.8.1 release](https://github.com/bisq-network/bisq/releases/tag/v0.8.1) stirred things up a bit. No harm has been done to the `bin` package. A simple version change did the trick. The `git` package does not care about releases anyways. However, I could not figure out how to build bisq 0.8.1 from source. I checked with @ripcurlx: the recent "moving repos around" shaked up the build process and building 0.8.1 from source is "tricky". I decided to leave the package out of date until 0.9 comes along.
- The `git` package somehow still used the deprecated repo bisq-desktop. Fixed it. And ran straight into:
- The `git` package got thrown out of line when the location of the binaries had been changed. It took me some time to find the issue and fix the package. I also suggested a fix to the issue in bisq-network/bisq#1979 as I already found the cause.

/cc bisq-network/compensation#166

**Comment by freimair** [comment]
## 2018.12 report

- moved the packages first to 0.9.0 then to 0.9.1
- did some optimizations along the way
- nothing special

/cc https://github.com/bisq-network/compensation/issues/185

**Comment by freimair** [comment]
## 2019.01 report

- updated to 0.9.3
- skipped 0.9.2 due to work-life-balance-nonsense
- issues with Gnome on Wayland keep showing up. However, we are not the only ones affected:
  - https://github.com/javafxports/openjdk-jfx/issues/175
  - https://bugs.openjdk.java.net/browse/JDK-8172142
  - https://bugs.openjdk.java.net/browse/JDK-8170519
  - https://github.com/dmolony/Xmit/issues/2
  - ...

lets see how things evolve.

**Comment by freimair** [comment]
# 2019.02 report
- updated to 0.9.4

nothing new on the Wayland front

**Comment by freimair** [comment]
# 2019.03 report

- ad Wayland: a [fix](https://github.com/javafxports/openjdk-jfx/pull/199) has been proposed a while ago. However, it has been rejected. However, if the issue is encountered, a simple `-Djdk.gtk.version=2` might just do the trick (at least it does for me)
- updated bisq and bisq-bin to 0.9.5

**Comment by freimair** [comment]
# 2019.05 report
- updated bisq and bisq-bin to 1.1.2

**Comment by freimair** [comment]
# 2019.06 report

- nothing to report

**Comment by freimair** [comment]
# 2019.07 report

- updated bisq and bisq-bin to 1.1.3
- updated bisq and bisq-bin to 1.1.4
- updated bisq and bisq-bin to 1.1.5
- added checksums

**Comment by freimair** [comment]
# 2019.09 report
- updated bisq and bisq-bin to 1.1.6
- updated bisq and bisq-bin to 1.1.7

**Comment by freimair** [comment]
# 2019.10 report

- updated bisq and bisq-bin to 1.2.1
- updated bisq and bisq-bin to 1.2.2
- updated bisq and bisq-bin to 1.2.3

**Comment by freimair** [comment]
# Cycle 8 Report

- updated bisq and bisq-bin to 1.2.4

**Comment by freimair** [comment]
# Cycle 10 report

- updated bisq and bisq-bin to 1.2.5

**Comment by freimair** [comment]
# Cycle 11 report

- updated bisq and bisq-bin to 1.2.6
- updated bisq and bisq-bin to 1.2.7

**Comment by freimair** [comment]
# Cycle 12 report

- updated bisq and bisq-bin to 1.2.8
- updated bisq and bisq-bin to 1.2.9
- updated bisq and bisq-bin to 1.3.0
- updated bisq and bisq-bin to 1.3.1

**Comment by freimair** [comment]
# Cycle 13 report

- updated bisq and bisq-bin to 1.3.2
- skipped 1.3.3 because it has only been pre-released.
- updated bisq and bisq-bin to 1.3.4

**Comment by freimair** [comment]
# Cycle 14 report

- updated bisq to use jdk-11-openjdk, because Arch Linux no longer provides a reasonable source for jdk-10-openjdk
- marked bisq-git to be deleted
- git-lfs does not go with downloading source tarballs. Hence, reverted package "bisq" to use git clone. However, to prevent clients from downloading the whole 400MB of data, I threw in a "--depth=1" to the clone command. Downloaded data size is now approx. 100MB (=20MB src + 80MB data stores).

**Comment by freimair** [comment]
# Cycle 15 report

- updated bisq and bisq-bin to 1.3.6

**Comment by freimair** [comment]
# Cycle 17 report
- updated bisq and bisq-bin to 1.3.9

**Comment by freimair** [comment]
# Cycle 18 report

- since no releases have been made, nothing was updated

**Comment by freimair** [comment]
# Cycle 19 report
- updated bisq and bisq-bin to 1.4.2
- adjusted runtime jdk for these releases as there is no more jdk11 for arch linux
- updated bisq and bisq-bin to 1.5.0

**Comment by freimair** [comment]
# Cycle 20 report

- updated bisq and bisq-bin to 1.5.1
- updated bisq and bisq-bin to 1.5.2

**Comment by freimair** [comment]
# Cycle 21 report

- updated bisq and bisq-bin to 1.5.3
- updated bisq and bisq-bin to 1.5.4

**Comment by freimair** [comment]
# Cycle 22 report

- updated bisq and bisq-bin to 1.5.5
- moved "bisq" package to use the source tarball as it includes the binary files and a signature file is provided now (get rid of git in the installation process)
- updated bisq and bisq-bin to 1.5.6
- updated bisq and bisq-bin to 1.5.8

**Comment by freimair** [comment]
# Cycle 23 report
- updated bisq and bisq-bin to 1.5.9
- updated bisq and bisq-bin to 1.6.1
- updated bisq and bisq-bin to 1.6.2

**Comment by freimair** [comment]
# Cycle 24 report

- updated bisq and bisq-bin to 1.6.4, thereby cleaning the build process because the hack of getting a makeshift jdk10 (which has been removed from the Arch repositories a long time ago) for building and running is no longer needed

**Comment by freimair** [comment]
# Cycle 25 report

nothing happened

**Comment by freimair** [comment]
# Cycle 26 report
- updated bisq to 1.7.0 and introduced a build dependency for jdk11-openjdk
- updated bisq and bisq-bin to 1.7.1 pre and set build dependency and runtime to jdk11-openjdk

**Comment by freimair** [comment]
# Cycle 27 report
- updated bisq and bisq-bin to 1.7.2

**Comment by freimair** [comment]
# Cycle 28 report
- updated bisq and bisq-bin to 1.7.3

**Comment by freimair** [comment]
# Cycle 29 report

- updated bisq and bisq-bin to 1.7.4
