### ISSUE TITLE
Netlayer maintainer

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/roles#81]
Maintaining the https://github.com/JesusMcCloud/netlayer repository.

Even the repo is hosted and the code base was developed by @JesusMcCloud I suggest to use @freimair as primary role owner as he is an active developer in Bisq. 

Primary role owner: @freimair 
Seondary role owner: @JesusMcCloud

**Comment by freimair** [comment]
# 2019.03 report

- some tweaks and cleanup have been done to address file locking issues, timeouts, ...
- updated to tor 0.3.5.8

**Comment by freimair** [comment]
# 2019.04 report

- nothing to report

**Comment by freimair** [comment]
# 2019.05 report

- nothing to report

**Comment by freimair** [comment]
# 2019.06 report
- started thinking about next gen onion aka. HSv3

**Comment by freimair** [comment]
# Cycle 10

- HSv3 preparations are in progress
- the pressure on the netlayer stack increases - I am in the progress of sketching up a roadmap on how and when we can provide the love netlayer needs

**Comment by freimair** [comment]
# Cycle 11

- HSv3 preparations resulted in https://github.com/bisq-network/projects/issues/23
- maybe found the issue with the last release according to [this](https://github.com/bisq-network/bisq/pull/4028#issuecomment-596831321)

**Comment by freimair** [comment]
# Cycle 12

- nothing to report
