### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/roles#84]
# 2019.03 Report

There was an increase in activity in March. German and Portuguese translations are complete, with Russian and Spanish translations nearing completion.

New initiatives (WIP): standardized glossary across all languages.

![Transifex report pic March 2019](https://user-images.githubusercontent.com/43150241/55290737-6f73c980-53c6-11e9-95f1-43197a5850e5.png)

**Comment by ghost** [comment]
Hello @arunasurya , this repo is probably not the right place for your issue. ;-)

**Comment by arunasurya** [comment]
Ooops, thank for letting me know!
