### ISSUE TITLE
Blog Maintainer

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/roles#85]
It was made clear in [this issue](https://github.com/bisq-network/compensation/issues/261) that the Bisq blogging initiative was poorly defined in its goals and mechanisms when it was started sometime in March 2019.

After discussing some ideas between Steve Jain, Aruna Surya and myself, we now have a better idea of the what, why, and how of the Bisq blog.

### Why:

Blog topics were originally submitted in the Bisq growth repository and I think it speaks to its still-standing goals; to grow the Bisq network.

Without good communications and outreach, Bisq will be slow to adopt. A consistent blogging effort can bring in traffic through search engines, but can also help newcomers be welcomed to Bisq by having a consistent, educational, and friendly voice.

### What:

We propose that a new role be implemented titled “Blog Maintainer” and that this maintainer has certain duties (I will describe these responsibilities further below.)

That there be a **fixed budget** for writers per voting cycle. The amount is subject to change based on feedback but can start at **500 BSQ**.

That there be at least **two blog posts** (or however many the stakeholders prefer) written every voting cycle. Compensation will be divided among the writers from the allotted 500 BSQ and can vary per post.

- If the maintainer makes both posts, and deems them worth 250 each, then they earn 500. Full budget spent.
- If they deem their posts worth 100 each, then they earn 200, and 200 is the total amount spent on the blogging initiative that month.
- If they do 1 post worth 200, and someone else does another post worth 250, then each person received what they earn, and the total spent on blogging that month is 450.
- If one person does work worth 300 and another does work worth 300, then both posts cannot be merged in the same month, since the total of 600 would be higher than the budget of 500. Both posts can still be merged, if stakeholders want them, but they’d have to be merged in separate months. It’s up to the blog maintainer to make sure that the posts merged in a month respect the limits that stakeholders have set.
- Ideal scenario: Blog Maintainer does no writing, and both posts are written by other contributors. In this case, they could charge something symbolic for their role like 25 BSQ (which is the current convention).

### Duties-

The Blog Maintainer has the following duties:

1. Ensure two blogs (or however many stakeholders agree upon) are written and published every voting cycle.
2. Assign writers to topics.
3. Triage and label submitted topics.
4. To include a monthly report that consists of 

- Number of posts targeted per month
- Actual posts made that month
- Count of accepted post topic proposals (bounties)

### Rights-
The Blog Maintainer has write access to the new Blog Maintainer repository.

### Owners-
I am volunteering to pick up this role after discussing with the unofficial blog maintainers Steve Jain and Aruna Surya. 

I would like to include the following description into the readme doc for the new blog maintainer role.

--------------------------------------------------README-----------------------------------------------------
The blog creation process will be as follows:

Anyone can submit their blog topic ideas (with a BSQ amount that they think it's worth) **as issues** in the blog repository. 

People **upvote** if they think the blog post should be written or not.

Anyone can start working on any blog post topic but **must** make it known that they are doing so by **commenting on the issue** and announcing that they are beginning work on the blog post. 

The blog maintainer would then **assign** the writer to the blog post and add the writers’ name to the blog writing publication schedule with an assigned publication date.

The blog maintainer will wait until a writer has commented on the issue and announced that they have completed work on a blog topic and edits can commence.

Any contributor can edit the posts but **must** do so as pull requests. This allows for transparency when it comes to editors asking to be compensated.

The maintainer must review and make edits to posts to ensure quality if no one else has done so.
 
Blog topic proposals **must** include a number of BSQ requested for writing the topic but the amount can change if the writer feels that they deserve more or less for their work.

If no one is picking up blog posts to write, The Blog Maintainer should create these posts or find someone that is willing and able to do it.

Anyone can **upvote or downvote** topics and explain why they should or shouldn’t be written.

The blog maintainer will make the final decision on the completeness of the blog posts. 

It is up to the maintainers of the respective communication channels to publish the posts for promotion.

--------------------------------------------------End of README-----------------------------------------------------

Initial tasks to be done as Blog Maintainer:

- Consolidate blog topics under the new Blog repository and label each.
- Create the readme doc which describes the blog writing process.
- Coordinate and communicate with all current writers about the new writing process.
- Create tutorial video describing the Bisq blog writing process

**Comment by m52go** [comment]
Hey @Mycelial1 this should go in the [proposal repository](https://github.com/bisq-network/proposals).

Roles issues are only opened when the role has been confirmed through consensus there.

I'm going to close this for now -- please reopen it in repo linked above.

**Comment by arunasurya** [comment]
By the way, I like your initial tasks. I wanted to add a few more thoughts on the role: first, I think that the blog maintainer should be involved in promoting the posts because the main goal of the project is to grow the user base and attract more people. It is best if the maintainer coordinates with the maintainers of comm. channels and ambassadors to promote the post, and do so for all posts. Second, having objective metrics to evaluate the project may be necessary, so tracking the number of views on the Bisq blog site may be a good idea. This can be included in a monthly blog maintainer report. Third, you may want to mention here or in a separate doc that the writers can file for a compensation after the post has been published. Fourth, and most importantly, you may want to add a sentence that some aspects of the role may change depending on how the project goes and that it is up to the maintainer's discretion, since they will know the project best. Some creative freedom and trust in the maintainer's judgment are important, I think.

**Comment by ghost** [comment]
> because the main goal of the project is to grow the user base and attract more people. 

If Bisq attracts the usual "fast money" people, Bisq could simply explode under the load.
Before attracting simply "more people", I think it could be more cautious to attract wise people.
This april month costed (and still costs) a lot of energy for a scam which concerns only a small part of the volume traded.
imo Bisq is still in the phase where it must be selective regarding the users.
And this concerns many aspects of the project. Blog included.

**Comment by m52go** [comment]
Folks -- this issue is closed. Please post your thoughts here https://github.com/bisq-network/proposals/issues/81.
