### ISSUE TITLE
Wiki Operator

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#92]
Docs: https://bisq.wiki/Wiki_Operator
Team: @bisq-network/wiki-operators

**Comment by cbeams** [comment]
I've assigned @wiz to this role as he is in fact operating the wiki, but am leaving myself assigned until I've handed off domain name ownership and DNS management to him.

**Comment by wiz** [comment]
## Initial report

Bisq wiki seems to be off to a nice start, with the code in GitHub for the Mediawiki extension we've added, the required email configuration, and daily off-site backups of the database and webroot. I've also taken ownership of the domain name so I think handoff from @cbeams is completed.

/cc bisq-network/compensation#515

**Comment by cbeams** [comment]
I've unassigned myself from this role as domain name ownership and DNS have been handed off to @wiz in bisq-network/wiki#7.

**Comment by wiz** [comment]
## Cycle 12 report

* Enabled sitemap generation and submitted the sitemap to Google search console, site is now being indexed https://www.google.com/search?q=site%3Abisq.wiki
* Copied some CSS fixes from Pedro to the dark theme
* Working with support agents to create various articles for FAQ topics

https://github.com/bisq-network/compensation/issues/547

**Comment by wiz** [comment]
## Cycle 13 report

* Wiki is running stable and lots of new editors
* Considering to close user registration now that we have many editors

/cc https://github.com/bisq-network/compensation/issues/569

**Comment by wiz** [comment]
## Cycle 14 report

* Migrated to a new server, running stable
* Had a major spambot attack and had to clean all that out of the DB manually
* Restricted creation of new user accounts to admins only
* Installed 2 new plugins, Universal Translation Plugin and Translate Plugin

/cc https://github.com/bisq-network/compensation/issues/602

**Comment by wiz** [comment]
## Cycle 15 report

* Running stable
* Nothing to report

/cc https://github.com/bisq-network/compensation/issues/632

**Comment by wiz** [comment]
Cycle 20 report

* Renewed the bisq.wiki domain name on Namecheap

**Comment by wiz** [comment]
## Cycle 20 report

* Renewed the bisq.wiki domain name on Namecheap
